### ISSUE TITLE
 View is not visible and can therefore not be clicked!

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#107]
_From [lionghos...@gmail.com](https://code.google.com/u/113949645225071788388/) on November 15, 2010 04:56:12_

What steps will reproduce the problem? 1. Try to invoke clickOnView many times What is the expected output? What do you see instead? I got following exception
junit.framework.AssertionFailedError: View is not visible and can therefore not be clicked!
at com.jayway.android.robotium.solo.Clicker.clickOnScreen(Clicker.java:151)
at com.jayway.android.robotium.solo.Clicker.clickOnScreen(Clicker.java:127)
at com.jayway.android.robotium.solo.Solo.clickOnView(Solo.java:718)
at actester.testgenerator.ACTestGenerator.testActivity(ACTestGenerator.java:57)
at tt.hh.test.MyInstrumentTest.testUsingLib(MyInstrumentTest.java:35)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:204)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:194)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:186)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:520)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1447) What version of the product are you using? On what operating system? 1.9.0 Please provide any additional information below.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=28_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 15, 2010 05:10:38_

Hi,

Can you please give some more details? Are you trying to invoke clickOnView() with the same parameter many times? Do you use a goBack() between the clicks etc etc.

**Comment by renas** [comment]
_From [lionghos...@gmail.com](https://code.google.com/u/113949645225071788388/) on November 15, 2010 05:13:07_

I use following code to invoke it
public void testActivity(ActivityInstrumentationTestCase2<?> test,
			Instrumentation ins, Activity ac) {
		solo = new Solo(ins, ac);
		Random random = new Random(1234);
		int i = 0;
		ArrayList<View> views=null;
		Activity currentActivity = solo.getCurrentActivity();
		Activity previousActivity=currentActivity;
		while (i++ \< 1000) {
			Log.i(ACTESTER,""+i);
			/*
			 * We must use getViews() each time to get new list of views
			 * because views on a single Activity may be updated
			 */
			views=solo.getViews(); 
			if (currentActivity.hasWindowFocus()) {
				View v = views.get(random.nextInt(views.size()));
				if (v.isEnabled()&&v.isShown() ) {
					Log.i(ACTESTER, "click "+v.toString());
					try{
						solo.clickOnView(v);
						//TouchUtils.clickView(test, v);
					}catch (Exception e) {
						Log.i(ACTESTER,e.toString());
					}
					Log.i(ACTESTER, "finished click "+v.toString());
				}
			}else{
				currentActivity=solo.getCurrentActivity();
				if(currentActivity==previousActivity){
					//some dialog pop up
					solo.goBack();
					Log.i(ACTESTER,"Go back");
				}else{
					//a new Activity is created on top of the task stack
					previousActivity=currentActivity;
					Log.i(ACTESTER, "Change Activity to "+currentActivity);
				}
			}
		}
	}

**Comment by renas** [comment]
_From [lionghos...@gmail.com](https://code.google.com/u/113949645225071788388/) on November 15, 2010 05:15:14_

It happens when the code runs hundreds of times.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 15, 2010 05:32:12_

This does not occur when you use TouchUtils instead?

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 15, 2010 05:33:52_

I mean the exact same test case but instead of solo.clickOnView using TouchUtils.clickView(). How does that work?

**Comment by renas** [comment]
_From [lionghos...@gmail.com](https://code.google.com/u/113949645225071788388/) on November 15, 2010 05:34:15_

TouchUtils is OK.

**Comment by renas** [comment]
_From [lionghos...@gmail.com](https://code.google.com/u/113949645225071788388/) on November 15, 2010 05:41:08_

Replacing the call to solo.clickOnView() with TouchUtils.clickView() in the
code I provided and that is the way I used TouchUtils.clickView().

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 15, 2010 06:26:01_

What happens is the following:

if(!view.isShown())
Assert.assertTrue("View is not visible and can therefore not be clicked!", false);

Basically it asks the view if it is shown. And that is after it has waited for 5 seconds. So the view is telling Robotium that it is not shown (says so for 5 seconds). Therefore Robotium fails it as it will not be able to click it (it thinks that it is not shown).

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 15, 2010 07:47:06_

Thanks for this issue. This method will be rewritten in the next release.

**Status:** Accepted  
  **Owner:** renasreda

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 07, 2010 11:38:23_

This issue has been resolved in Robotium 2.0

**Status:** Verified
