### ISSUE TITLE
Not able click on screen with coordinates when the screen location is selected state.

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#116]
_From [anandpai...@gmail.com](https://code.google.com/u/116639303515044083042/) on November 26, 2010 05:15:35_

I am testing google base contacts,which show 4tabs like (dialer,callog,contacts, favorites etc...) What steps will reproduce the problem? 1.launching dialer application.
2.Now i launch the application and keep the coordinates so that i touch the  dialer tab. What is the expected output? What do you see instead? Actual: as my application starts with dialer tab,i am again clicking on the dialer tab - not able to find the view of at that coordinates.
(Tool is not able to find the view if it already selected).

Expected: Should be able to click even the selected area. What version of the product are you using? On what operating system? Robotium 1.9.0 Please provide any additional information below.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=37_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 26, 2010 09:49:36_

Im not sure I understand your issue. Are you using clickOnScreen() or clickOnText()?

**Comment by renas** [comment]
_From [anandpai...@gmail.com](https://code.google.com/u/116639303515044083042/) on November 26, 2010 12:08:48_

I am using clickonscreen method

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 29, 2010 08:27:47_

If it is already selected then probably that is why you do not see that it is being clicked. There is not much logic in clickOnScreen(). I can not see that it would fail to click if you give it the right coordinates.

**Status:** Invalid

**Comment by renas** [comment]
_From [anandpai...@gmail.com](https://code.google.com/u/116639303515044083042/) on December 01, 2010 07:12:12_

12-01 20:37:50.106: INFO/TestRunner(467): ----- begin exception -----
12-01 20:37:50.177: INFO/TestRunner(467): junit.framework.AssertionFailedError: View is not visible and can therefore not be clicked!
12-01 20:37:50.177: INFO/TestRunner(467):     at junit.framework.Assert.fail(Assert.java:47)
12-01 20:37:50.177: INFO/TestRunner(467):     at junit.framework.Assert.assertTrue(Assert.java:20)
12-01 20:37:50.177: INFO/TestRunner(467):     at com.jayway.android.robotium.solo.Clicker.clickOnScreen(Clicker.java:151)
12-01 20:37:50.177: INFO/TestRunner(467):     at com.jayway.android.robotium.solo.Clicker.clickOnText(Clicker.java:283)
12-01 20:37:50.177: INFO/TestRunner(467):     at com.jayway.android.robotium.solo.Solo.clickOnText(Solo.java:744)
12-01 20:37:50.177: INFO/TestRunner(467):     at com.android.sanity.Utils.Contactslist_functions.CreateNewContact_menu(Contactslist_functions.java:26)
12-01 20:37:50.177: INFO/TestRunner(467):     at com.android.sanity.Contacts.TC_C_Copy_SIM_02_001.testTC_C_Copy_SIM_02_001(TC_C_Copy_SIM_02_001.java:45)
12-01 20:37:50.177: INFO/TestRunner(467):     at java.lang.reflect.Method.invokeNative(Native Method)
12-01 20:37:50.177: INFO/TestRunner(467):     at java.lang.reflect.Method.invoke(Method.java:521)
12-01 20:37:50.177: INFO/TestRunner(467):     at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:204)
12-01 20:37:50.177: INFO/TestRunner(467):     at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:194)
12-01 20:37:50.177: INFO/TestRunner(467):     at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:186)
12-01 20:37:50.177: INFO/TestRunner(467):     at junit.framework.TestCase.runBare(TestCase.java:127)
12-01 20:37:50.177: INFO/TestRunner(467):     at junit.framework.TestResult$1.protect(TestResult.java:106)
12-01 20:37:50.177: INFO/TestRunner(467):     at junit.framework.TestResult.runProtected(TestResult.java:124)
12-01 20:37:50.177: INFO/TestRunner(467):     at junit.framework.TestResult.run(TestResult.java:109)
12-01 20:37:50.177: INFO/TestRunner(467):     at junit.framework.TestCase.run(TestCase.java:118)
12-01 20:37:50.177: INFO/TestRunner(467):     at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
12-01 20:37:50.177: INFO/TestRunner(467):     at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
12-01 20:37:50.177: INFO/TestRunner(467):     at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:520)
12-01 20:37:50.177: INFO/TestRunner(467):     at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1447)
12-01 20:37:50.177: INFO/TestRunner(467): ----- end exception -----

**Comment by renas** [comment]
_From [anandpai...@gmail.com](https://code.google.com/u/116639303515044083042/) on December 01, 2010 07:12:36_

Plz check the log
