### ISSUE TITLE
clickLongOnText fails when using uncommon characters

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#131]
_From [finalJus...@googlemail.com](https://code.google.com/u/109930177564936938952/) on December 29, 2010 03:02:53_

What steps will reproduce the problem? 1. Make an App with clickable text: "Li$t wit&#37; ch\" without ". maybe this step is not needed to reproduce the exception.
2. Make an Test-App with test case that uses mSolo.clickLongOnText("Li$t wit&#37; ch\\");
3. Run the test case and there will be an exception:

java.util.regex.PatternSyntaxException: Syntax error U_REGEX_BAD_ESCAPE_SEQUENCE near index 13:
Li$t wit&#37; ch\
^
at com.ibm.icu4jni.regex.NativeRegEx.open(Native Method)
at java.util.regex.Pattern.compileImpl(Pattern.java:264)
at java.util.regex.Pattern.<init>(Pattern.java:239)
at java.util.regex.Pattern.compile(Pattern.java:179)
at com.jayway.android.robotium.solo.Clicker.clickOnText(Clicker.java:252)
at com.jayway.android.robotium.solo.Solo.clickLongOnText(Solo.java:817)
... What is the expected output? What do you see instead? I want the text to be long clicked :-) What version of the product are you using? On what operating system? I am using robotium 2.0.2 on Win 7 - 64 bit
tested on Android 1.5 / 2.3 with emulator Please provide any additional information below.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=52_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 29, 2010 05:50:22_

Hi,

If you want to click or search for strings with special characters or symbols you need to add \\ before them. This is due to the regex support that is included into the click and search methods. If you add \\ before them it will work. 

/Renas

**Status:** Invalid

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 29, 2010 06:49:25_

To clarify you need to add \\ before the special charachters and symbols. An example of how it should look like:

clickLongOnText("Li\\$t wit\\% ch\\\");

**Comment by renas** [comment]
_From [finalJus...@googlemail.com](https://code.google.com/u/109930177564936938952/) on December 29, 2010 23:55:04_

thanks for the response!!! that was very helpful. now it works and "searchText" seems to work too. thanks!!!
