### ISSUE TITLE
Problem with two test cases for robotium

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#138]
_From [guost...@gmail.com](https://code.google.com/u/110478850486487008482/) on January 24, 2011 18:48:52_

What steps will reproduce the problem? When we run two test methods inside the class first one is working fine but second one is failing with some errors. If you run these two methods separately working fine without having any problems. What is the expected output? What do you see instead? both methods has to work without having any problems What version of the product are you using? On what operating system? robotium 2.0 and XP Please provide any additional information below. when run the second testcase,it would goback automaticly but also some sentence did not run. for example in calculator:

public void test0() throws Exception
    {
        mySolo.drag(238, 4, 206, 206, 10);
        mySolo.clickOnButton("cos");
        mySolo.clickOnButton(11);
    }
  @Smoke
    public void test1() throws Exception
    {
        mySolo.drag(238, 4, 206, 206, 10);
        mySolo.clickOnButton("cos");
        mySolo.clickOnButton(11);
     }
test1 could not run successfully,when run mySolo.drag(238, 4, 206, 206, 10);it would automatic quit.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=59_

**Comment by renas** [comment]
_From [guost...@gmail.com](https://code.google.com/u/110478850486487008482/) on January 24, 2011 18:49:54_

my email :guost295@gmail.com.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on January 24, 2011 21:58:31_

Hi, You should add a waitForX() before the drag to make sure that the activity is loaded before trying to use drag(). If that does not work then please paste the log.

**Status:** Invalid

**Comment by renas** [comment]
_From [guost...@gmail.com](https://code.google.com/u/110478850486487008482/) on January 24, 2011 23:33:15_

thank you for your answer.
but the problem is still exist.i add  mySolo.waitForActivity(LAUNCHER_ACTIVITY_FULL_CLASSNAME, 10000) before trying to use drag().        LAUNCHER_ACTIVITY_FULL_CLASSNAME =com.android.calculator2.Calculator.
the log is :
 junit.framework.AssertionFailedError: There is no Button with index 11
at com.jayway.android.robotium.solo.Clicker.clickOn(Clicker.java:333)
at com.jayway.android.robotium.solo.Solo.clickOnButton(Solo.java:908)
at com.android.newoppocalculator.newoppocalculator.test1(newoppocalculator.java:65)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(SourceFile:235)
at android.test.InstrumentationTestCase.runTest(SourceFile:225)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:217)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:200)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:185)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:551)
at android.app.Instrumentation$InstrumentationThread.run(SourceFile:1482)

**Comment by renas** [comment]
_From [guost...@gmail.com](https://code.google.com/u/110478850486487008482/) on January 24, 2011 23:37:20_

i add  mySolo.waitForActivity(LAUNCHER_ACTIVITY_FULL_CLASSNAME, 10000)  in test0 and test1 before trying to use drag(),it says :There is no Button with index 11,because when it run the mySolo.clickOnButton("cos"),then it quit automaticly.

thank you again.

**Comment by renas** [comment]
_From [guost...@gmail.com](https://code.google.com/u/110478850486487008482/) on January 25, 2011 03:37:29_

Thank you for your reply.
  but the problem is still exist.i add
mySolo.waitForActivity(LAUNCHER_ACTIVITY_FULL_CLASSNAME, 10000) before
trying to use drag().        LAUNCHER_ACTIVITY_FULL_CLASSNAME
=com.android.calculator2.Calculator.
the log is :
 junit.framework.AssertionFailedError: There is no Button with index 11
at com.jayway.android.robotium.solo.Clicker.clickOn(Clicker.java:333)
at com.jayway.android.robotium.solo.Solo.clickOnButton(Solo.java:908)
at
com.android.newoppocalculator.newoppocalculator.test1(newoppocalculator.java:65)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(SourceFile:235)
at android.test.InstrumentationTestCase.runTest(SourceFile:225)
at
android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:217)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:200)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:185)
at
android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:551)
at android.app.Instrumentation$InstrumentationThread.run(SourceFile:1482)

i add  mySolo.waitForActivity(LAUNCHER_ACTIVITY_FULL_CLASSNAME, 10000)  in
test0 and test1 before trying to use drag(),it says :There is no Button with
index 11,because when it run the mySolo.clickOnButton("cos"),then it quit
automaticly.
thank you again.
