### ISSUE TITLE
 New problem with two test cases for robotium

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#146]
_From [guost...@gmail.com](https://code.google.com/u/110478850486487008482/) on February 09, 2011 17:35:18_

What steps will reproduce the problem? When we run two test methods inside the class first one is working fine but second one is failing with some errors. If you run these two methods separately working fine without having any problems. What is the expected output? What do you see instead? both methods has to work without having any problems What version of the product are you using? On what operating system? robotium 2.0 and XP Please provide any additional information below. 1. public void test0() throws Exception
    {
        mySolo.drag(238, 4, 206, 206, 10);
        mySolo.clickOnButton("cos");
        mySolo.clickOnButton(11);
    }
  @Smoke
    public void test1() throws Exception
    {
        mySolo.drag(238, 4, 206, 206, 10);
        mySolo.clickOnButton("cos");
  
      mySolo.clickOnButton(11);
     }
test1 could not run successfully,when run mySolo.drag(238, 4, 206, 206, 10);it would automatic quit.

2.i add  mySolo.waitForActivity(LAUNCHER_ACTIVITY_FULL_CLASSNAME, 10000) before trying to use drag().        LAUNCHER_ACTIVITY_FULL_CLASSNAME =com.android.calculator2.Calculator.but it still run failly.

3.the log is :
 junit.framework.AssertionFailedError: There is no Button with index 11
at com.jayway.android.robotium.solo.Clicker.clickOn(Clicker.java:333)
at com.jayway.android.robotium.solo.Solo.clickOnButton(Solo.java:908)
at com.android.newoppocalculator.newoppocalculator.test1(newoppocalculator.java:65)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(SourceFile:235)
at android.test.InstrumentationTestCase.runTest(SourceFile:225)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:217)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:200)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:185)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:551)
at android.app.Instrumentation$InstrumentationThread.run(SourceFile:1482)

_Original issue: http://code.google.com/p/robotium/issues/detail?id=67_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on February 09, 2011 22:45:12_

Please do the following:

1. Change to Robotium 2.1? 

2. You have to add a wait before doing a drag. Try waitForText("any text on the screen", "10 000");

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on February 09, 2011 22:58:56_

Also please paste the log:

logcat.

**Comment by renas** [comment]
_From [guost...@gmail.com](https://code.google.com/u/110478850486487008482/) on February 14, 2011 20:48:07_

thank you for your reply so much.I also follow your method to solve this problem,but finally it still fail.now i put the code and logcat to you ,and look forward to your reply again,and i will appreciate you very much.

I did as follow:
1.Change to Robotium 2.1

2. add a wait before doing a drag. Try  mySolo.waitForActivity(LAUNCHER_ACTIVITY_FULL_CLASSNAME, 10000);

thank you.................

**Attachment:** [code.txt logcat.txt](http://code.google.com/p/robotium/issues/detail?id=67#hc3)

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on February 14, 2011 21:54:58_

I am sorry but I do not know how to help you. This has nothing to do with Robotium. It is an application problem. The only interesting I could see in the log was:

junit.framework.AssertionFailedError: Button with the text: sin is not found!

Otherwise I can not see anything interesting in the log and definitely not something that shows Robotium crashing etc. 

Please read this page: https://code.google.com/p/robotium/wiki/Getting_Started

**Status:** Invalid

**Comment by renas** [comment]
_From [guost...@gmail.com](https://code.google.com/u/110478850486487008482/) on February 16, 2011 03:53:47_

i will also thank you so much.I ever see issue #30 in this,the probrem he meet with is the same,and he said he solved this problem,but when i turn to ask for help,he never answer me,now i will excepte for his answer to solve this problem.

thank your reply again,if you have spare time,could you hava a look at issue #30 ...

**Comment by renas** [comment]
_From [guost...@gmail.com](https://code.google.com/u/110478850486487008482/) on February 16, 2011 03:59:02_

Issue 30 :  Problem with two test cases

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on February 16, 2011 04:02:05_

Yes it seems as if he fixed the problem. Try to email him instead. I hope you will find a solution.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on February 16, 2011 04:12:43_

Dont forget to use tearDown(), look at the example test project.

**Comment by renas** [comment]
_From [guost...@gmail.com](https://code.google.com/u/110478850486487008482/) on February 17, 2011 17:48:11_

thank you ,i used tearDown().
i ever email the issue #30 ,but he always don't reply me,now i hope he can reply me as soon as possible.
thank you !
