### ISSUE TITLE
Samples project does not build with 2.1

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#151]
_From [mosa...@gmail.com](https://code.google.com/u/105460375065140382634/) on February 15, 2011 23:11:14_

What steps will reproduce the problem? 1. Start a 2.3 emulator
2. Update the robotium version in the parent pom of the samples project to 2.1
3. Run a build with mvn clean install What is the expected output? What do you see instead? Build to succeed but I get

net.tawacentral.roger.secrets.SecretsForAndroidRobotiumTest:
Failure in testCreateSecret:
junit.framework.AssertionFailedError
        at net.tawacentral.roger.secrets.SecretsForAndroidRobotiumTest.testCreateSecret(SecretsForAndroidRobotiumTest.java:55)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:204)
        at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:194)
        at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:186)
        at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
        at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
        at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:529)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1447)
. What version of the product are you using? On what operating system? Latest samples project off github Please provide any additional information below. Running on Ubuntu 10.10, Maven 3.0.2, Android SDK r9

_Original issue: http://code.google.com/p/robotium/issues/detail?id=72_

**Comment by renas** [comment]
_From [h...@josefson.org](https://code.google.com/u/104400114270051607683/) on February 15, 2011 23:56:25_

Hi Manfred,

Thanks for filing.

Yes, I'm sorry I haven't kept the Robotium samples up to date with Robotium itself. If you know what's wrong, you are welcome to fix it and send a pull request my way on github.

/Hugo

**Status:** Accepted

**Comment by renas** [comment]
_From [mosa...@gmail.com](https://code.google.com/u/105460375065140382634/) on February 16, 2011 09:03:40_

I was hoping you or Renas would do that ;-)

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on February 20, 2011 22:02:11_

I am sure Hugo will fix this :)

**Status:** WontFix

**Comment by renas** [comment]
_From [mosa...@gmail.com](https://code.google.com/u/105460375065140382634/) on February 21, 2011 08:48:40_

I thought that the project is a GREAT example for the library and you should feel responsible too.. maybe you should do it to get familiar with it ;-)

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on February 21, 2011 08:50:58_

Hehe, maybe I will ;)
