### ISSUE TITLE
Android Phone.apk test with Robotium

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#162]
_From [feu...@gmail.com](https://code.google.com/u/103174306080771765636/) on March 09, 2011 03:00:53_

Hello,
I am newbie in Java programming and Android-testing. i will like to test the android Phone.apk application with robotium-solo-2.2.jar.   
I follow all the steps on this links successfully: https://code.google.com/p/robotium/wiki/RobotiumForPreInstalledApps .

my test application:

package com.android.contacts.phoneTesting;
import android.app.Activity;
import com.jayway.android.robotium.solo.Solo;

import android.test.ActivityInstrumentationTestCase2;

@SuppressWarnings("unchecked")
public class PhonecallTest extends ActivityInstrumentationTestCase2{

private static final String TARGET_PACKAGE_ID = "com.android.contacts";

	private static final String LAUNCHER_ACTIVITY_FULL_CLASSNAME = 
		"com.android.contacts.DialtactsActivity";

	private static Class<?> launcherActivityClass;

	static {

		try {

			launcherActivityClass = Class.forName(LAUNCHER_ACTIVITY_FULL_CLASSNAME);

		} catch (ClassNotFoundException e) {

			throw new RuntimeException(e);

		}

	}

        @SuppressWarnings("unchecked")	
  
	public PhonecallTest() throws ClassNotFoundException {

		super(TARGET_PACKAGE_ID, launcherActivityClass);

	}

	private Solo solo;
	private Activity activity;
	
	@Override
	protected void setUp() throws Exception {

               setUp();
		activity = getActivity();
		solo = new Solo(getInstrumentation(), activity);
	}

        
	public void testDial()throws Exception  {
		solo.enterText(0, "5");
		solo.enterText(1, "3");
		solo.enterText(3, "7");
		solo.enterText(4, "3");
		solo.enterText(5, "9");
		solo.enterText(6, "1");
		solo.clickOnButton("Dial");
		assertTrue(solo.searchEditText("537391"));
		}

	
	@Override
	public void tearDown() throws Exception {

		try {

			solo.finalize();

		} catch (Throwable e) {

			e.printStackTrace();

		}

		activity.finish();

		super.tearDown();

	}

}

AndroidManifest.xml

\<?xml version="1.0" encoding="utf-8"?>
\<manifest xmlns:android=" http://schemas.android.com/apk/res/android "
      package="com.android.contacts.phoneTesting"
      android:versionCode="1"
      android:versionName="1.0"
      android:sharedUserId="android.uid.phone" >

    \<uses-sdk android:minSdkVersion="7" />
    \<instrumentation android:targetPackage="com.android.contacts" android:name="android.test.InstrumentationTestRunner" />
    \<application android:icon="@drawable/icon" android:label="@string/app_name">

    \<uses-library android:name="android.test.runner" />
    \</application>
\</manifest> What is the expected output? What do you see instead? chinco@chinco-desktop:~/android/dev$ adb shell am instrument -w com.android.contacts.phoneTesting/android.test.InstrumentationTestRunner

INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0

adb logs

W/dalvikvm(12449): Exception Ljava/lang/RuntimeException; thrown during Lcom/android/contacts/phoneTesting/PhonecallTest;.<clinit>
E/dalvikvm(12449): Class lookup Ljava/lang/Object; attemped while exception Ljava/lang/ExceptionInInitializerError; pending
I/dalvikvm(12449): DALVIK THREADS:
I/dalvikvm(12449): "main" prio=5 tid=3 RUNNABLE
I/dalvikvm(12449):   | group="main" sCount=0 dsCount=0 s=N obj=0x4001b2d0 self=0xbd40
I/dalvikvm(12449):   | sysTid=12449 nice=0 sched=0/0 cgrp=unknown handle=-1343997288
I/dalvikvm(12449):   at java.lang.Class.getDeclaredConstructors(Native Method)
I/dalvikvm(12449):   at java.lang.Class.getConstructors(Class.java:509)
I/dalvikvm(12449):   at android.test.suitebuilder.TestGrouping$TestCasePredicate.hasValidConstructor(TestGrouping.java:226)
I/dalvikvm(12449):   at android.test.suitebuilder.TestGrouping$TestCasePredicate.apply(TestGrouping.java:215)
I/dalvikvm(12449):   at android.test.suitebuilder.TestGrouping$TestCasePredicate.apply(TestGrouping.java:211)
I/dalvikvm(12449):   at android.test.suitebuilder.TestGrouping.select(TestGrouping.java:170)
I/dalvikvm(12449):   at android.test.suitebuilder.TestGrouping.selectTestClasses(TestGrouping.java:160)
I/dalvikvm(12449):   at android.test.suitebuilder.TestGrouping.testCaseClassesInPackage(TestGrouping.java:154)
I/dalvikvm(12449):   at android.test.suitebuilder.TestGrouping.addPackagesRecursive(TestGrouping.java:115)
I/dalvikvm(12449):   at android.test.suitebuilder.TestSuiteBuilder.includePackages(TestSuiteBuilder.java:103)
I/dalvikvm(12449):   at android.test.InstrumentationTestRunner.onCreate(InstrumentationTestRunner.java:323)
I/dalvikvm(12449):   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3982)
I/dalvikvm(12449):   at android.app.ActivityThread.access$2900(ActivityThread.java:119)
I/dalvikvm(12449):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1901)
I/dalvikvm(12449):   at android.os.Handler.dispatchMessage(Handler.java:99)
I/dalvikvm(12449):   at android.os.Looper.loop(Looper.java:123)
I/dalvikvm(12449):   at android.app.ActivityThread.main(ActivityThread.java:4363)
I/dalvikvm(12449):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm(12449):   at java.lang.reflect.Method.invoke(Method.java:521)
I/dalvikvm(12449):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
I/dalvikvm(12449):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
I/dalvikvm(12449):   at dalvik.system.NativeStart.main(Native Method)

I just wanted the test  to start the Phone  application and dial some number.
please can you help me out of this problem ?

what is wrong on my implementation? 

thank You 
Chindji

_Original issue: http://code.google.com/p/robotium/issues/detail?id=83_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 09, 2011 03:33:46_

Have you installed the test project on device before trying to run the test suite?

**Comment by renas** [comment]
_From [feu...@gmail.com](https://code.google.com/u/103174306080771765636/) on March 09, 2011 04:30:05_

yes I install it on /data/app

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 09, 2011 05:13:35_

I am not sure what the problem is. Have you tried to run the test project from development tools instead? http://www.youtube.com/watch?v=v1z39IIA7kY

**Comment by renas** [comment]
_From [feu...@gmail.com](https://code.google.com/u/103174306080771765636/) on March 09, 2011 06:31:27_

yes I run the test project from development tools. but it was not working. i have the same error.
 adb log.

I/ActivityManager(  805): Start proc com.android.contacts for restart com.android.contacts: pid=1418 uid=1001 gids={1015}
W/ActivityManager(  805): Crash of app com.android.contacts running instrumentation ComponentInfo{com.android.contacts.phoneTesting/android.test.InstrumentationTestRunner}
I/instrumentation(  981): INSTRUMENTATION_RESULT: shortMsg=Process crashed.
I/instrumentation(  981): INSTRUMENTATION_CODE: 0
D/ActivityManager(  805): Uninstalling process com.android.contacts
D/ActivityManager(  805): Force removing process ProcessRecord{439ac520 1418:com.android.contacts/1001} (com.android.contacts/1001)
I/Process (  805): Sending signal. PID: 1418 SIG: 9
D/Zygote  (  761): Process 1412 terminated by signal (11)
I/ActivityManager(  805): Start proc com.android.contacts for added application com.android.contacts: pid=1419 uid=1001 gids={1015}
D/ddm-heap( 1419): Got feature list request

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 09, 2011 08:16:36_

Others have had problems with the contacts applicaiton. Try with the pre-installed calculator instead. I see nothing wrong in how you have created your test case.

**Status:** Invalid

**Comment by renas** [comment]
_From [feu...@gmail.com](https://code.google.com/u/103174306080771765636/) on March 10, 2011 00:07:21_

I test already the pre-installed calculator. the test was successful. My next steps was the contacts application. 
Thank you for your support.

**Comment by renas** [comment]
_From [mydreams...@gmail.com](https://code.google.com/u/103627847626509511575/) on June 26, 2012 05:02:35_

Can somebody provide solution for it. I am also facing the same issue

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 26, 2012 06:01:19_

This is what you need to do:

I tested the Contacts.apk with Robotium in emulator.

If you want to test native applications(e.g. Contacts.apk, Settings.apk) then you have to use test key that is in android source(/build/target/product/security). There is README file in that place. Contacts.apk use 'shared' key.

**Comment by renas** [comment]
_From [mrawat...@gmail.com](https://code.google.com/u/116994252668576801416/) on August 08, 2012 22:30:50_

Any one tell me, in case of pre-installed app Calculator. When i use to adb push the calculator then the icon in emulator goes invisible.

**Comment by renas** [comment]
_From [d.mishr...@gmail.com](https://code.google.com/u/111513416255843522252/) on October 03, 2012 06:49:38_

Can some one tell me how to add test project without having the complete Package and source code for the application. Like I don't have the complete source code for contacts.apk and while creating test project it asks for the package to browse.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on October 03, 2012 07:04:34_

Please see: https://code.google.com/p/robotium/wiki/RobotiumForPreInstalledApps

**Comment by renas** [comment]
_From [d.mishr...@gmail.com](https://code.google.com/u/111513416255843522252/) on October 04, 2012 01:54:46_

Thanks for the reply.
 But the above link only tells about the pushing the new signed apk. While creating robotium test project it asks for the select test target to select from the existing project but for inbuilt apk we don't have the target project.(File > New > other > Android Test project >do next > Give project name>  Select Test Target ?  here what to select as I don't have the complete code for inbuilt apk).

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on October 04, 2012 01:56:21_

Please download the tutorial test android apk file with Robotium. https://code.google.com/p/robotium/wiki/RobotiumTutorials

**Comment by renas** [comment]
_From [d.mishr...@gmail.com](https://code.google.com/u/111513416255843522252/) on October 04, 2012 04:02:00_

The test android apk(AndroidCalculator) has calculator package and the source code for calculator. So I will be able to test only calculator package not other packages like settings. I want to test settings package but I don't have the source code for it. That's why I was asking what to select in "select Test Target" field in my previous comment.
