### ISSUE TITLE
Code coverage for  Robotium tests with Emma

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#168]
_From [feu...@gmail.com](https://code.google.com/u/103174306080771765636/) on March 21, 2011 04:36:02_

Hello, What steps will reproduce the problem? I am trying to integrate Emma on my build system for Robotium test coverage. 
I allays have this error when : export EMMA_INSTRUMENT=true What is the expected output? What do you see instead? UNEXPECTED TOP-LEVEL EXCEPTION:

com.android.dx.cf.code.SimException: local variable type mismatch: attempt to set or access a value of type java.lang.Object using a local variable of type int. This is symptomatic of .class transformation tools that ignore local variable information.

	at com.android.dx.cf.code.BaseMachine.throwLocalMismatch(BaseMachine.java:537)

	at com.android.dx.cf.code.Simulator$SimVisitor.visitLocal(Simulator.java:523)

	at com.android.dx.cf.code.BytecodeArray.parseInstruction(BytecodeArray.java:472)

	at com.android.dx.cf.code.Simulator.simulate(Simulator.java:99)

	at com.android.dx.cf.code.Ropper.processBlock(Ropper.java:678)

	at com.android.dx.cf.code.Ropper.doit(Ropper.java:633)

	at com.android.dx.cf.code.Ropper.convert(Ropper.java:250)

	at com.android.dx.dex.cf.CfTranslator.processMethods(CfTranslator.java:252)

	at com.android.dx.dex.cf.CfTranslator.translate0(CfTranslator.java:131)

	at com.android.dx.dex.cf.CfTranslator.translate(CfTranslator.java:85)

	at com.android.dx.command.dexer.Main.processClass(Main.java:299)

	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:278)

	at com.android.dx.command.dexer.Main.access$100(Main.java:56)

	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:229)

	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)

	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:130)

	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:108)

	at com.android.dx.command.dexer.Main.processOne(Main.java:247)

	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:183)

	at com.android.dx.command.dexer.Main.run(Main.java:139)

	at com.android.dx.command.dexer.Main.main(Main.java:120)

	at com.android.dx.command.Main.main(Main.java:89)

...at bytecode offset 00000071

locals[0000]: Lcom/jayway/android/robotium/solo/Presser;

locals[0001]: I

locals[0002]: I

locals[0003]: [I

locals[0004]: I

locals[0005]: [Z

stack[top0]: type{java.lang.SecurityException}

...while working on block 0071

...while working on method pressMenuItem:(II)V

...while processing pressMenuItem (II)V

...while processing com/jayway/android/robotium/solo/Presser.class

1 error; aborting

make: *** [out/target/common/obj/APPS/PhoneCallTests_intermediates/classes.dex] Fehler 1 What version of the product are you using? On what operating system? robotium-solo-2.2 
Operating system : Ubuntu 10.04 LTS Please provide any additional information below. Please can you help me out of this problem?

Thank You. 
Chindji

_Original issue: http://code.google.com/p/robotium/issues/detail?id=89_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 26, 2011 02:07:26_

Please ask this question in the forum. http://groups.google.com/group/robotium-developers

**Status:** Invalid
