### ISSUE TITLE
Click Long on Screen on device home screen gives exception

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#240]
_From [pr...@anvaya.net](https://code.google.com/u/102624229117984655215/) on September 20, 2011 11:38:36_

What steps will reproduce the problem? 1. clickLongOnScreen with screen coordinates to open folders after clicking on device HOME to see the Folders context menu. 2. 3. What is the expected output? What do you see instead? The Folders menu on the device must open. Instead I get exception:
junit.framework.AssertionFailedError: Click can not be completed! Something is in the way e.g. the keyboard.
        at com.jayway.android.robotium.solo.Clicker.clickLongOnScreen(Clicker.java:98)
        at com.jayway.android.robotium.solo.Solo.clickLongOnScreen(Solo.java:651) What version of the product are you using? On what operating system? solo 2.2, windows xp Please provide any additional information below. Basically I need to click long on screen to open the folders context menu to click on a folder inside the context menu. but i got the screen coordinates by the following:
int width = pageSolo.getCurrentActivity().getWindowManager().getDefaultDisplay()
        .getWidth();
		int height = pageSolo.getCurrentActivity().getWindowManager().getDefaultDisplay()
        .getHeight();

I used the width and height obtained to click long on screen after clicking on device HOME button but see exceptions. I tried width/2, height/2 yet the same issue.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=161_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on September 20, 2011 22:13:45_

You are not allowed to interact with another application (home button belongs to another application. Please see our QA page.

**Status:** Invalid
