### ISSUE TITLE
Is there any compatibility issues with app created using monodroid?

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#254]
_From [rasangaKS](https://code.google.com/u/rasangaKS/) on October 14, 2011 08:19:16_

hi 
i am also trying to drive a app created using mono droid, and test keep on getting crashed at run time..
is there any known issues with mono(.net) compatibility..
for example in my app the c# name space and the activity class name is shown as the activity class name in logcat..
for example the app apk file is packaged as Package.Package.apk
and the main activity has the namaspace package and the class as the testActivity and in the logcat the loading activity is shown as 
Package.Package/package.testActivity 

so i am using the package name as Package.Package and the full class as Package.Package.package.testActivity 

is this the correct way to use?

W/dalvikvm(  401): Exception Ljava/lang/RuntimeException; thrown during Lcom/rasanga/tests/LoginActivityTest;.<clinit>
E/dalvikvm(  401): Class lookup Ljava/lang/Class; attempted while exception Ljava/lang/ExceptionInInitializerError; pending
I/dalvikvm(  401): DALVIK THREADS:
I/dalvikvm(  401): "main" prio=5 tid=1 RUNNABLE
I/dalvikvm(  401):   | group="main" sCount=0 dsCount=0 s=N obj=0x4001d8e0 self=0xccb0
I/dalvikvm(  401):   | sysTid=401 nice=0 sched=0/0 cgrp=default handle=-1345026008
I/dalvikvm(  401):   | schedstat=( 4558093929 339015059 217 )
I/dalvikvm(  401):   at java.lang.Class.getDeclaredConstructors(Native Method)
I/dalvikvm(  401):   at java.lang.Class.getConstructors(Class.java:499)
I/dalvikvm(  401):   at android.test.suitebuilder.TestGrouping$TestCasePredicate.hasValidConstructor(TestGrouping.java:226)
I/dalvikvm(  401):   at android.test.suitebuilder.TestGrouping$TestCasePredicate.apply(TestGrouping.java:215)
I/dalvikvm(  401):   at android.test.suitebuilder.TestGrouping$TestCasePredicate.apply(TestGrouping.java:211)
I/dalvikvm(  401):   at android.test.suitebuilder.TestGrouping.select(TestGrouping.java:170)
I/dalvikvm(  401):   at android.test.suitebuilder.TestGrouping.selectTestClasses(TestGrouping.java:160)
I/dalvikvm(  401):   at android.test.suitebuilder.TestGrouping.testCaseClassesInPackage(TestGrouping.java:154)
I/dalvikvm(  401):   at android.test.suitebuilder.TestGrouping.addPackagesRecursive(TestGrouping.java:115)
I/dalvikvm(  401):   at android.test.suitebuilder.TestSuiteBuilder.includePackages(TestSuiteBuilder.java:103)
I/dalvikvm(  401):   at android.test.InstrumentationTestRunner.onCreate(InstrumentationTestRunner.java:360)
I/dalvikvm(  401):   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4218)
I/dalvikvm(  401):   at android.app.ActivityThread.access$3000(ActivityThread.java:125)
I/dalvikvm(  401):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
I/dalvikvm(  401):   at android.os.Handler.dispatchMessage(Handler.java:99)
I/dalvikvm(  401):   at android.os.Looper.loop(Looper.java:123)
I/dalvikvm(  401):   at android.app.ActivityThread.main(ActivityThread.java:4627)
I/dalvikvm(  401):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm(  401):   at java.lang.reflect.Method.invoke(Method.java:521)
I/dalvikvm(  401):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
I/dalvikvm(  401):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
I/dalvikvm(  401):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm(  401):
I/dalvikvm(  401): "Binder Thread `#2`" prio=5 tid=6 NATIVE
I/dalvikvm(  401):   | group="main" sCount=0 dsCount=0 s=N obj=0x44f3ade0 self=0x11c6c0

_Original issue: http://code.google.com/p/robotium/issues/detail?id=175_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on October 14, 2011 17:20:19_

Unfortunately I have no experience in monodroid so this is not something that I can help you with.

**Status:** Invalid
