### ISSUE TITLE
Failure with Dialog on Android 4.0

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#265]
_From [andi.hof...@gmail.com](https://code.google.com/u/111216911044559284132/) on November 15, 2011 23:39:04_

What steps will reproduce the problem? 1. solo.clickOnText("Text")
2. solo.clearEditText(0)
3. solo.enterText("Text_New")
4. solo.clickOnButton("OK") What is the expected output? What do you see instead? Expected output would be an opening Dialog Window, clear the Textfield, enter the Text "Text_New" click on "OK" Button.

I do this for many elements in a List (Preferences), and sometimes the Dialog Window opens sometimes not, but I always get this failure:

junit.framework.AssertionFailedError: EditText with index -1 is not available!
at com.jayway.android.robotium.solo.Waiter.waitForAndGetView(Waiter.java:359)
at com.jayway.android.robotium.solo.Solo.clearEditText(Solo.java:1257) What version of the product are you using? On what operating system? Robotium 3.0 Please provide any additional information below. This problem only occurs since I have used Robotium 3.0 and this problem is only on Android4.0 for all other Android versions it works perfectly. With Robotium 2.6 it also works on Android 4.0.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=186_

**Comment by renas** [comment]
_From [andi.hof...@gmail.com](https://code.google.com/u/111216911044559284132/) on November 15, 2011 23:43:04_

It works for Robotium 2.5 not 2.6, sry for this mistake.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 16, 2011 00:25:08_

Thanks for this. Would it be possible for you to send me your application?

**Status:** Accepted  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 16, 2011 00:27:19_

Please update your test case so that you use: waitForText(Something shown in the dialog) before clearEditText() my guess is that it is a timing issue.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on January 09, 2012 04:00:54_

This has been fixed in Robotium 3.1. Remember to always use a waitFor method when a new window is expected to open.

**Status:** Verified
