### ISSUE TITLE
solo.clickOnText does not work on 4.0.1

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#313]
_From [GillesBa...@gmail.com](https://code.google.com/u/101329230007579602900/) on March 14, 2012 08:26:13_

What steps will reproduce the problem? 1. run a script with solo.clickOnText("Aanmelden"); on a 2.2.1 device (Samsung Galaxy S)
2. run exactly the same script on a Galaxy Nexus with Android 4.0 3. What is the expected output? What do you see instead? I expect the scripts to do exactly the same on these devices, and not a crash on the Nexus What version of the product are you using? On what operating system? Robotium 3.1
OS 2.2.1
OS 4.0.1 Please provide any additional information below. I have script which runs fine on a Galaxy S, but crashes almost immediately when it arrives at a clickOnText statement. Crashlog below:

03-14 16:10:13.074: INFO/TestRunner(19796): ----- begin exception -----
03-14 16:10:13.081: INFO/TestRunner(19796): java.lang.RuntimeException: java.lang.NullPointerException
03-14 16:10:13.081: INFO/TestRunner(19796):     at com.jayway.android.robotium.solo.Searcher.searchFor(Searcher.java:107)
03-14 16:10:13.081: INFO/TestRunner(19796):     at com.jayway.android.robotium.solo.Waiter.waitForText(Waiter.java:253)
03-14 16:10:13.081: INFO/TestRunner(19796):     at com.jayway.android.robotium.solo.Clicker.clickOnText(Clicker.java:254)
03-14 16:10:13.081: INFO/TestRunner(19796):     at com.jayway.android.robotium.solo.Solo.clickOnText(Solo.java:828)
03-14 16:10:13.081: INFO/TestRunner(19796):     at com.xxx.mobile.test.flows.Utils.menu(Utils.java:656)
03-14 16:10:13.081: INFO/TestRunner(19796):     at com.xxx.mobile.test.flows.zAddressbook.test(zAddressbook.java:35)
03-14 16:10:13.081: INFO/TestRunner(19796):     at java.lang.reflect.Method.invokeNative(Native Method)
03-14 16:10:13.081: INFO/TestRunner(19796):     at java.lang.reflect.Method.invoke(Method.java:511)
03-14 16:10:13.081: INFO/TestRunner(19796):     at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
03-14 16:10:13.081: INFO/TestRunner(19796):     at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
03-14 16:10:13.081: INFO/TestRunner(19796):     at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:186)
03-14 16:10:13.081: INFO/TestRunner(19796):     at junit.framework.TestCase.runBare(TestCase.java:127)
03-14 16:10:13.081: INFO/TestRunner(19796):     at junit.framework.TestResult$1.protect(TestResult.java:106)
03-14 16:10:13.081: INFO/TestRunner(19796):     at junit.framework.TestResult.runProtected(TestResult.java:124)
03-14 16:10:13.081: INFO/TestRunner(19796):     at junit.framework.TestResult.run(TestResult.java:109)
03-14 16:10:13.081: INFO/TestRunner(19796):     at junit.framework.TestCase.run(TestCase.java:118)
03-14 16:10:13.081: INFO/TestRunner(19796):     at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
03-14 16:10:13.081: INFO/TestRunner(19796):     at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
03-14 16:10:13.081: INFO/TestRunner(19796):     at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:537)
03-14 16:10:13.081: INFO/TestRunner(19796):     at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1551)
03-14 16:10:13.081: INFO/TestRunner(19796): Caused by: java.lang.NullPointerException
03-14 16:10:13.081: INFO/TestRunner(19796):     at com.jayway.android.robotium.solo.ViewFetcher.getNonDecorViews(ViewFetcher.java:188)
03-14 16:10:13.081: INFO/TestRunner(19796):     at com.jayway.android.robotium.solo.ViewFetcher.getAllViews(ViewFetcher.java:112)
03-14 16:10:13.081: INFO/TestRunner(19796):     at com.jayway.android.robotium.solo.ViewFetcher.getViews(ViewFetcher.java:232)
03-14 16:10:13.081: INFO/TestRunner(19796):     at com.jayway.android.robotium.solo.ViewFetcher.getCurrentViews(ViewFetcher.java:430)
03-14 16:10:13.081: INFO/TestRunner(19796):     at com.jayway.android.robotium.solo.ViewFetcher.getCurrentViews(ViewFetcher.java:417)
03-14 16:10:13.081: INFO/TestRunner(19796):     at com.jayway.android.robotium.solo.Searcher$1.call(Searcher.java:99)
03-14 16:10:13.081: INFO/TestRunner(19796):     at com.jayway.android.robotium.solo.Searcher$1.call(Searcher.java:93)
03-14 16:10:13.081: INFO/TestRunner(19796):     at com.jayway.android.robotium.solo.Searcher.searchFor(Searcher.java:136)
03-14 16:10:13.081: INFO/TestRunner(19796):     at com.jayway.android.robotium.solo.Searcher.searchFor(Searcher.java:105)
03-14 16:10:13.081: INFO/TestRunner(19796):     ... 19 more
03-14 16:10:13.081: INFO/TestRunner(19796): ----- end exception -----

_Original issue: http://code.google.com/p/robotium/issues/detail?id=234_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 14, 2012 23:37:04_

Are you sure you are using Robotium 3.1? This is an issue that we had before the 2.5 release (which did not support honeycomb)

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 14, 2012 23:41:41_

Please use Robotium 3.1.

**Status:** Duplicate  
  **Mergedinto:** 127

**Comment by renas** [comment]
_From [GillesBa...@gmail.com](https://code.google.com/u/101329230007579602900/) on March 16, 2012 01:19:54_

When I right click on the project, select properties, Java Build Path, Libraries, I see robotium-solo-3.1.jar

Are there any other places I should check? Is there any way to have Robotium itself tell me its version? Something like solo.getVersion?

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 16, 2012 01:25:48_

No, there is no getVersion(). Please download 3.1 at the bottom of the following page: https://code.google.com/p/robotium/downloads/list

**Comment by renas** [comment]
_From [GillesBa...@gmail.com](https://code.google.com/u/101329230007579602900/) on March 19, 2012 01:48:56_

That's where I got it: When I right click on the project, select properties, Java Build Path, Libraries, I see robotium-solo-3.1.jar
