### ISSUE TITLE
Fails with SDK rev. 17

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#316]
_From [karabara...@gmail.com](https://code.google.com/u/107526814912555924817/) on March 23, 2012 01:45:05_

What steps will reproduce the problem? 1. Update android SDK Tools into rev. 17
2. Run tests with solo What is the expected output? What do you see instead? Test should success like with before update into rev.17. But instead we has:
03-23 08:43:25.540: I/TestRunner(2881): java.lang.NoClassDefFoundError: com.jayway.android.robotium.solo.Solo
03-23 08:43:25.540: I/TestRunner(2881): 	at ru.infteh.organizer.test.TaskEditActivityTest.tearDown(TaskEditActivityTest.java:75)
03-23 08:43:25.540: I/TestRunner(2881): 	at junit.framework.TestCase.runBare(TestCase.java:130)
03-23 08:43:25.540: I/TestRunner(2881): 	at junit.framework.TestResult$1.protect(TestResult.java:106)
03-23 08:43:25.540: I/TestRunner(2881): 	at junit.framework.TestResult.runProtected(TestResult.java:124)
03-23 08:43:25.540: I/TestRunner(2881): 	at junit.framework.TestResult.run(TestResult.java:109)
03-23 08:43:25.540: I/TestRunner(2881): 	at junit.framework.TestCase.run(TestCase.java:118)
03-23 08:43:25.540: I/TestRunner(2881): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
03-23 08:43:25.540: I/TestRunner(2881): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
03-23 08:43:25.540: I/TestRunner(2881): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:529)
03-23 08:43:25.540: I/TestRunner(2881): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1448) What version of the product are you using? On what operating system? ver 3.1, OS Windows 7, eclipse ide Please provide any additional information below.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=237_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 23, 2012 02:31:27_

Have you gotten it to work with earlier versions of the SDK?

**Comment by renas** [comment]
_From [karabara...@gmail.com](https://code.google.com/u/107526814912555924817/) on March 23, 2012 02:35:59_

Yes it worked before, but it's failed after update SDK tools

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 23, 2012 02:46:59_

Please create a new rev 17 avd, and then try again. It seems as if Robotium jar is not transfered (with the test project) to the emulator and therefore you get the NoClassDefFoundError.

**Comment by renas** [comment]
_From [karabara...@gmail.com](https://code.google.com/u/107526814912555924817/) on March 23, 2012 03:25:23_

I create new AVD by new AVD manager rev.17 and had exactly the same exception.

Note that while tests is running and before NoClassDefFoundError there is such errors in LogCat:
03-23 10:21:18.511: E/dalvikvm(985): Could not find class 'com.jayway.android.robotium.solo.Solo', referenced from method myapp.test.TaskEditActivityTest.testFields

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 23, 2012 03:27:17_

Thanks for reporting this. I will have to take a look at it to see what the issue might be.

**Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 26, 2012 04:18:38_

Please see: http://stackoverflow.com/questions/9828722/verifyerror-in-android-test-project-build-tools-v17

**Comment by renas** [comment]
_From [karabara...@gmail.com](https://code.google.com/u/107526814912555924817/) on March 26, 2012 04:37:40_

thx, helped this: http://android.foxykeep.com/dev/how-to-fix-the-classdefnotfounderror-with-adt-17

**Comment by renas** [comment]
_From [grnd...@gmail.com](https://code.google.com/u/102977532618544105925/) on March 28, 2012 15:37:30_

Works if you export all your referenced libraries, by going to Properties-> Java Build Path -> Order and Export ...then check all your imported jar files.  Do the same in your project and test project.

**Comment by renas** [comment]
_From [vegito....@gmail.com](https://code.google.com/u/105963738182722066896/) on April 04, 2012 12:34:35_

You are not suppose to export any libraries with r17 . It does project dependencies automatically. One thing you have to be aware of is to not import libraries if your main project (project that's being tested on) already includes that library.
Do a dexdump if you are not sure

**Comment by renas** [comment]
_From [anilredd...@gmail.com](https://code.google.com/u/117408497712825215598/) on April 09, 2012 06:07:45_

This is working fine. Please refer to Comment 7 above for the URL http://android.foxykeep.com/dev/how-to-fix-the-classdefnotfounderror-with-adt-17

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 12, 2012 21:06:15_

Issue 246 has been merged into this issue.

**Comment by renas** [comment]
_From [tatajaja...@gmail.com](https://code.google.com/u/118108850629816476285/) on April 17, 2012 06:01:46_

I have "java.lang.NoClassDefFoundError: com.jayway.android.robotium.solo.Solo" exception running the robotium tests with SDK 17
Could you suggest smth to do with it ?

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 17, 2012 06:03:43_

@tatajaja88888888, Please see the previous comments.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 15, 2012 04:05:30_

Issue 279 has been merged into this issue.

**Comment by renas** [comment]
_From [michele.sama](https://code.google.com/u/michele.sama/) on July 11, 2012 15:39:04_

It is a problem with ADT 17 and the way libraries are handled.
 
Simply put all the referred libraries in the "libs" PLURAL folder and be sure that they are added as android libraries and not as java libraries.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on August 07, 2012 01:54:46_

**Status:** Done

**Comment by renas** [comment]
_From [vishal.v...@gmail.com](https://code.google.com/u/115311948285348536140/) on August 24, 2012 02:05:49_

i think it is not a problem of version 17

you can find solution here. http://stackoverflow.com/questions/9875029/android-robotium-noclassdeffounderror

**Comment by renas** [comment]
_From [taha.sta...@gmail.com](https://code.google.com/u/116020912233385671054/) on August 28, 2012 07:21:59_

lol
