### ISSUE TITLE
can robotium test the project whose target is google apis????

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#320]
_From [Jing....@fmr.com](https://code.google.com/u/115001050032104391615/) on March 28, 2012 02:28:03_

What steps will reproduce the problem? 1.Create an project whose target is google apis
2.Create an test project for 1
3.run test project What is the expected output? What do you see instead? i can not see my app runs,the following error occurs.

[java.lang.NoClassDefFoundError: com.jayway.android.robotium.solo.Solo
at com.fidelity.android.test.FirstTest.setUp(FirstTest.java:46)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:529)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1448)
]

FirstTest.java:46 is 
solo = new Solo(getInstrumentation(), getActivity());. What version of the product are you using? On what operating system? robotium3.1 android 2.3 whose target is google apis Please provide any additional information below. i can run the test by android2.3 whose target is android2.3.3.

So can robotium test the project whose target is google apis????????

_Original issue: http://code.google.com/p/robotium/issues/detail?id=241_

**Comment by renas** [comment]
_From [Jing....@fmr.com](https://code.google.com/u/115001050032104391615/) on March 28, 2012 02:30:57_

What version of the product are you using? On what operating system?
robotium3.1 
android 2.3 whose target is google apis
sdk17

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 28, 2012 14:58:57_

**Status:** Duplicate  
  **Owner:** renasr...@gmail.com  
  **Mergedinto:** 237

**Comment by renas** [comment]
_From [Jing....@fmr.com](https://code.google.com/u/115001050032104391615/) on March 28, 2012 17:41:42_

works fine now,many thanks!

**Comment by renas** [comment]
_From [netwal...@gmail.com](https://code.google.com/u/101373261491468027716/) on April 09, 2012 06:34:04_

How did you fix it? I am facing same issue.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 09, 2012 06:36:31_

Please see:

issue: 237

**Comment by renas** [comment]
_From [tatajaja...@gmail.com](https://code.google.com/u/118108850629816476285/) on April 17, 2012 05:47:26_

Could you give the full instructions of fixing this problem ?

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 17, 2012 05:48:30_

Please see the links on this page: https://code.google.com/p/robotium/issues/detail?id=237&colspec=ID%20Type%20Stars%20Status%20Priority%20Milestone%20Owner%20Summary
