### ISSUE TITLE
Strange behaviours on big projects

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#328]
_From [alex.gi...@gmail.com](https://code.google.com/u/106277910938818275510/) on April 18, 2012 03:18:02_

What steps will reproduce the problem? 1.Create test steps with one intent flagged ACTIVITY_CLEAR_TOP or other flags that Robotium conception does not take into account.
2.Call solo.finishOpenedActivities() What is the expected output? What do you see instead? My test should terminate. Instead, I can get functional exceptions, outOfMemoryExceptions due to activities that are unfrozen while they should no more exist, hanging InstrumentationTestRunner, ... What version of the product are you using? On what operating system? Will crash on any SDK and every version of robotium Please provide any additional information below. This is a conception flaw. I think the problem was raised on issue #219 , and rejected. But the problem does exist.
The whole conception of keeping a hard reference upon the "stack" of activities is wrong. Android activity manager is much more complex than a simple stack, and stacking activities into an inner object leaks the robotium tests, and bypasses the application expected functional workflow. When a hard reference is kept upon an activity, you prevent Android from managing activities and garbage collecting objects the way it wants to, then the tested application behaves strangely : OutOfMemory (because you keep reference upon an activity that has reference upon bitmaps that can not be garbagecollected), functional exceptions because finishOpenedActivities() calls finish() on activities that should no more exist (for example when an intent is started with flag ACTIVITY_CLEAR_TOP, or NO_HISTORY), hence implemented activity does not handle this unnatural behaviour.
A temporary patch should be to keep a stack of WeakReference<Activity> within the activity stack, to prevent robotium from leaking the whole application then randomly crashing the instrumentationtestrunner. But I don't get the point of keeping the stack at all... Why should this be necessary in a blackbox test ? 

Robotium is a great framework, but this point of conception really is painful. This problem keeps crashing our Jenkins continuous integration, holding all executors whenever it happens, and forcing us to allocate 256Mo heaps emulators to prevent OutOfMemory ! 
If I can help in any way, please let me know.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=249_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 18, 2012 04:27:15_

What happens if you use finishInactiveActivities() through your test cases. Do you still get crashes and OutOfMemoryExceptions?

**Comment by renas** [comment]
_From [alex.gi...@gmail.com](https://code.google.com/u/106277910938818275510/) on April 18, 2012 06:30:52_

First, thank you for your responsiveness.

finishInactiveActivities() partially corrects the problem if it is followed by getCurrentActivity().finish(). I did not test it through all of my test cases (120 minutes of execution, I lack time). But this is only bypassing the problem. When you call finish on activities that are not active, you may trigger other problems, like infinite loops inside the inner android workflow manager (I just had an example a few minutes ago). This solution seems to solve my first problem, but may cause other issues for other applications.

The OutOfMemory problem is not solved anyway, because of the inner stack, which keeps hard references upon activities. When I study heap size via ddms, it appears that layouts, views, business objects and big bitmaps that should be freed are never released inside a test.
The point is that in any case, it is a BAD pattern to keep a hard link on a sdk-managed object, particularly activities ( http://developer.android.com/resources/articles/avoiding-memory-leaks.html ). Also, calling finish() on an activity is more than a technical operation, since it may have an applicative meaning, trigger other operations, like resuming an other activity, calling onActivityResult(), etc...

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 19, 2012 02:00:43_

The issue here is that we can not break backward compatibility (getOpenedActivities()). Also this is not only a blackbox test framework, people may be interested in getting a hold of the activities that have been opened. Another reason for the Activity references to be kept is due to being able to finish them at the end. That is needed as having a old Activity still open and in focus will lead to complications with the next test case. Many times activities are not cleaned properly and therfore manually calling finish is a must. 

Using weak references could work. I will send you a version where Robotium uses weak references to the Activities instead. Please let me know if it works better for you.

**Comment by renas** [comment]
_From [alex.gi...@gmail.com](https://code.google.com/u/106277910938818275510/) on April 19, 2012 06:46:22_

Great !
No more memory leak ^^
I created a standard emulator with 25Mo heap, and the used memory is now between 55% and 62% maximum. Big objects are garbage collected as soon as huge activities are released. (before, I had to use a 256Mo heap, and it was 85% full in 2 tests, then the garbage collector had to struggle for survival)
Looks like the functional issue is solved as well : because of weak references, the activities that should no more exist are just forgotten ; then the finish() that used to trigger strange behaviours is no more called.

I just encountered a (major) side effect issue. It seems that sometimes, the "current activity" is not recognized correctly (1 transition on 10, solo is late and pretends that the current activity is the previous one). I could not step into the source code to find out why, but I guess the jar you sent me was a first draft, and you need time to make it stable.

Anyway thank you for your responsiveness, I continue reading the posts, and I hope I can help finalizing this major improvement. Don't hesitate if you need me to test the next snapshots.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 19, 2012 07:05:34_

Thanks for the great news. I have identified the getCurrentActivity() issue as well and I know why it happens. It will be fixed and commited soon. I will send you a new jar when all the work has been performed. Thanks for helping out with the testing.

**Status:** Accepted  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 26, 2012 00:06:07_

I have sent you a new jar where all issues should be fixed. Please let me know if it works well for you.

**Comment by renas** [comment]
_From [alex.gi...@gmail.com](https://code.google.com/u/106277910938818275510/) on April 30, 2012 05:34:49_

Sorry, I was on holidays the past week.
I'm trying the new jar now, I'll tell you in a few minutes if it works well.

**Comment by renas** [comment]
_From [alex.gi...@gmail.com](https://code.google.com/u/106277910938818275510/) on April 30, 2012 06:16:56_

Congratulations.
Everything is working perfectly for me. No leak, no getCurrentActivity() issue.
My full testSuite's memory profile is light and clean.

Thank you very much !

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 30, 2012 06:33:28_

Thanks for reporting the issue and helping out with the testing. I hope it's ok if I send you one last jar before release.

**Comment by renas** [comment]
_From [alex.gi...@gmail.com](https://code.google.com/u/106277910938818275510/) on May 02, 2012 09:44:58_

Of course it's OK !
Thank you for your work again.

**Comment by renas** [comment]
_From [kapilgod...@gmail.com](https://code.google.com/u/116202997325348330919/) on May 29, 2012 03:51:20_

Hi Renas

Would you please share the jar of this with me too. Also any ETA on the new version will be highly helpful. I have been facing this issue and following this thread for a long time now and I am still stuck at OutOfMemory issues. Please help me out here.

**Comment by renas** [comment]
_From [markper...@gmail.com](https://code.google.com/u/100945538260448177391/) on June 08, 2012 08:10:05_

Hi Renas,

Could you please send me the jar file as well?  Like others I was wondering when you would be releasing this version.

Thanks,
Mark

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 08, 2012 08:12:41_

Next version will be released early next week.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 11, 2012 09:11:08_

This has been fixed in Robotium 3.3.

**Status:** Verified

**Comment by renas** [comment]
_From [dnlkn...@gmail.com](https://code.google.com/u/115226172254596283208/) on June 12, 2012 04:38:14_

Hi Renas,

the Out of Memory Exception is still happening on my project :(. I am using the new Robotium Version 3.3. My tearDown() Method look like this:

public void tearDown() throws Exception {
		
		try {
			getActivity().finish();
			solo.finishOpenedActivities();
									
		} catch (Throwable e) {
			e.printStackTrace();
		}
}

I am calling the tearDown method after each testmethod. I have around 100 automated tests. On every test a user has to login to my app and is performing some action.

Do you have an idea what else could go wrong?

Greets,

Daniel

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 12, 2012 04:41:17_

What if you do the following?

public void tearDown(){
solo.finishOpenedActivities();
}

**Comment by renas** [comment]
_From [dnlkn...@gmail.com](https://code.google.com/u/115226172254596283208/) on June 12, 2012 04:52:07_

If I just do 
public void tearDown(){
   solo.finishOpenedActivities();
}
Just one testmethod is executed. At the end of the test, the testsuite is just stopping (not with Out Of Mem Exc.) but it looks like the old activity is still open. When I use the tearDown Method I posted before, the tests are running fine as long as the OutOfMem Exc. is happening. 

Greets,

Daniel

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 12, 2012 04:54:26_

What if you change your setUp() to look like this?

setUp(){
solo = new Solo(getInstrumentation());
getActivity();
}

**Comment by renas** [comment]
_From [dnlkn...@gmail.com](https://code.google.com/u/115226172254596283208/) on June 12, 2012 05:53:48_

The same. The test execution is stopping after the first test. If I use 

getActivity().finish();
solo.finishOpenedActivities();

in teardown it is running (with the OOM Exc.)

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 12, 2012 07:02:04_

I have emailed you a new jar. Please let me know if you have the same issue.

**Comment by renas** [comment]
_From [dnlkn...@gmail.com](https://code.google.com/u/115226172254596283208/) on June 12, 2012 07:31:40_

Sorry, still getting the out of memory exceptuin...

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 12, 2012 07:35:19_

I actually do not know what your issue might be. I dont think its Robotium that is causing it. I cant see what in Robotium might be causing this. What does the log say?

**Comment by renas** [comment]
_From [dnlkn...@gmail.com](https://code.google.com/u/115226172254596283208/) on June 12, 2012 07:37:58_

That is the only error I receive:


06-12 16:20:42.415: E/AndroidRuntime(25800): Caused by: java.lang.OutOfMemoryError: bitmap size exceeds VM budget

I am testing on a real device (Samsung Galaxy S II). The exception occur after ~20 test executions.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 12, 2012 07:42:00_

Do you get the same issue when running on the emulator? Or other phone?

**Comment by renas** [comment]
_From [dnlkn...@gmail.com](https://code.google.com/u/115226172254596283208/) on June 12, 2012 07:45:42_

yes. I tested it with different simulator settings vm size ... and also with different devices (Samsung S3, Galaxy Nexus, Motorola Droid and many more) always the same. 

I am now trying this: 

protected void tearDown() throws Exception {
   solo.finishInactiveActivities();
   solo.finishOpenedActivities();
}

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 12, 2012 07:49:22_

finishOpenedActivities() does the same and more as finishInactiveActivities(). If its always at the same point that it happens you can add finishInactiveActivities() at that point in order to kill of activities. However that should not be needed now when we are using weak references...

**Comment by renas** [comment]
_From [dnlkn...@gmail.com](https://code.google.com/u/115226172254596283208/) on June 12, 2012 07:57:52_

When I use finishInactiveActivities() I get the following NPE Exception

06-12 16:52:07.405: W/System.err(29728): java.lang.NullPointerException
06-12 16:52:07.405: W/System.err(29728): 	at com.jayway.android.robotium.solo.ActivityUtils.finishActivity(ActivityUtils.java:348)
06-12 16:52:07.405: W/System.err(29728): 	at com.jayway.android.robotium.solo.ActivityUtils.finishInactiveActivities(ActivityUtils.java:295)
06-12 16:52:07.405: W/System.err(29728): 	at com.jayway.android.robotium.solo.Solo.finishInactiveActivities(Solo.java:1960)

**Comment by renas** [comment]
_From [dnlkn...@gmail.com](https://code.google.com/u/115226172254596283208/) on June 12, 2012 07:58:18_

but the test app is not crashing

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 12, 2012 08:01:01_

Yes. The exception is catched. It can happen and is according to design.

**Comment by renas** [comment]
_From [kapilgod...@gmail.com](https://code.google.com/u/116202997325348330919/) on June 13, 2012 03:54:21_

Hi

I am still getting this issue in my build too. Is there a specific way to implement the setup method because I tried the one mentioned above and also tried using both finishInactiveActivities() and  finishOpenedActivities() in teardown method.

Regards
Kapil

**Comment by renas** [comment]
_From [mobilek...@googlemail.com](https://code.google.com/u/106691555097769530572/) on June 15, 2012 03:42:43_

What's the status of this issue? 

I'm writing a suite case capturing screenshots in port/land for six locales of three activities. What are the best practices for achieving this?

At first I wrote a number of ActivityInstrumentationTestCase2 for each locale and orientation and made sure that in tearDown() I do finishInactiveActivities(). The app crashes with "java.lang.OutOfMemoryError: bitmap size exceeds VM budget" and I can see the weak references to the activities in the hprof just before the app runs out of memory.

I then tried to put all test cases in one ActivityInstrumentationTestCase2 with the hope that this will reduce the weak references by orientations * locales. However, that produced the same result.

Any suggestions on how to fix this? Thanks.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 15, 2012 03:47:49_

Please use finishOpenedActivities() in your tearDown() and not finishInactiveActivities(). 

Can anyone send me a project and test project where this behaviour can be reproduced? I am not able to reproduce it my self even with test suites of 150 test cases.

**Status:** Accepted

**Comment by renas** [comment]
_From [mobilek...@googlemail.com](https://code.google.com/u/106691555097769530572/) on June 15, 2012 04:03:57_

I wish I could send you my projects however I can't do that because of the IP involved. I'll try your suggestion.

**Comment by renas** [comment]
_From [mobilek...@googlemail.com](https://code.google.com/u/106691555097769530572/) on June 15, 2012 04:18:55_

@Override
protected void tearDown() throws Exception {
   super.tearDown();
   solo.finishOpenedActivities();
}

Once this code is invoked the next test case hangs indefinitely. 

A way to reproduce it is to have a couple of activities and make sure they hold on to a large bitmap, byte[], etc.. and write test cases around logic revisiting those activities sequentially. 

Can you send me the project you have with the 150 test cases? Thanks.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 15, 2012 04:23:26_

Unfortunately those are 2 test suites that I am not allowed to share. Would it be possible for you to create a sample app where the issue you are experiencing (where the test case hangs) and send it to me?

**Comment by renas** [comment]
_From [JoaRe...@gmail.com](https://code.google.com/u/112856617907425013321/) on June 29, 2012 00:42:39_

I also have problems with those OutOfMemory crashes. 

I created a sample proect/testproject. The project has two Activities that both display very big images. The test project then tries to jump between those Activities. When going back to Activity1 the test crashes. Try it yourself! http://www.file-upload.net/download-4488607/bigimages_test_outofmemory_example.zip.html

**Comment by renas** [comment]
_From [JoaRe...@gmail.com](https://code.google.com/u/112856617907425013321/) on June 29, 2012 00:51:46_

The project also crashes if not under test. Have to figure out another sample project. Sorry!

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 29, 2012 06:47:03_

Thanks for helping out with trying to reproduce this!

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on August 07, 2012 01:54:34_

This issue has finally been fixed in 3.4. Thanks to Daniel Knott for helping out with the testing.

**Status:** Verified

**Comment by renas** [comment]
_From [kukreti....@gmail.com](https://code.google.com/u/103550759417591223556/) on August 14, 2012 04:11:42_

Hi Renas, can you please send me the build which was shared with alex. In all my test cases I have to login and then do smething and then logout. But this Arraylist keeps on holding references to all the activities which are holding references to the bitmap arrays and other java objects. I am also attaching the screenshot with the arraylist. Can't send you an expanded one cause of IP issues. let me know if any other detail is required.
This is how my tearDown looks like

protected void tearDown() throws Exception {
		
		//Log out...
		
		solo.sendKey(Solo.MENU);
		solo.clickOnText("More");
		solo.clickOnText("Logout");
		if (solo.searchButton("Logout")) {
			solo.clickOnButton("Logout");
		}
		
		solo.waitForActivity(LoginActivity.class.getName(), 1000);
		
		assertTrue(solo.searchText("Your id"));
		
		int i = 0;
		
		while(solo.getAllOpenedActivities()!=null && solo.getAllOpenedActivities().size()>0){
			
			solo.finishOpenedActivities();
			solo.goBack();									
			
			if(i++>5){
				break;
			}
		}
		
		solo.finishOpenedActivities();
		
		solo = null;
		System.gc();
}

**Attachment:** [arraylist_with_references_to_activities.bmp](http://code.google.com/p/robotium/issues/detail?id=249#hc42)

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on August 14, 2012 04:22:56_

Please update to 3.4.1 and change your teardown to:

protected void tearDown() throws Exception {
		
		//Log out...
		
		solo.sendKey(Solo.MENU);
		solo.clickOnText("More");
		solo.clickOnText("Logout");
		if (solo.searchButton("Logout")) {
			solo.clickOnButton("Logout");
		}
		
		solo.waitForActivity(LoginActivity.class.getName(), 1000);
		assertTrue(solo.searchText("Your id"));
		
		solo.finishOpenedActivities();
}

**Comment by renas** [comment]
_From [kukreti....@gmail.com](https://code.google.com/u/103550759417591223556/) on August 14, 2012 05:20:02_

Thanks for youe quick response. I tried using the above mentioned tear down method with 3.4.1 but the solo.finishOpenedActivities doesn't finish the login activity and the test suite hangs there itself. The method I was using makse it move but after running some 45 test cases it runs out of memory. Am I missing anything here?

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on August 14, 2012 05:22:48_

What you are describing is another issue. I have emailed you about it.

**Comment by renas** [comment]
_From [qmxiu...@gmail.com](https://code.google.com/u/114885725848235210463/) on September 02, 2012 22:27:35_

I also have problems with the test suite hangs there itself.How to  resolve the problems?

**Comment by renas** [comment]
_From [mrlhwlib...@gmail.com](https://code.google.com/u/107770464206980364909/) on December 04, 2012 13:58:58_

I also have this issue on Emulator. It didn't happen on real device.

Project here: https://code.google.com/p/anymemo/source/browse/#git%2Ftest%2Fsrc%2Forg%2Fliberty%2Fandroid%2Ffantastischmemo%2Ftest%2Fui

**Comment by renas** [comment]
_From [nayanshr...@gmail.com](https://code.google.com/u/101169501305555766839/) on May 11, 2015 23:52:52_

I have just joined as a fresher and the existing automation run throws OutOfMemoryException when a bunch of test cases are executed together. Because of this issue we have got to run the test in multiple test runners. Plz help !
