### ISSUE TITLE
Can not click all the buttons get by getCurrentButtons()

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#367]
_From [davidyou...@gmail.com](https://code.google.com/u/109288464246994579719/) on June 25, 2012 19:28:17_

What steps will reproduce the problem? 1.ArrayList<Button> buttons = solo.getCurrentButtons();
2.int btnsize = buttons.size();
3.for(int i = 0; i \< buttons.size(); i++){
     solo.clickOnButton(i);
  } Please provide any additional information below. junit.framework.AssertionFailedError: Button with index 3 is not available!
at com.jayway.android.robotium.solo.Waiter.waitForAndGetView(Waiter.java:362)
at com.jayway.android.robotium.solo.Clicker.clickOn(Clicker.java:323)
at com.jayway.android.robotium.solo.Solo.clickOnButton(Solo.java:929)
at ....

_Original issue: http://code.google.com/p/robotium/issues/detail?id=288_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 26, 2012 04:17:29_

Is any of the buttons blocked? E.g. soft keyboard blocking one of them or similar?

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on July 19, 2012 22:56:37_

Will open up again when new information is given.

**Status:** Invalid

**Comment by renas** [comment]
_From [dqz...@gmail.com](https://code.google.com/u/104482673221631818898/) on September 11, 2012 20:46:13_

i have encountered the same question
have you found the reason?

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on September 11, 2012 21:36:51_

Would it be possible for you to send me a sample app that exhibits this issue?
