### ISSUE TITLE
Not able to click on a button in dialog fragment

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#369]
_From [kataria....@gmail.com](https://code.google.com/u/118342713991201707392/) on July 02, 2012 07:11:32_

What steps will reproduce the problem? 1.Clicking on a view shows a dialog fragment which has a title, an edittext and 2 buttons 'ok' and 'cancel'.
2.Click on 'ok' button using -
 a)clickOnButton("Ok")
 b)clickOnButton(index), I find index by looping through current button list.
 c) clickOnText("Ok") What is the expected output? What do you see instead? Expected output - Dialog should get dismissed.
What I get - junit.framework.AssertionFailedError: Click can not be completed!
at com.jayway.android.robotium.solo.Clicker.clickOnScreen(Clicker.java:85)
at com.jayway.android.robotium.solo.Clicker.clickOnScreen(Clicker.java:160)
at com.jayway.android.robotium.solo.Clicker.clickOnText(Clicker.java:279)
at com.jayway.android.robotium.solo.Solo.clickOnText(Solo.java:823)
at com.philips.lighting.lightapp.lightrecipes.testauto.TestAddScene.testAddNewScene(TestAddScene.java:80)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:186)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:525)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1547) What version of the product are you using? On what operating system? Robotium 3.3 with android SDK 20 Please provide any additional information below.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=290_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on July 02, 2012 09:08:01_

The issue you are experiencing is because of the soft keyboard blocking the button. Use solo.goBack() first and then clickOnButton("Ok");

**Status:** Invalid

**Comment by renas** [comment]
_From [kataria....@gmail.com](https://code.google.com/u/118342713991201707392/) on July 03, 2012 00:32:17_

That works...Thanks Renas...

**Comment by renas** [comment]
_From [davidovi...@gmail.com](https://code.google.com/u/108405384541124084416/) on August 29, 2012 04:09:31_

Thanks for answer... This help me much
