### ISSUE TITLE
Robotium fails in the second duplicated test

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#430]
_From [UdiO...@gmail.com](https://code.google.com/u/113614087409155118714/) on November 15, 2012 01:59:45_

I've created simple test in my android program using robotium 3.5.1 with the following code:

protected void setUp() throws Exception {
    solo = new Solo(getInstrumentation(), getActivity());
}

protected void tearDown() throws Exception {
    solo.finishOpenedActivities();
}

public void testAddTabs() throws Exception {

    addTab("TAB1");
    addPreset("TAB1");
    addTab("TAB2");
    addPreset("TAB2");

}

public void addTab(String tabName) throws Exception {

    solo.assertCurrentActivity("Checking current Activity",
            MainActivity.class);
    Log.d("MyTag", solo.getCurrentActivity().getLocalClassName() );
    solo.clickOnView(solo.getView(com.sm.scam.R.id.menu_new_tab));
    solo.enterText(0, tabName);
    solo.clickOnText("OK");

}

public void addPreset(String name) throws Exception {
    Log.d("MyTag", solo.getCurrentActivity().getLocalClassName() );
    solo.goBackToActivity("MainActivity");
    Log.d("MyTag", solo.getCurrentActivity().getLocalClassName() );
    solo.clickOnText(name);
    solo.clickOnText("New Preset");
    Log.d("MyTag", solo.getCurrentActivity().getLocalClassName() );
    solo.assertCurrentActivity("Checking current Activity",
            PresetActivity.class);

    String presetName = "Moti" + 1;
    solo.enterText(0, presetName);
    solo.pressSpinnerItem(0, 1);
    solo.clickOnText("Darkened");
    solo.clickOnText("GPS Tag");
    solo.clickOnView(solo.getView(com.sm.scam.R.id.menu_save_preset));
}
it simply add new tab, and in the tab pressing on button, changes edittext,spinner and 2 switch buttons and save. everything is OK in the first tab but in the second tab the following code:

solo.clickOnText("New Preset");
just don't do nothing! when clicking this button nothing happens and it should forward to PresetActivity as it forwarding correctly in the first tab.

the error code:

junit.framework.ComparisonFailure: Checking current Activity expected:<...Preset...>            but was:<...Main...>
at com.jayway.android.robotium.solo.Asserter.assertCurrentActivity(Asserter.java:57)
at com.jayway.android.robotium.solo.Solo.assertCurrentActivity(Solo.java:570)
at com.sm.scam.test.ScamTest.addPreset(ScamTest.java:55)
at com.sm.scam.test.ScamTest.testAddTabs(ScamTest.java:32)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at                                                                                                                                                                        android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java   :186)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:537)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1574)
I've also tried to force it by calling to:

solo.goBackToActivity("MainActivity");
but still nothing. would appreciate if someone help me. thanks

_Original issue: http://code.google.com/p/robotium/issues/detail?id=351_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 15, 2012 07:49:45_

Would it be possible for you to send me your application?

**Comment by renas** [comment]
_From [UdiO...@gmail.com](https://code.google.com/u/113614087409155118714/) on November 17, 2012 22:46:00_

As much as  I want but according to our customer policy I can't share this code with anyone....

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 18, 2012 22:49:10_

Would it be possible for you to create or send another application that exhibits this issue? Otherwise I am afraid that nothing can be done to fix it.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 19, 2012 05:09:48_

**Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [u...@sergata.mobi](https://code.google.com/u/114365764304904279581/) on December 03, 2012 02:27:49_

Hello,
The issue has been solved. Needed to use goBack method.
all ok now.
thanks. udi

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 03, 2012 02:28:35_

**Status:** Invalid
