### ISSUE TITLE
Robotium is broken with Android 4.2

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#431]
_From [Michal.S...@bitbar.com](https://code.google.com/u/115462272701630068832/) on November 15, 2012 06:41:50_

What steps will reproduce the problem? 1. Write simple test, for instance:
solo.sleep(5000);
assertTrue(solo.getViews() != null);
solo.sleep(5000);
2. Run on device/emulator with Android 4.2 What is the expected output? What do you see instead? solo.getViews() return null

I think, there are similar problems with other getters.

java.lang.NullPointerException
at com.jayway.android.robotium.solo.ViewFetcher.getNonDecorViews(ViewFetcher.java:163)
at com.jayway.android.robotium.solo.ViewFetcher.getAllViews(ViewFetcher.java:85)
at com.jayway.android.robotium.solo.Searcher.searchFor(Searcher.java:158)
at com.jayway.android.robotium.solo.Waiter.waitForView(Waiter.java:214)
... Please provide any additional information below.

**Attachment:** [Zaznaczenie_018.png](http://code.google.com/p/robotium/issues/detail?id=352)

_Original issue: http://code.google.com/p/robotium/issues/detail?id=352_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 15, 2012 07:50:54_

On Monday 3.6 will be released with full support for Android 4.2 (API Level 17)

**Status:** Accepted  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 18, 2012 22:06:13_

This has been fixed in Robotium 3.6.

**Status:** Verified
