### ISSUE TITLE
call enterText cause NullPointerException

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#435]
_From [mrpc.cam...@gmail.com](https://code.google.com/u/107682821486331697412/) on November 19, 2012 20:38:53_

What steps will reproduce the problem? I setup a test project to test another Android project. Everything is working fine. I can call solo.clickOnView and the test will run fine. Problem happens when i try to update a view, example an EditText by calling solo.enterText. The below error message will come up. What version of the product are you using? On what operating system? 3.6 Please provide any additional information below. Error message

=========
java.lang.NullPointerException
at android.app.Instrumentation.runOnMainSync(Instrumentation.java:338)
at com.jayway.android.robotium.solo.TextEnterer.setEditText(TextEnterer.java:52)
at com.jayway.android.robotium.solo.Solo.enterText(Solo.java:1404)
at com.darakok.test.TestMain.testDisplayBlackBox(TestMain.java:30)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:204)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:194)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:186)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:520)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1447)

_Original issue: http://code.google.com/p/robotium/issues/detail?id=356_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 19, 2012 22:58:42_

Would it be possible for you to send me an application that exhibits this issue?

**Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [mrpc.cam...@gmail.com](https://code.google.com/u/107682821486331697412/) on November 20, 2012 06:45:36_

I've put the test project separate from the main project. In the test project, as soon as it reaches the line "enterText", a NullPointerException is raised.

**Attachment:** [Main_TestProject.zip](http://code.google.com/p/robotium/issues/detail?id=356#hc2)

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 20, 2012 06:59:27_

There is a facebook dependency. Can you please send that as well. Thanks.

**Comment by renas** [comment]
_From [mrpc.cam...@gmail.com](https://code.google.com/u/107682821486331697412/) on November 20, 2012 07:04:30_

here it is.

**Attachment:** [facebook.zip](http://code.google.com/p/robotium/issues/detail?id=356#hc4)

**Comment by renas** [comment]
_From [mrpc.cam...@gmail.com](https://code.google.com/u/107682821486331697412/) on November 20, 2012 07:05:29_

I run this project on a Mac with Eclipse 3.8 and Android SDK Tool v21.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 20, 2012 07:19:26_

Your solo setup should look like the following:

 solo = new Solo(getInstrumentation(), getActivity());

As it is now you give it a instrumentation null object.

**Status:** Invalid

**Comment by renas** [comment]
_From [mrpc.cam...@gmail.com](https://code.google.com/u/107682821486331697412/) on November 20, 2012 07:25:20_

My mistake. Thanks.
