### ISSUE TITLE
How to add french language with special character in robotium using xml or properties file

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#462]
_From [rasmikan...@gmail.com](https://code.google.com/u/115535375305705561965/) on January 22, 2013 23:16:08_

hi,

I am using robotium for the automation android device.
I am trying to click on french language using solo.clickOnText("Français").

When language name is hard coded it is working, but when i am accessing from xml or properties file it is showing the error i.e. shown in below
The code is like: solo.clickOnText(ExcelInsertion.getContent("lang"));

error :
junit.framework.AssertionFailedError: No TextView with text Fran?ais is found!
at com.jayway.android.robotium.solo.Getter.getView(Getter.java:71)
at com.jayway.android.robotium.solo.Solo.getText(Solo.java:1434)
at com.testtelus.TestTelus.testCheckA01_UI_03(TestTelus.java:90)

It is because of special chracter "ç".
But while it is printing with System.out.println(ExcelInsertion.getContent("lang")). It is showing perfect.

Is their any way to solve this?

_Original issue: http://code.google.com/p/robotium/issues/detail?id=383_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on January 24, 2013 00:11:20_

This issue has to be here:

ExcelInsertion.getContent("lang")

As solo.clickOnText("Français") works. This is not a Robotium issue.

**Status:** Invalid  
  **Owner:** renasr...@gmail.com
