### ISSUE TITLE
Improvement for the method waitForActivity()

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#466]
_From [G.Rjab...@gmail.com](https://code.google.com/u/114613923384070765920/) on February 07, 2013 04:31:31_

Sometimes tests randomly crashes when used method solo.getView() throwing NullPointerException. Will be great to have a method which will wait for the specified timeout until all elements not loaded on the current activity, can return boolean if checking ended earlier than specified timeout.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=387_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on February 07, 2013 12:12:45_

Can you please paste the error message and stack trace?

**Comment by renas** [comment]
_From [G.Rjab...@gmail.com](https://code.google.com/u/114613923384070765920/) on February 09, 2013 06:12:46_

I had randomly the same error overtime: JavaLangNullPointerExcption

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on February 09, 2013 06:14:23_

Please paste the log.

**Comment by renas** [comment]
_From [G.Rjab...@gmail.com](https://code.google.com/u/114613923384070765920/) on February 12, 2013 07:29:34_

02-12 18:27:00.187: I/TestRunner(5873): ----- begin exception -----
02-12 18:27:00.195: I/TestRunner(5873): junit.framework.AssertionFailedError: View is null and can therefore not be clicked!
02-12 18:27:00.195: I/TestRunner(5873): 	at junit.framework.Assert.fail(Assert.java:47)
02-12 18:27:00.195: I/TestRunner(5873): 	at junit.framework.Assert.assertTrue(Assert.java:20)
02-12 18:27:00.195: I/TestRunner(5873): 	at com.jayway.android.robotium.solo.Clicker.clickOnScreen(Clicker.java:153)
02-12 18:27:00.195: I/TestRunner(5873): 	at com.jayway.android.robotium.solo.Clicker.clickOnScreen(Clicker.java:139)
02-12 18:27:00.195: I/TestRunner(5873): 	at com.jayway.android.robotium.solo.Solo.clickOnView(Solo.java:785)
02-12 18:27:00.195: I/TestRunner(5873): 	at com.mypackage.tv.test2.MyPackage.testD(MyPackage.java:531)
02-12 18:27:00.195: I/TestRunner(5873): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-12 18:27:00.195: I/TestRunner(5873): 	at java.lang.reflect.Method.invoke(Method.java:511)
02-12 18:27:00.195: I/TestRunner(5873): 	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
02-12 18:27:00.195: I/TestRunner(5873): 	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
02-12 18:27:00.195: I/TestRunner(5873): 	at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:186)
02-12 18:27:00.195: I/TestRunner(5873): 	at junit.framework.TestCase.runBare(TestCase.java:127)
02-12 18:27:00.195: I/TestRunner(5873): 	at junit.framework.TestResult$1.protect(TestResult.java:106)
02-12 18:27:00.195: I/TestRunner(5873): 	at junit.framework.TestResult.runProtected(TestResult.java:124)
02-12 18:27:00.195: I/TestRunner(5873): 	at junit.framework.TestResult.run(TestResult.java:109)
02-12 18:27:00.195: I/TestRunner(5873): 	at junit.framework.TestCase.run(TestCase.java:118)
02-12 18:27:00.195: I/TestRunner(5873): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
02-12 18:27:00.195: I/TestRunner(5873): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
02-12 18:27:00.195: I/TestRunner(5873): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:537)
02-12 18:27:00.195: I/TestRunner(5873): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1575)
02-12 18:27:00.195: I/TestRunner(5873): ----- end exception -----

**Comment by renas** [comment]
_From [G.Rjab...@gmail.com](https://code.google.com/u/114613923384070765920/) on February 12, 2013 07:31:04_

But I saw by eyes that this view was on the screen entirely

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on February 13, 2013 21:40:40_

This is not a robotium issue. If view is null there is nothing Robotium can do with it.

**Status:** Invalid  
  **Owner:** renasr...@gmail.com
