### ISSUE TITLE
NullPointerException while testing APK

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#482]
_From [valentin...@gmail.com](https://code.google.com/u/106145933394766715411/) on March 06, 2013 08:26:24_

What steps will reproduce the problem? 1. install re-signed Tumblr apk from Play Store https://play.google.com/store/apps/details?id=com.tumblr 2. 	public void testLogin() {
		if (solo.waitForText("Log in")) {
			solo.clickOnButton(1);
		}
	}
3. Run test and then manually launch app to initiate the testing. What is the expected output? What do you see instead? Expecting a button to be clicked after first screen shows a "Log in" button. What version of the product are you using? On what operating system? Robotium 4.0, Android 2.3.4 (API 10), OS X Mountain Lion 10.8.2 Please provide any additional information below. Complete RobotTumblr.java test code and AndroidManifest.xml attached.

Test uses solo = new Solo(getInstrumentation()); so it will NOT launch the app automatically.
(This is due to some other issue where it does not recognize the activity for APKs if JUnit starts the app via solo = new Solo(getInstrumentation(), getActivity());)

**Attachment:** [RobotTumblr.java AndroidManifest.xml](http://code.google.com/p/robotium/issues/detail?id=403)

_Original issue: http://code.google.com/p/robotium/issues/detail?id=403_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 06, 2013 08:30:03_

Thanks for reporting this. It will be fixed in the next release.

**Status:** Accepted  
  **Owner:** renasr...@gmail.com  
  **Labels:** -Type-Enhancement

**Comment by renas** [comment]
_From [valentin...@gmail.com](https://code.google.com/u/106145933394766715411/) on March 06, 2013 08:36:09_

Thank you, Renas. Could you comment on when the next release may be available?
I'm happy to help test with the latest git source if the fix is available there sooner.

For posterity, I forgot to include the answer to "What do you see instead?"
I see a stack trace:

java.lang.RuntimeException: java.lang.NullPointerException
at com.jayway.android.robotium.solo.Searcher.searchFor(Searcher.java:127)
at com.jayway.android.robotium.solo.Waiter.waitForText(Waiter.java:383)
at com.jayway.android.robotium.solo.Waiter.waitForText(Waiter.java:353)
at com.jayway.android.robotium.solo.Waiter.waitForText(Waiter.java:312)
at com.jayway.android.robotium.solo.Solo.waitForText(Solo.java:211)
at com.jayway.test.tumblr.RobotTumblr.testLogin(RobotTumblr.java:38)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:204)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:194)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:186)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:529)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1448)
Caused by: java.lang.NullPointerException
at com.jayway.android.robotium.solo.ViewFetcher.getNonDecorViews(ViewFetcher.java:159)
at com.jayway.android.robotium.solo.ViewFetcher.getAllViews(ViewFetcher.java:83)
at com.jayway.android.robotium.solo.ViewFetcher.getViews(ViewFetcher.java:189)
at com.jayway.android.robotium.solo.ViewFetcher.getCurrentViews(ViewFetcher.java:308)
at com.jayway.android.robotium.solo.ViewFetcher.getCurrentViews(ViewFetcher.java:295)
at com.jayway.android.robotium.solo.Searcher$1.call(Searcher.java:117)
at com.jayway.android.robotium.solo.Searcher$1.call(Searcher.java:106)
at com.jayway.android.robotium.solo.Searcher.searchFor(Searcher.java:203)
at com.jayway.android.robotium.solo.Searcher.searchFor(Searcher.java:125)
... 19 more

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 06, 2013 09:10:44_

The fix has been pushed into the git repository. The next release will be in 3 weeks. Please let me know if this fix works well for you.

**Comment by renas** [comment]
_From [valentin...@gmail.com](https://code.google.com/u/106145933394766715411/) on March 06, 2013 09:27:55_

The fix in git works. Thanks for the amazingly fast response/fix!

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 06, 2013 09:29:53_

Great. Thank you for testing the fix.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 07, 2013 21:14:12_

This has been included in Robotium 4.1.

**Status:** Verified
