### ISSUE TITLE
Tests failing -error trace gives "java.lang.NoClassDefFoundError: com.jayway.android.robotium.solo.Solo"

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#494]
_From [n.navjot...@gmail.com](https://code.google.com/u/116578005561509956695/) on March 12, 2013 10:06:11_

Created a Test project using for the activity of the test class.
Trying to run Junit test
Test fail and getting 
"java.lang.NoClassDefFoundError: com.jayway.android.robotium.solo.Solo
at com.Delta.helloworld.test.InitialTest.setUp(InitialTest.java:18)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661)" error in the error trace.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=415_

**Comment by renas** [comment]
_From [carl.na...@sas.com](https://code.google.com/u/109112886858732574266/) on March 12, 2013 11:05:35_

This sounds like the robotium JAR file(s) has not been packaged up in the Test APK.

**Comment by renas** [comment]
_From [n.navjot...@gmail.com](https://code.google.com/u/116578005561509956695/) on March 12, 2013 11:12:01_

I have added the robotium jar files in the build path.
There is just one problem i'm having in my Test class is the constructor.
If I use "super("com.Delta.helloworld",MainActivity.class);" in the constructor , it gets deprecated. So, I used "super(MainActivity.class);"

*************************************************************************************

package com.Delta.helloworld.test;

import com.Delta.helloworld.MainActivity;
import com.jayway.android.robotium.solo.Solo;

import android.test.ActivityInstrumentationTestCase2;

public class InitialTest extends ActivityInstrumentationTestCase2<MainActivity> {

	private Solo solo;
	
	public InitialTest() {
		super("com.Delta.helloworld",MainActivity.class);
	}

	protected void setUp() throws Exception {
		super.setUp();
		solo = new Solo(getInstrumentation(), getActivity());
	}
	
	public void testADd(){
		
		solo.assertCurrentActivity("testing", MainActivity.class);
		
	}

}

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 12, 2013 23:28:34_

Please see the tutorial: "Common Robotium Issues" https://code.google.com/p/robotium/wiki/RobotiumTutorials

**Status:** Invalid  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [ayushbag...@gmail.com](https://code.google.com/u/101338145441586689216/) on April 15, 2015 00:38:54_

I have added the jar file, even gone through the document "Common Robtoium Issues", implemented the solution given for  "java.lang.NoClassDefFoundError:com.jayway.android.robotium.solo.Solo"
but I am not able to run it. Still showing the same problem.
