### ISSUE TITLE
TextView cannot be cast to Button (getButton() method)

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#496]
_From [keymusic...@gmail.com](https://code.google.com/u/100593211173840709450/) on March 15, 2013 06:00:37_

What steps will reproduce the problem? 1. Button button = solo.getButton(name); What is the expected output? What do you see instead? java.lang.ClassCastException: android.widget.TextView cannot be cast to android.widget.Button
at com.jayway.android.robotium.solo.Solo.getButton(Solo.java:1741)
at com.tecomgroup.handifox.steps.CommonSteps.clickOnButton(CommonSteps.java:35)
at com.tecomgroup.handifox.webServiceClient.TestManager.click(TestManager.java:211)
at com.tecomgroup.handifox.webServiceClient.TestManager.execute(TestManager.java:61)
at main.testHandiFox(main.java:65)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:545)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1575) What version of the product are you using? On what operating system? robotium-solo-4.0.jar, Android 4.0.4 (Samsung galaxy tab, GT-P5110) Please provide any additional information below. Robotium 4.0 works great, but I have to use the 3.6 version due to this issue.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=417_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 15, 2013 06:25:11_

Thanks for reporting this. Unfortunately it's a bug that came with all the internal changes of 4.0. The fix will be included in the next release that is due in the beginning of April.

**Status:** Accepted  
  **Owner:** renasr...@gmail.com  
  **Labels:** -Type-Enhancement

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 07, 2013 21:14:29_

This has been fixed in Robotium 4.1

**Status:** Verified
