### ISSUE TITLE
java.lang.NoSuchFieldException: mRenderer in wrapAllGLViews

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#512]
_From [jiongxin...@gmail.com](https://code.google.com/u/110835442896443543428/) on April 10, 2013 23:16:28_

What steps will reproduce the problem? 1.I tested the method of takeScreenshot on 4.2.2.
2.The UI of app has a GLSurfaceView
3.When I invoke takeScreenshot, an exception will happen:
java.lang.NoSuchFieldException: mRenderer
 	at java.lang.Class.getDeclaredField(Class.java:631)
 	at sogou.test.agent.framework.robotium.Reflect$FieldRf.getField(Reflect.java:110)
 	at sogou.test.agent.framework.robotium.Reflect$FieldRf.out(Reflect.java:68) 

What should I do to solve this problem?

_Original issue: http://code.google.com/p/robotium/issues/detail?id=433_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 11, 2013 00:54:54_

Thanks for reporting this. Would it be possible for you to send me an app that exhibits this issue?

**Status:** Accepted  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [jiongxin...@gmail.com](https://code.google.com/u/110835442896443543428/) on April 11, 2013 01:06:45_

Sorry, I can't send you an app I used, because the application is in the testing phase , there is no dissemination version.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 11, 2013 05:19:03_

Is the screenshot taken?

**Comment by renas** [comment]
_From [jiongxin...@gmail.com](https://code.google.com/u/110835442896443543428/) on April 11, 2013 06:22:50_

No, the screenshot is black. I tested the method on another app of GLSurfaceView, and 
there is no exception, but the screenshot is also black. I will send you the app.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 11, 2013 07:45:31_

Great. Thanks.

**Comment by renas** [comment]
_From [jiongxin...@gmail.com](https://code.google.com/u/110835442896443543428/) on April 11, 2013 18:07:26_

Hi, I just found that the app I send to you using SurfaceView, not GLSurfaceView.

**Comment by renas** [comment]
_From [jiongxin...@gmail.com](https://code.google.com/u/110835442896443543428/) on April 11, 2013 18:27:42_

I send you another app, please have a look.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 11, 2013 22:01:38_

I have not received any files from you. Please send it to renasreda@gmail.com.

**Comment by renas** [comment]
_From [jiongxin...@gmail.com](https://code.google.com/u/110835442896443543428/) on April 12, 2013 00:14:03_

Okay.

**Comment by renas** [comment]
_From [berg...@uncle.se](https://code.google.com/u/107498801174108257890/) on April 13, 2013 10:00:36_

Hi, I guess we can get the source for your project but can you recreate the problem in a smaller project with just an opengl view so that I can see how the gl part is implemented?

**Comment by renas** [comment]
_From [jiongxin...@gmail.com](https://code.google.com/u/110835442896443543428/) on April 14, 2013 18:52:00_

Okay, I have send you the source code of my porject. Please have a look.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 17, 2013 11:12:44_

The sent project does not contain GL.

**Status:** Invalid

**Comment by renas** [comment]
_From [jesus.bo...@gmail.com](https://code.google.com/u/102960980643445188522/) on May 21, 2013 08:28:02_

how did you fix this?

**Comment by renas** [comment]
_From [cid.h...@gmail.com](https://code.google.com/u/117461383648209900072/) on May 21, 2013 08:55:57_

I have the same problem. I have a project that uses OpenGL with C++ and NDK. I'm using a game engine that uses GLSurfaceView. I'm using last version of robotium, 4.1.
In the LogCat I can see the same error:


java.lang.NoSuchFieldException: mRenderer
	at java.lang.Class.getDeclaredField(Class.java:631)
	at com.jayway.android.robotium.solo.Reflect$FieldRf.getField(Reflect.java:110)
	at com.jayway.android.robotium.solo.Reflect$FieldRf.out(Reflect.java:68)
	at com.jayway.android.robotium.solo.Solo.wrapAllGLViews(Solo.java:2301)
	at com.jayway.android.robotium.solo.Solo.takeScreenshot(Solo.java:2285)
	at com.jayway.android.robotium.solo.Solo.takeScreenshot(Solo.java:2271)
[...]


And I'm getting a black screenshot. Any advice?

**Comment by renas** [comment]
_From [a.shynke...@softteco.com](https://code.google.com/u/107974773264363507236/) on February 05, 2015 01:18:52_

Hello all.
I have the same issue when try take screenshot during test case.

There is my logcat:

02-05 12:15:42.001  17188-17259/bn.ereader W/System.err﹕ java.lang.IllegalArgumentException: field *.*.*.*.lib.curlOGL.CurlView.mRenderer has type *.*.*.*.lib.curlOGL.CurlRenderer, got com.robotium.solo.GLRenderWrapper
02-05 12:15:42.014  17188-17259/bn.ereader W/System.err﹕ at java.lang.reflect.Field.set(Native Method)
02-05 12:15:42.014  17188-17259/bn.ereader W/System.err﹕ at java.lang.reflect.Field.set(Field.java:557)
02-05 12:15:42.014  17188-17259/bn.ereader W/System.err﹕ at com.robotium.solo.Reflect$FieldRf.in(Reflect.java:82)
02-05 12:15:42.014  17188-17259/bn.ereader W/System.err﹕ at com.robotium.solo.ScreenshotTaker.wrapAllGLViews(ScreenshotTaker.java:195)

Have the solution of the problem found?

**Comment by renas** [comment]
_From [amar.pat...@gmail.com](https://code.google.com/u/100621994811967447784/) on May 14, 2015 02:50:20_

Hi All,

I am getting the same exception and the Robotium testcase is failed:

I am trying to test below APK that is downloaded from playstore:
com.navigon.navigator_checkout_eu40

Below are the exception logs :

5-14 15:13:57.409: E/AndroidRuntime(24912): FATAL EXCEPTION: main
05-14 15:13:57.409: E/AndroidRuntime(24912): Process: com.navigon.navigator_checkout_eu40, PID: 24912
05-14 15:13:57.409: E/AndroidRuntime(24912): java.lang.RuntimeException: Exception finding resource identifier
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at com.a.a.a.a.a(ProGuard:178)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at com.a.a.a.a.b(ProGuard:113)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at org.flinc.sdk.util.FlincSDKUtils.getRandomAvatars(ProGuard:80)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at org.flinc.sdk.overlay.nview.FlincNavigationView.getRandomAvatars(ProGuard:124)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at com.navigon.navigator_checkout_eu40.hmi.flinc.widget.NaviFlincNavigationView.performSwitchState(ProGuard:190)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at org.flinc.sdk.overlay.nview.FlincNavigationView.switchStateTo(ProGuard:98)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at org.flinc.sdk.overlay.nview.FlincNavigationViewLogic.showNavigationView(ProGuard:617)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at org.flinc.sdk.overlay.nview.FlincNavigationViewLogic.reset(ProGuard:728)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at org.flinc.sdk.overlay.nview.FlincNavigationViewLogic$2.run(ProGuard:115)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at android.os.Handler.handleCallback(Handler.java:739)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at android.os.Looper.loop(Looper.java:135)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at java.lang.reflect.Method.invoke(Native Method)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at java.lang.reflect.Method.invoke(Method.java:372)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
05-14 15:13:57.409: E/AndroidRuntime(24912): Caused by: java.lang.NoSuchFieldException: flinc_random_avatar_1
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at java.lang.Class.getDeclaredField(Class.java:890)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	at com.a.a.a.a.a(ProGuard:154)
05-14 15:13:57.409: E/AndroidRuntime(24912): 	... 16 more
05-14 15:13:57.410: W/ActivityManager(752): Error in app com.navigon.navigator_checkout_eu40 running instrumentation ComponentInfo{com.hcl.test_com_navigon_navigator_checkout_eu40/android.test.InstrumentationTestRunner}:
05-14 15:13:57.410: W/ActivityManager(752):   java.lang.NoSuchFieldException
05-14 15:13:57.410: W/ActivityManager(752):   java.lang.NoSuchFieldException: flinc_random_avatar_1
05-14 15:13:57.411: D/AndroidRuntime(24898): Shutting down VM

Please provide info on this.
