### ISSUE TITLE
Get web element by xpath

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#516]
_From [G.Rjab...@gmail.com](https://code.google.com/u/114613923384070765920/) on April 16, 2013 05:23:33_

What steps will reproduce the problem? 1. Have got xpath from the web structure
2. Call method solo.getWebElement(By.xpath()) in the webView
3. Receive error What is the expected output? What do you see instead? junit.framework.AssertionFailedError: WebElement with xpath: '//*[@id="nameOfelementID"]/tbody/tr[11]/td[2]/input[1]' is not found!
at com.jayway.android.robotium.solo.Solo.getWebElement(Solo.java:1832)
at com.ocleen.tv.test3.OcleenTestSearchActivity.testChotels(OcleenTestSearchActivity.java:731)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1599) What version of the product are you using? On what operating system? Robotium 4.1

_Original issue: http://code.google.com/p/robotium/issues/detail?id=437_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 16, 2013 06:11:15_

Thanks for reporting this. Would it be possible for you to share an application that exhibits this issue?

**Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on April 17, 2013 11:11:48_

Probably something wrong with the xpath. We have had reports before about issues with xpath and the problems have always been the xpath strings.

**Status:** Invalid

**Comment by renas** [comment]
_From [G.Rjab...@gmail.com](https://code.google.com/u/114613923384070765920/) on April 17, 2013 14:37:12_

I have tried several elements as I wrote you in a letter this web page was written in ASP.NET
