### ISSUE TITLE
Test run failed: Instrumentation run failed due to 'java.lang.ClassNotFoundException'

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#525]
_From [luca.c...@gmail.com](https://code.google.com/u/104653054699073497854/) on May 03, 2013 06:56:31_

What steps will reproduce the problem? launch the Junit, here the code:

package com.example.city;
import com.jayway.android.robotium.solo.Solo;
import java.util.Random;
import android.test.ActivityInstrumentationTestCase2;
@SuppressWarnings("unchecked")
public class MainActivity extends ActivityInstrumentationTestCase2{
private static final String TARGET_PACKAGE_ID="com.rcs.city1tap";
private static final String LAUNCHER_ACTIVITY_FULL_CLASSNAME="com.rcs.city1tap.HomeSplash";
private static Class launcherActivityClass;
static{
try
{
launcherActivityClass=Class.forName(LAUNCHER_ACTIVITY_FULL_CLASSNAME);
} catch (ClassNotFoundException e){
throw new RuntimeException(e);
}
}
public MainActivity()throws ClassNotFoundException{
super(launcherActivityClass);
}
private Solo solo;
@Override
protected void setUp() throws Exception
{
solo = new Solo(getInstrumentation(),getActivity());
}
public void testDisplayBlackBox() {

	
	//  registraione nuovo utente
	solo.sleep(6000);
	solo.clickOnButton(2);
	String name = "name" + Math.random();
	String surn = "surn" + Math.random();	
	solo.sleep(3000);
solo.goBack();
solo.clickOnMenuItem("Logout");

}
@Override
public void tearDown() throws Exception {
solo.finishOpenedActivities();
}
} What is the expected output? What do you see instead? i see the error:
Test run failed: Instrumentation run failed due to 'java.lang.ClassNotFoundException'

in the logcat

:23:06.676: E/QcrilMsgTunnelSocket(32358): IOExceptionjava.io.IOException: No such file or directoryReason: No such file or directory
05-03 15:23:07.126: E/LightSensor(774): Light old sensor_state 0, new sensor_state : 128 en : 1
05-03 15:23:07.146: E/Watchdog(774): !@Sync 1669
05-03 15:23:07.476: E/LightSensor(774): Light old sensor_state 128, new sensor_state : 0 en : 0
05-03 15:23:10.680: E/QcrilMsgTunnelSocket(32358): IOExceptionjava.io.IOException: No such file or directoryReason: No such file or directory
05-03 15:23:10.970: E/AndroidRuntime(6052): FATAL EXCEPTION: main
05-03 15:23:10.970: E/AndroidRuntime(6052): java.lang.ExceptionInInitializerError
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at java.lang.reflect.Constructor.constructNative(Native Method)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at junit.framework.TestSuite.createTest(TestSuite.java:61)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at junit.framework.TestSuite.addTestMethod(TestSuite.java:294)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at junit.framework.TestSuite.addTestsFromTestCase(TestSuite.java:150)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at junit.framework.TestSuite.<init>(TestSuite.java:129)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at junit.runner.BaseTestRunner.getTest(BaseTestRunner.java:118)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at android.test.AndroidTestRunner.getTest(AndroidTestRunner.java:148)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at android.test.AndroidTestRunner.setTestClassName(AndroidTestRunner.java:56)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at android.test.suitebuilder.TestSuiteBuilder.addTestClassByName(TestSuiteBuilder.java:80)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at android.test.InstrumentationTestRunner.parseTestClass(InstrumentationTestRunner.java:444)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at android.test.InstrumentationTestRunner.parseTestClasses(InstrumentationTestRunner.java:425)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at android.test.InstrumentationTestRunner.onCreate(InstrumentationTestRunner.java:370)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4558)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at android.app.ActivityThread.access$1400(ActivityThread.java:151)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at android.os.Looper.loop(Looper.java:137)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at android.app.ActivityThread.main(ActivityThread.java:5293)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at java.lang.reflect.Method.invoke(Method.java:511)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at dalvik.system.NativeStart.main(Native Method)
05-03 15:23:10.970: E/AndroidRuntime(6052): Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.rcs.city1tap.HomeSplash
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at com.example.city.MainActivity.<clinit>(MainActivity.java:16)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	... 24 more
05-03 15:23:10.970: E/AndroidRuntime(6052): Caused by: java.lang.ClassNotFoundException: com.rcs.city1tap.HomeSplash
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at java.lang.Class.classForName(Native Method)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at java.lang.Class.forName(Class.java:217)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at java.lang.Class.forName(Class.java:172)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at com.example.city.MainActivity.<clinit>(MainActivity.java:14)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	... 24 more
05-03 15:23:10.970: E/AndroidRuntime(6052): Caused by: java.lang.NoClassDefFoundError: com/rcs/city1tap/HomeSplash
05-03 15:23:10.970: E/AndroidRuntime(6052): 	... 28 more
05-03 15:23:10.970: E/AndroidRuntime(6052): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.rcs.city1tap.HomeSplash" on path: /system/framework/android.test.runner.jar:/data/app/com.example.city-2.apk:/data/app/com.rcs.city1tap-1.apk
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
05-03 15:23:10.970: E/AndroidRuntime(6052): 	... 28 more
05-03 15:23:14.693: E/QcrilMsgTunnelSocket(32358): IOExceptionjava.io.IOException: No such file or directoryReason: No such file or directory
05-03 15:23:16.135: E/MP-Decision(1861): num online cores: 2 reqd : 1 available : 4 rq_depth:0.000000 hotplug_avg_load_dw: 29
05-03 15:23:16.135: E/MP-Decision(1861): DOWN cpu:1 core_idx:1 Ns:1.100000 Ts:190 total_time_down:206.000000
05-03 15:23:18.687: E/QcrilMsgTunnelSocket(32358): IOExcepti...

_Original issue: http://code.google.com/p/robotium/issues/detail?id=446_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on May 06, 2013 01:50:42_

Unfortunately I can not tell you what is wrong. This is not a bug in Robotiut but an issue with your test project/environment The only thing I can do is to recommend you to see the "Common Robotium Issues" document: https://code.google.com/p/robotium/wiki/RobotiumTutorials

**Status:** Invalid  
  **Owner:** renasr...@gmail.com
