### ISSUE TITLE
Unable to locate webelement in hybrid android application

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#531]
_From [suryakantaml@gmail.com](https://code.google.com/u/suryakantaml@gmail.com/) on May 10, 2013 13:57:30_

I am trying to automate one android hybrid app using Robotium 4.0. The script is as follows:
**********************************************

package com.tcs.robotiumtesting;

import android.test.ActivityInstrumentationTestCase2;
import com.jayway.android.robotium.solo.By;
import com.jayway.android.robotium.solo.Solo;

@SuppressWarnings("rawtypes")
public class TC001_GstAcct_AdnwAdd extends ActivityInstrumentationTestCase2 {

private static final String TARGET_PACKAGE_ID = "com.target.ui";
private static final String LAUNCHERACTIVITY_FULL_CLASSNAME = "com.target.android.activity.TopLevelNavigationActivity";
private static Class<?> launcherActivityClass;
	static {
		try {
			launcherActivityClass = Class
				.forName(LAUNCHERACTIVITY_FULL_CLASSNAME);
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
	}
	@SuppressWarnings({ "unchecked", "deprecation" })
	public TC001_GstAcct_AdnwAdd() throws ClassNotFoundException {
		super(TARGET_PACKAGE_ID,launcherActivityClass);
	}
	public  Solo solo;
	@Override
	protected void setUp() throws Exception {
		super.setUp();
		solo=new Solo(getInstrumentation(), getActivity());
        }
	@Override
	protected void tearDown() throws Exception {
		solo.finishOpenedActivities();
	}
	public void testCase1() throws Exception{
		solo.clickOnImageButton(0);
		synchronized(solo) {solo.wait(2000);}
		solo.clickOnText("My Accounts");
		synchronized(solo) {solo.wait(2000);}
		solo.clickOnText("My Target.com Account");
		synchronized(solo) {solo.wait(15000);}
		//solo.clickOnWebElement(By.xpath("//*[@id='logonId']"));
		solo.enterTextInWebElement(By.name("logonId"),       "suryakantaml@gmail.com");
	}
}

**********************************************
When i execute the above script, everything goes well but the last step which should write "suryakantaml@gmail.com" in the login edit box of the web view.I tried accessing login edit box using name, id and xpath but failed every time.The error message is as follows:

***********************************************************
05-10 20:30:18.391: I/TestRunner(3242): failed: testCase1(com.tcs.robotiumtesting.TC001_GstAcct_AdnwAdd)
05-10 20:30:18.391: I/TestRunner(3242): ----- begin exception -----
05-10 20:30:18.411: I/TestRunner(3242): junit.framework.AssertionFailedError: There is no web element with Name: logonId
05-10 20:30:18.411: I/TestRunner(3242): 	at junit.framework.Assert.fail(Assert.java:50)
05-10 20:30:18.411: I/TestRunner(3242): 	at junit.framework.Assert.assertTrue(Assert.java:20)
05-10 20:30:18.411: I/TestRunner(3242): 	at com.jayway.android.robotium.solo.Solo.enterTextInWebElement(Solo.java:1529)
05-10 20:30:18.411: I/TestRunner(3242): 	at com.tcs.robotiumtesting.TC001_GstAcct_AdnwAdd.testCase1(TC001_GstAcct_AdnwAdd.java:56)
05-10 20:30:18.411: I/TestRunner(3242): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-10 20:30:18.411: I/TestRunner(3242): 	at java.lang.reflect.Method.invoke(Method.java:511)
05-10 20:30:18.411: I/TestRunner(3242): 	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
05-10 20:30:18.411: I/TestRunner(3242): 	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
05-10 20:30:18.411: I/TestRunner(3242): 	at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
05-10 20:30:18.411: I/TestRunner(3242): 	at junit.framework.TestCase.runBare(TestCase.java:134)
05-10 20:30:18.411: I/TestRunner(3242): 	at junit.framework.TestResult$1.protect(TestResult.java:115)
05-10 20:30:18.411: I/TestRunner(3242): 	at junit.framework.TestResult.runProtected(TestResult.java:133)
05-10 20:30:18.411: I/TestRunner(3242): 	at junit.framework.TestResult.run(TestResult.java:118)
05-10 20:30:18.411: I/TestRunner(3242): 	at junit.framework.TestCase.run(TestCase.java:124)
05-10 20:30:18.411: I/TestRunner(3242): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
05-10 20:30:18.411: I/TestRunner(3242): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
05-10 20:30:18.411: I/TestRunner(3242): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
05-10 20:30:18.411: I/TestRunner(3242): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661)
05-10 20:30:18.411: I/TestRunner(3242): ----- end exception -----
05-10 20:30:18.481: I/TestRunner(3242): finished: testCase1(com.tcs.robotiumtesting.TC001_GstAcct_AdnwAdd)

***********************************************************

Please help me resolve it out.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=452_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on May 13, 2013 00:58:27_

Please use Robotium 4.1 instead and try to use typeTextInWebelement() instead.

**Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on May 23, 2013 10:53:52_

Will open up if new information is given.

**Status:** Invalid
