### ISSUE TITLE
RobotiumRC does not connects and does not starts the tests

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#537]
_From [robso...@gmail.com](https://code.google.com/u/104787384330921518519/) on May 17, 2013 06:27:06_

In my project the tests does not starts and time
After instrument and TimeoutException occurs on run test: What steps will reproduce the problem? 1. Instruments the SAFSTCPMessenger and RobotiumTestRunner projects (ant debug)
2. Intall my project and SAFSTCPMessenger and RobotiumTestRunner projects  (adb install)
3. Run the test class on JUnit What is the expected output? What do you see instead? Expected to start launch app and run tests.. but not connects! What version of the product are you using? On what operating system? - Win 7 64bits - Intel Core i7 3.4 GHz - 8 GB Ram
- Robotium RC 2012.12.12
- JDK 1.6.0_21 Please provide any additional information below. - Console log on run test:
SocketProtocol.addListener(): AbstractRunner was successfully registered.
DroidSocketProtocol.addListener(): AbstractRunner was successfully registered.
Port forwarding will be from '2411'
DroidSocketProtocol.createRemoteClientConnection(): Local Runner attempting to make remote Runner connection...
Forwarding port from 'local:2411' to 'device/emulator:2410'
DroidSocketProtocol.createRemoteClientConnection(): Remote Runner seems to be connected!
DroidSocketProtocol.verifyRemoteClient(): Remote client did not verify in timeout period.
DroidSocketProtocol.createRemoteClientConnection(): Remote client did NOT verify itself as a remote SocketProtocolRunner!
Forwarding port from 'local:2411' to 'device/emulator:2410'
DroidSocketProtocol.createRemoteClientConnection(): Remote Runner seems to be connected!
DroidSocketProtocol.verifyRemoteClient(): Remote client did not verify in timeout period.
DroidSocketProtocol.createRemoteClientConnection(): Remote client did NOT verify itself as a remote SocketProtocolRunner!
Forwarding port from 'local:2411' to 'device/emulator:2410'
DroidSocketProtocol.createRemoteClientConnection(): Remote Runner seems to be connected!
DroidSocketProtocol.verifyRemoteClient(): Remote client did not verify in timeout period.
DroidSocketProtocol.createRemoteClientConnection(): Remote client did NOT verify itself as a remote SocketProtocolRunner!
Forwarding port from 'local:2411' to 'device/emulator:2410'
DroidSocketProtocol.createRemoteClientConnection(): Remote Runner seems to be connected!
DroidSocketProtocol.verifyRemoteClient(): Remote client did not verify in timeout period.
DroidSocketProtocol.createRemoteClientConnection(): Remote client did NOT verify itself as a remote SocketProtocolRunner!
Forwarding port from 'local:2411' to 'device/emulator:2410'
DroidSocketProtocol.createRemoteClientConnection(): Remote Runner seems to be connected!
DroidSocketProtocol.verifyRemoteClient(): Remote client did not verify in timeout period.
DroidSocketProtocol.createRemoteClientConnection(): Remote client did NOT verify itself as a remote SocketProtocolRunner!
Forwarding port from 'local:2411' to 'device/emulator:2410'
DroidSocketProtocol.createRemoteClientConnection(): Remote Runner seems to be connected!
DroidSocketProtocol.verifyRemoteClient(): Remote client did not verify in timeout period.
DroidSocketProtocol.createRemoteClientConnection(): Remote client did NOT verify itself as a remote SocketProtocolRunner!
DroidSocketProtocol.createRemoteClientConnection(): The remotePort is set to next possible port number '2412'
DroidSocketProtocol.createRemoteClientConnection(): Local Runner attempting to make remote Runner connection...
Forwarding port from 'local:2411' to 'device/emulator:2412'
DroidSocketProtocol.createRemoteClientConnection(): Remote Runner seems to be connected!
DroidSocketProtocol.verifyRemoteClient(): Remote client did not verify in timeout period.
DroidSocketProtocol.createRemoteClientConnection(): Remote client did NOT verify itself as a remote SocketProtocolRunner!
Forwarding port from 'local:2411' to 'device/emulator:2412'
DroidSocketProtocol.createRemoteClientConnection(): Remote Runner seems to be connected!
DroidSocketProtocol.verifyRemoteClient(): Remote client did not verify in timeout period.
DroidSocketProtocol.createRemoteClientConnection(): Remote client did NOT verify itself as a remote SocketProtocolRunner!
Forwarding port from 'local:2411' to 'device/emulator:2412'
DroidSocketProtocol.createRemoteClientConnection(): Remote Runner seems to be connected!
DroidSocketProtocol.verifyRemoteClient(): Remote client did not verify in timeout period.
DroidSocketProtocol.createRemoteClientConnection(): Remote client did NOT verify itself as a remote SocketProtocolRunner!
Forwarding port from 'local:2411' to 'device/emulator:2412'
DroidSocketProtocol.createRemoteClientConnection(): Remote Runner seems to be connected!
DroidSocketProtocol.verifyRemoteClient(): Remote client did not verify in timeout period.
DroidSocketProtocol.createRemoteClientConnection(): Remote client did NOT verify itself as a remote SocketProtocolRunner!
Forwarding port from 'local:2411' to 'device/emulator:2412'
DroidSocketProtocol.createRemoteClientConnection(): Remote Runner seems to be connected!
DroidSocketProtocol.verifyRemoteClient(): Remote client did not verify in timeout period.
DroidSocketProtocol.createRemoteClientConnection(): Remote client did NOT verify itself as a remote SocketProtocolRunner!
Forwarding port from 'local:2411' to 'device/emulator:2412'
DroidSocketProtocol.createRemoteClientConnection(): Remote Runner seems to be connected!
java.util.concurrent.TimeoutException: waitForRemoteConnected Timeout before Connect
	at com.jayway.android.robotium.remotecontrol.solo.SoloRemoteControl.waitForRemoteConnected(SoloRemoteControl.java:502)
	at com.jayway.android.robotium.remotecontrol.solo.SoloWorker.initialize(SoloWorker.java:161)
	at com.jayway.android.robotium.remotecontrol.solo.SoloTest.initialize(SoloTest.java:532)
	at br.fpf.test.cucumber.robotiumrc.CucumberRCTestConfig.startMainLaunch(CucumberRCTestConfig.java:256)
	at br.fpf.test.automatedtest.common.cucumber.defaultsteps.TestBase2.startScenario(TestBase2.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at cucumber.runtime.Utils$1.call(Utils.java:42)
	at cucumber.runtime.Timeout.timeout(Timeout.java:12)
	at cucumber.runtime.Utils.invoke(Utils.java:38)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:59)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:192)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:184)
	at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:175)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:35)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:76)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:65)
	at cucumber.runtime.junit.FeatureRunner.runChild(Fea...

_Original issue: http://code.google.com/p/robotium/issues/detail?id=458_

**Comment by renas** [comment]
_From [carl.na...@sas.com](https://code.google.com/u/109112886858732574266/) on May 17, 2013 07:43:34_

Don't know how good or bad the entire setup is that you have, but you don't provide any information here as to why the TestRunner on the device/emulator does not launch--or does not launch successfully.

Can you review and provide some adb logcat output so that we can see if there is an indication of a problem launching the TestRunner on the device?

**Status:** Incomplete  
  **Owner:** carl.na...@sas.com

**Comment by renas** [comment]
_From [robso...@gmail.com](https://code.google.com/u/104787384330921518519/) on May 20, 2013 05:58:26_

Thank you for your feedback,
Follow the log from test execution..

05-20 08:46:26.291: D/AndroidRuntime(3653): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit \<<<<<<
05-20 08:46:26.291: D/AndroidRuntime(3653): CheckJNI is OFF
05-20 08:46:26.291: D/AndroidRuntime(3653): setted country_code = Brazil
05-20 08:46:26.291: D/AndroidRuntime(3653): setted sales_code = ZTO
05-20 08:46:26.291: D/AndroidRuntime(3653): found sales_code tag = \<ZTO>, \</ZTO> 
05-20 08:46:26.451: D/LibQmg_native(3653): register_android_app_LibQmg
05-20 08:46:26.471: D/AndroidRuntime(3653): Calling main entry com.android.commands.pm.Pm
05-20 08:46:26.471: I/ActivityManager(185): Force stopping package name uid=10026
05-20 08:46:26.481: I/SevenBroadCastReceiver(2071): ==============================================
05-20 08:46:26.481: I/SevenBroadCastReceiver(2071): 	SevenBroadCastReceiver.onReceive() 
05-20 08:46:26.481: D/AndroidRuntime(3653): Shutting down VM
05-20 08:46:26.481: I/SevenBroadCastReceiver(2071): 	intent.getAction() :  android.intent.action.PACKAGE_DATA_CLEARED
05-20 08:46:26.481: I/SevenBroadCastReceiver(2071): ==============================================
05-20 08:46:26.481: E/SevenAdapter(2071): [SevenAdapter] isAvailable() is called
05-20 08:46:26.491: D/dalvikvm(3653): GC_CONCURRENT freed 101K, 82% free 474K/2560K, paused 0ms+0ms
05-20 08:46:26.491: I/AndroidRuntime(3653): NOTE: attach of thread 'Binder Thread `#3`' failed
05-20 08:46:26.491: D/jdwp(3653): Got wake-up signal, bailing out of select
05-20 08:46:26.491: D/dalvikvm(3653): Debugger has detached; object registry had 1 entries
05-20 08:46:26.491: E/SocialHub(2309): [UinboxReceiver] onReceive() >> Context is android.app.ReceiverRestrictedContext@413e7c28
05-20 08:46:26.491: D/SocialHub(2309): [UinboxReceiver]  On Receive  >>  ContentUri is NULL >>
05-20 08:46:26.921: D/AndroidRuntime(3666): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit \<<<<<<
05-20 08:46:26.921: D/AndroidRuntime(3666): CheckJNI is OFF
05-20 08:46:26.931: D/AndroidRuntime(3666): setted country_code = Brazil
05-20 08:46:26.931: D/AndroidRuntime(3666): setted sales_code = ZTO
05-20 08:46:26.931: D/AndroidRuntime(3666): found sales_code tag = \<ZTO>, \</ZTO> 
05-20 08:46:27.071: D/LibQmg_native(3666): register_android_app_LibQmg
05-20 08:46:27.091: D/AndroidRuntime(3666): Calling main entry com.android.commands.am.Am
05-20 08:46:27.101: I/ActivityManager(185): Force stopping package name uid=10026
05-20 08:46:27.111: D/dalvikvm(3676): Late-enabling CheckJNI
05-20 08:46:27.111: D/AndroidRuntime(3666): Shutting down VM
05-20 08:46:27.111: I/ActivityManager(185): Start proc app.processName for added application hostingNameStr: pid=3676 uid=10026 gids={3003, 1015}
05-20 08:46:27.121: D/dalvikvm(3666): GC_CONCURRENT freed 101K, 82% free 475K/2560K, paused 0ms+1ms
05-20 08:46:27.121: D/jdwp(3666): Got wake-up signal, bailing out of select
05-20 08:46:27.121: D/dalvikvm(3666): Debugger has detached; object registry had 1 entries
05-20 08:46:27.121: I/AndroidRuntime(3666): NOTE: attach of thread 'Binder Thread `#3`' failed
05-20 08:46:27.141: D/dalvikvm(3676): Debugger has detached; object registry had 1 entries
05-20 08:46:27.221: D/RobotiumTestRunner(3676): SAFS TCP Messenger Binding:MessengerService
05-20 08:46:27.221: D/RobotiumTestRunner(3676): Found target Package: com.test.project
05-20 08:46:27.221: I/System.out(3220): SocketProtocol.addListener(): AbstractRunner was successfully registered.
05-20 08:46:27.231: D/RobotiumTestRunner(3676): Found Launch Intent Action: android.intent.action.MAIN
05-20 08:46:27.231: D/RobotiumTestRunner(3676): Is ACTION_MAIN  : true
05-20 08:46:27.231: D/RobotiumTestRunner(3676): Found Launch Component: com.test.project.view.activity.SplashActivity
05-20 08:46:27.231: D/RobotiumTestRunner(3676): Found 9 target Activities.
05-20 08:46:27.231: D/RobotiumTestRunner(3676):    Activity Name: com.test.project.view.activity.SplashActivity
05-20 08:46:27.231: D/RobotiumTestRunner(3676):    Activity Name: com.test.project.view.activity.MovieActivity
05-20 08:46:27.231: D/RobotiumTestRunner(3676):    Activity Name: com.test.project.view.activity.TutorialActivity
05-20 08:46:27.231: D/RobotiumTestRunner(3676):    Activity Name: com.test.project.view.activity.TheaterActivity
05-20 08:46:27.231: D/RobotiumTestRunner(3676):    Activity Name: com.test.project.view.activity.MyCinemarkActivity
05-20 08:46:27.231: D/RobotiumTestRunner(3676):    Activity Name: com.test.project.view.activity.TrailerActivity
05-20 08:46:27.231: D/RobotiumTestRunner(3676):    Activity Name: com.test.project.view.activity.TwitterActivity
05-20 08:46:27.231: D/RobotiumTestRunner(3676):    Activity Name: com.google.ads.AdActivity
05-20 08:46:27.231: D/RobotiumTestRunner(3676):    Activity Name: com.facebook.LoginActivity
05-20 08:46:27.231: D/RobotiumTestRunner(3676): createTestCase commencing...
05-20 08:46:27.231: W/dalvikvm(3676): Class resolved by unexpected DEX: Lcom/test/project/view/activity/SplashActivity;(0x41349630):0x812c68 ref [Landroid/support/v4/app/FragmentActivity;] Landroid/support/v4/app/FragmentActivity;(0x41349630):0x7ea7c8
05-20 08:46:27.231: W/dalvikvm(3676): (Lcom/test/project/view/activity/SplashActivity; had used a different Landroid/support/v4/app/FragmentActivity; during pre-verification)
05-20 08:46:27.231: W/dalvikvm(3676): Unable to resolve superclass of Lcom/test/project/view/activity/SplashActivity; (158)
05-20 08:46:27.231: W/dalvikvm(3676): Link of class 'Lcom/test/project/view/activity/SplashActivity;' failed
05-20 08:46:27.231: D/RobotiumTestRunner(3676): ClassNotFoundException: com.test.project.view.activity.SplashActivity can't be found.
05-20 08:46:27.231: D/RobotiumTestRunner(3676): initializeInstrumentation commencing...
05-20 08:46:27.231: D/AndroidRuntime(3676): Shutting down VM
05-20 08:46:27.241: W/dalvikvm(3676): threadid=1: thread exiting with uncaught exception (group=0x40c431f8)
05-20 08:46:27.241: E/AndroidRuntime(3676): FATAL EXCEPTION: main
05-20 08:46:27.241: E/AndroidRuntime(3676): java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{com.jayway.android.robotium.remotecontrol.client/com.jayway.android.robotium.remotecontrol.client.RobotiumTestRunner}: java.lang.NullPointerException
05-20 08:46:27.241: E/AndroidRuntime(3676): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3935)
05-20 08:46:27.241: E/AndroidRuntime(3676): 	at android.app.ActivityThread.access$1300(ActivityThread.java:127)
05-20 08:46:27.241: E/AndroidRuntime(3676): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1197)
05-20 08:46:27.241: E/AndroidRuntime(3676): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-20 08:46:27.241: E/AndroidRuntime(3676): 	at android.os.Looper.loop(Looper.java:137)
05-20 08:46:27.241: E/AndroidRuntime(3676): 	at android.app.ActivityThread.main(ActivityT...

**Comment by renas** [comment]
_From [robso...@gmail.com](https://code.google.com/u/104787384330921518519/) on May 20, 2013 05:58:26_

...hread.java:4507)
05-20 08:46:27.241: E/AndroidRuntime(3676): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-20 08:46:27.241: E/AndroidRuntime(3676): 	at java.lang.reflect.Method.invoke(Method.java:511)
05-20 08:46:27.241: E/AndroidRuntime(3676): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
05-20 08:46:27.241: E/AndroidRuntime(3676): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
05-20 08:46:27.241: E/AndroidRuntime(3676): 	at dalvik.system.NativeStart.main(Native Method)
05-20 08:46:27.241: E/AndroidRuntime(3676): Caused by: java.lang.NullPointerException
05-20 08:46:27.241: E/AndroidRuntime(3676): 	at com.jayway.android.robotium.remotecontrol.client.RobotiumTestRunner.initializeInstrumentation(RobotiumTestRunner.java:172)
05-20 08:46:27.241: E/AndroidRuntime(3676): 	at com.jayway.android.robotium.remotecontrol.client.RobotiumTestRunner.beforeStart(RobotiumTestRunner.java:232)
05-20 08:46:27.241: E/AndroidRuntime(3676): 	at com.jayway.android.robotium.remotecontrol.client.AbstractTestRunner.onCreate(AbstractTestRunner.java:150)
05-20 08:46:27.241: E/AndroidRuntime(3676): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3932)
05-20 08:46:27.241: E/AndroidRuntime(3676): 	... 10 more
05-20 08:46:27.241: W/ActivityManager(185): Error in app r.processName running instrumentation r.instrumentationClass:
05-20 08:46:27.241: W/ActivityManager(185):   java.lang.NullPointerException
05-20 08:46:27.241: W/ActivityManager(185):   java.lang.NullPointerException: Exception thrown in onCreate() of ComponentInfo{com.jayway.android.robotium.remotecontrol.client/com.jayway.android.robotium.remotecontrol.client.RobotiumTestRunner}: java.lang.NullPointerException
05-20 08:46:27.251: D/SAFSMessenger(3220): Service has been destroyed!
05-20 08:46:27.251: I/ActivityManager(185): Force stopping package name uid=10026
05-20 08:46:27.251: I/ActivityManager(185): Killing proc 3676:com.test.project/10026: force stop
05-20 08:46:27.271: D/dalvikvm(3220): GC_CONCURRENT freed 1203K, 19% free 6894K/8455K, paused 2ms+1ms
05-20 08:46:27.281: D/SAFSMessenger(3220): SocketProtocol.createRemoteServerSocket(): NetworkInterface: lo, ::1%1, 127.0.0.1
05-20 08:46:27.281: D/SAFSMessenger(3220): SocketProtocol.createRemoteServerSocket(): NetworkInterface: rmnet0
05-20 08:46:27.281: D/SAFSMessenger(3220): SocketProtocol.createRemoteServerSocket(): NetworkInterface: rmnet1
05-20 08:46:27.281: D/SAFSMessenger(3220): SocketProtocol.createRemoteServerSocket(): NetworkInterface: rmnet2
05-20 08:46:27.281: D/SAFSMessenger(3220): SocketProtocol.createRemoteServerSocket(): NetworkInterface: dummy0
05-20 08:46:27.281: D/SAFSMessenger(3220): SocketProtocol.createRemoteServerSocket(): NetworkInterface: sit0
05-20 08:46:27.281: D/SAFSMessenger(3220): SocketProtocol.createRemoteServerSocket(): NetworkInterface: ip6tnl0
05-20 08:46:27.281: D/SAFSMessenger(3220): SocketProtocol.createRemoteServerSocket(): NetworkInterface: wlan0, fe80::1034:56ff:fe1d:fc4e%wlan0, 10.0.0.53
05-20 08:46:27.281: D/SAFSMessenger(3220): SocketProtocol.createRemoteServerSocket(): Try to create socket server at port '2410'.
05-20 08:46:27.281: D/SAFSMessenger(3220): SocketProtocol.createRemoteServerSocket(): Remote Runner available on port: 2410

\---

In project i'm using 2 externals apklibs.. need some additional configuration?

**Comment by renas** [comment]
_From [carl.na...@sas.com](https://code.google.com/u/109112886858732574266/) on May 20, 2013 08:15:13_

This is indicative of having the android-support-V4.jar in the TestRunner project when it probably should not be there.  If you are testing on Android 4.x platforms then this JAR file should not be used in the APK.  The classes it contains already exist on the platform.  

Additionally, you should be building that TestRunner with the Android SDK libs that already contain those classes.  So you would not reference this JAR file in your Android 4.x development projects.

The android-support-V4.jar file is only used when testing certain V4 features on Android 2.x and 3.x platforms.

Please let us know if removing this JAR file out of your project and APK fixes your problem.

**Status:** Started

**Comment by renas** [comment]
_From [robso...@gmail.com](https://code.google.com/u/104787384330921518519/) on May 23, 2013 15:04:27_

Hello Robotium team (sorry for the delay), 
I did some thorough testing on a sample application (raw, no nothing, just two screens) ..
and then, I realized that the problem is when I use any class that uses the api supporte android (support-v4).
if I comment out the call to these classes the test works!
see the log from logcat:

\------

05-23 16:52:35.653: W/dalvikvm(30506): Class resolved by unexpected DEX: Lcom/test/project/Tela2Activity;(0x4126b360):0x11cda18 ref [Landroid/support/v4/app/FragmentActivity;] Landroid/support/v4/app/FragmentActivity;(0x4126b360):0x131ab38
05-23 16:52:35.653: W/dalvikvm(30506): (Lcom/test/project/Tela2Activity; had used a different Landroid/support/v4/app/FragmentActivity; during pre-verification)
05-23 16:52:35.661: W/dalvikvm(30506): Unable to resolve superclass of Lcom/test/project/Tela2Activity; (137)
05-23 16:52:35.661: W/dalvikvm(30506): Link of class 'Lcom/test/project/Tela2Activity;' failed
05-23 16:52:35.661: W/dalvikvm(30506): threadid=1: thread exiting with uncaught exception (group=0x40bdb1f8)
05-23 16:52:35.684: E/AndroidRuntime(30506): FATAL EXCEPTION: main
05-23 16:52:35.684: E/AndroidRuntime(30506): java.lang.NoClassDefFoundError: com/test/project/Tela2Activity
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at com.test.project.HomeActivity$1.onClick(HomeActivity.java:28)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at android.view.View.performClick(View.java:3558)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at android.view.View$PerformClick.run(View.java:14152)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at android.os.Handler.handleCallback(Handler.java:605)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at android.os.Handler.dispatchMessage(Handler.java:92)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at android.os.Looper.loop(Looper.java:137)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at android.app.ActivityThread.main(ActivityThread.java:4514)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at java.lang.reflect.Method.invoke(Method.java:511)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at dalvik.system.NativeStart.main(Native Method)
05-23 16:52:35.684: E/AndroidRuntime(30506): Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at dalvik.system.DexFile.defineClass(Native Method)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:195)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at dalvik.system.DexPathList.findClass(DexPathList.java:315)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:58)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
05-23 16:52:35.684: E/AndroidRuntime(30506): 	... 12 more
05-23 16:52:35.692: W/ActivityManager(216): Error in app com.test.project running instrumentation ComponentInfo{com.jayway.android.robotium.remotecontrol.client/com.jayway.android.robotium.remotecontrol.client.RobotiumTestRunner}:
05-23 16:52:35.692: W/ActivityManager(216):   java.lang.IllegalAccessError
05-23 16:52:35.692: W/ActivityManager(216):   java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
05-23 16:52:35.692: W/ActivityManager(216): Force removing ActivityRecord{415ff0b0 com.test.project/.HomeActivity}: app died, no saved state
05-23 16:52:35.700: W/ActivityManager(216): mDVFSLock.acquire()

\------

log from other app test:

05-23 18:14:56.809: W/dalvikvm(4249): Class resolved by unexpected DEX: Lcom/test/project2/view/activity/SplashActivity;(0x4126e410):0x11dde10 ref [Landroid/support/v4/content/LocalBroadcastManager;] Landroid/support/v4/content/LocalBroadcastManager;(0x4126e410):0x11ddcc8
05-23 18:14:56.809: W/dalvikvm(4249): (Lcom/test/project2/view/activity/SplashActivity; had used a different Landroid/support/v4/content/LocalBroadcastManager; during pre-verification)
05-23 18:14:56.809: W/dalvikvm(4249): threadid=1: thread exiting with uncaught exception (group=0x40bdb1f8)
05-23 18:14:56.809: E/AndroidRuntime(4249): FATAL EXCEPTION: main
05-23 18:14:56.809: E/AndroidRuntime(4249): java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at com.test.project2.view.activity.SplashActivity.onResume(SplashActivity.java:90)
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1158)
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at android.app.Activity.performResume(Activity.java:4539)
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2448)
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2486)
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2000)
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at android.app.ActivityThread.access$600(ActivityThread.java:128)
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161)
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at android.os.Looper.loop(Looper.java:137)
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at android.app.ActivityThread.main(ActivityThread.java:4514)
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at java.lang.reflect.Method.invoke(Method.java:511)
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
05-23 18:14:56.809: E/AndroidRuntime(4249): 	at dalvik.system.NativeStart.main(Native Method)
05-23 18:14:56.817: W/ActivityManager(216): Error in app com.test.project2 running instrumentation ComponentInfo{com.jayway.android.robotium.remotecontrol.client/com.jayway.android.robotium.remotecontrol.client.RobotiumTestRunner}:
05-23 18:14:56.817: W/ActivityManager(216):   java.lang.IllegalAccessError
05-23 18:14:56.817: W/ActivityManager(216):   java.lang.Illeg...

**Comment by renas** [comment]
_From [robso...@gmail.com](https://code.google.com/u/104787384330921518519/) on May 23, 2013 15:04:27_

...alAccessError: Class ref in pre-verified class resolved to unexpected implementation
05-23 18:14:56.817: W/ActivityManager(216): Force removing ActivityRecord{419d0948 com.test.project2/.view.activity.SplashActivity}: app died, no saved state

\------

My dependencies (android and support ) in pom.xml:

		\<dependency>
			\<groupId>com.google.android</groupId>
			\<artifactId>android</artifactId>
			\<version>4.0.1.2</version>
			\<scope>provided</scope>
		\</dependency>

		\<dependency>
			\<groupId>com.google.android</groupId>
			\<artifactId>support-v4</artifactId>
			\<version> r7 \</version>
		\</dependency>


...
any suggestions of what can be?

and how the new version of Remote Control, have some foresight release?

Att,
Robson

**Comment by renas** [comment]
_From [carl.na...@sas.com](https://code.google.com/u/109112886858732574266/) on May 23, 2013 17:20:14_

For V4 apps you need to remove the android-support-v4.jar from the testrunner project. This jar is only used when building and running with pre-v4 sdks and devices. When building with a v4 sdk and running on v4 devices the necessary classes are already included.

Let us know when you have tried this and if it resolved your problem.

Carl Nagle

**Status:** Incomplete

**Comment by renas** [comment]
_From [robso...@gmail.com](https://code.google.com/u/104787384330921518519/) on May 24, 2013 07:31:55_

the problem really was it! after two days thinking that the problem was in the app ... but was the support api in RobotiumTestRunner project..

Thank you so much Robotium team..

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 15, 2013 19:06:56_

**Status:** Invalid
