### ISSUE TITLE
Cannot use getCurrentWebElements for an Hybrid App

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#538]
_From [k.pa...@gmail.com](https://code.google.com/u/113842173808975368493/) on May 20, 2013 02:54:00_

What steps will reproduce the problem? I have an hybrid app which has a WebView. I am trying to use getCurrentWebElements on this WebView. Below is my code:

package com.sqs.test;

import java.util.ArrayList;

import android.test.ActivityInstrumentationTestCase2;

@SuppressWarnings("unchecked")
public class P0002_tc0001_testcase1_N1_D1 extends ActivityInstrumentationTestCase2 {

  private static final String TARGET_PACKAGE_ID ="de.telekom.epub";
  private static final String LAUNCHER_ACTIVITY_FULL_CLASSNAME = "de.telekom.epub.ui.activities.SplashScreenActivity";
  private static Class launcherActivityClass;
  private Sobo solo;
  
  static 
  {
    try
    {
      launcherActivityClass=Class.forName(LAUNCHER_ACTIVITY_FULL_CLASSNAME);
    }
    catch (ClassNotFoundException e)
    {
      throw new RuntimeException(e);
    }
  }

  @SuppressWarnings("deprecation")
public P0002_tc0001_testcase1_N1_D1() throws ClassNotFoundException
  {
    super(TARGET_PACKAGE_ID,launcherActivityClass);
  }

  @Override
  public void setUp() throws Exception
  {
    solo = new Robo(getInstrumentation(),getActivity());
  }

  @Override
  public void tearDown() throws Exception
  {
    solo.finishOpenedActivities();
  }

  public void testDisplayBlackBox()
  {
	solo.clickOnImageButton(0);
	synchronized(solo) {solo.wait(2000);}
	ArrayList<WebElement> webViewCollection = solo.getCurrentWebElements();
	for (WebElement vw : webViewCollection) {
		 String objectClass = vw.getClass().toString();
		 System.out.println("WebObj " + objectClass);
	}

  }

} What is the expected output? What do you see instead? I get below exception:
W/InputDispatcher( 2117): Permission denied: injecting event from pid 31309 uid 10142 to window Window{4356e190 com.sec.android.app.launcher/com.android.launcher2.Launcher paused=false} owned by uid 10001

I/TestRunner(31309): failed: testDisplayBlackBox(com.sqs.test.P0002_tc0001_testcase1_N1_D1)

I/TestRunner(31309): ----- begin exception -----

W/InputManager( 2117): Input event injection from pid 31309 permission denied.

I/TestRunner(31309): 

I/TestRunner(31309): java.lang.NullPointerException

I/TestRunner(31309): 	at java.io.Reader.<init>(Reader.java:64)

I/TestRunner(31309): 	at java.io.InputStreamReader.<init>(InputStreamReader.java:122)

I/TestRunner(31309): 	at java.io.InputStreamReader.<init>(InputStreamReader.java:59)

I/TestRunner(31309): 	at com.sqs.test.cls_WebUtils.getJavaScriptAsString(cls_WebUtils.java:281)

I/TestRunner(31309): 	at com.sqs.test.cls_WebUtils.prepareForStartOfJavascriptExecution(cls_WebUtils.java:134)

I/TestRunner(31309): 	at com.sqs.test.cls_WebUtils.executeJavaScriptFunction(cls_WebUtils.java:214)

I/TestRunner(31309): 	at com.sqs.test.cls_WebUtils.getCurrentWebElements(cls_WebUtils.java:88)

I/TestRunner(31309): 	at com.sqs.test.Robo.getAllWebElements(Robo.java:4365)

I/TestRunner(31309): 	at com.sqs.test.P0002_tc0001_testcase1_N1_D1.testDisplayBlackBox(P0002_tc0001_testcase1_N1_D1.java:60)

I/TestRunner(31309): 	at java.lang.reflect.Method.invokeNative(Native Method)

I/TestRunner(31309): 	at java.lang.reflect.Method.invoke(Method.java:511)

I/TestRunner(31309): 	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)

I/TestRunner(31309): 	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)

I/TestRunner(31309): 	at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)

I/TestRunner(31309): 	at junit.framework.TestCase.runBare(TestCase.java:134)

I/TestRunner(31309): 	at junit.framework.TestResult$1.protect(TestResult.java:115)

I/TestRunner(31309): 	at junit.framework.TestResult.runProtected(TestResult.java:133)

I/TestRunner(31309): 	at junit.framework.TestResult.run(TestResult.java:118)

I/TestRunner(31309): 	at junit.framework.TestCase.run(TestCase.java:124)

I/TestRunner(31309): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:192)

I/TestRunner(31309): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:177)

I/TestRunner(31309): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)

I/TestRunner(31309): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1619)

I/TestRunner(31309): ----- end exception ----- What version of the product are you using? On what operating system? Using Robotium 4.0 Please provide any additional information below.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=459_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on May 20, 2013 04:20:56_

Please use the jar from the downloads list: https://code.google.com/p/robotium/downloads/list

**Status:** Invalid  
  **Owner:** renasr...@gmail.com
