### ISSUE TITLE
" ClickOnScreen " doesn't work

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#550]
_From [lqca...@163.com](https://code.google.com/u/102113066117275777154/) on June 07, 2013 00:23:48_

1.I select a picture by the method “solo.clickOnScreen(387, 381);”

--Robotium -solo 4.1.jar
\---
junit.framework.AssertionFailedError: Click can not be completed!
at com.jayway.android.robotium.solo.Clicker.clickOnScreen(Clicker.java:91)
at com.jayway.android.robotium.solo.Solo.clickOnScreen(Solo.java:649)
at com.ffcs.SmsHelper.test.TestAutoReply.testA11Sms(TestAutoReply.java:40)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:177)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1619)

_Original issue: http://code.google.com/p/robotium/issues/detail?id=471_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 07, 2013 13:20:37_

Due to the picture selector belonging to another process then the application under test Robotium is not allowed to interact with it. This is a restriction of the Android platform.  Please see Q&A wiki page for more information.

**Status:** Invalid  
  **Owner:** renasr...@gmail.com
