### ISSUE TITLE
Test run failed: Instrumentation run failed due to 'java.lang.IllegalAccessError'

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#551]
_From [skycity...@gmail.com](https://code.google.com/u/111958774071502456326/) on June 07, 2013 04:51:35_

when I write a test to test a APK,it can run in android 4.0 and up ,but run in the android 2.3 it can't work well .and happen 'java.lang.IllegalAccessError' error.

java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation

how can I do .I try all common function

_Original issue: http://code.google.com/p/robotium/issues/detail?id=472_

**Comment by renas** [comment]
_From [skycity...@gmail.com](https://code.google.com/u/111958774071502456326/) on June 07, 2013 04:55:49_

@@zhai:is service:com.eshore.notify.pushService.PushService
06-07 19:52:59.747: W/PushManager(19764): @@exit PushService!
06-07 19:52:59.747: W/PushManager(19764): @@uncaughtException:java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
06-07 19:52:59.747: W/PushManager(19764): 	at com.eshore.notify.pushService.JsonMapperUtils.getDefaultObjectMapper(Unknown Source)
06-07 19:52:59.747: W/PushManager(19764): 	at com.eshore.notify.pushService.JsonMapperUtils.toJson(Unknown Source)
06-07 19:52:59.747: W/PushManager(19764): 	at com.eshore.notify.pushService.JsonUtils.objectToJson(Unknown Source)
06-07 19:52:59.747: W/PushManager(19764): 	at com.eshore.notify.pushService.PushService.startSend(Unknown Source)
06-07 19:52:59.747: W/PushManager(19764): 	at com.eshore.notify.pushService.PushService.access$1(Unknown Source)
06-07 19:52:59.747: W/PushManager(19764): 	at com.eshore.notify.pushService.PushService$1.handleMessage(Unknown Source)
06-07 19:52:59.747: W/PushManager(19764): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-07 19:52:59.747: W/PushManager(19764): 	at android.os.Looper.loop(Looper.java:130)
06-07 19:52:59.747: W/PushManager(19764): 	at android.app.ActivityThread.main(ActivityThread.java:3703)
06-07 19:52:59.747: W/PushManager(19764): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-07 19:52:59.747: W/PushManager(19764): 	at java.lang.reflect.Method.invoke(Method.java:507)
06-07 19:52:59.747: W/PushManager(19764): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
06-07 19:52:59.747: W/PushManager(19764): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
06-07 19:52:59.747: W/PushManager(19764): 	at dalvik.system.NativeStart.main(Native Method)
06-07 19:52:59.767: E/AndroidRuntime(19764): FATAL EXCEPTION: main
06-07 19:52:59.767: E/AndroidRuntime(19764): java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
06-07 19:52:59.767: E/AndroidRuntime(19764): 	at com.eshore.notify.pushService.JsonMapperUtils.getDefaultObjectMapper(Unknown Source)
06-07 19:52:59.767: E/AndroidRuntime(19764): 	at com.eshore.notify.pushService.JsonMapperUtils.toJson(Unknown Source)
06-07 19:52:59.767: E/AndroidRuntime(19764): 	at com.eshore.notify.pushService.JsonUtils.objectToJson(Unknown Source)
06-07 19:52:59.767: E/AndroidRuntime(19764): 	at com.eshore.notify.pushService.PushService.startSend(Unknown Source)
06-07 19:52:59.767: E/AndroidRuntime(19764): 	at com.eshore.notify.pushService.PushService.access$1(Unknown Source)
06-07 19:52:59.767: E/AndroidRuntime(19764): 	at com.eshore.notify.pushService.PushService$1.handleMessage(Unknown Source)
06-07 19:52:59.767: E/AndroidRuntime(19764): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-07 19:52:59.767: E/AndroidRuntime(19764): 	at android.os.Looper.loop(Looper.java:130)
06-07 19:52:59.767: E/AndroidRuntime(19764): 	at android.app.ActivityThread.main(ActivityThread.java:3703)
06-07 19:52:59.767: E/AndroidRuntime(19764): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-07 19:52:59.767: E/AndroidRuntime(19764): 	at java.lang.reflect.Method.invoke(Method.java:507)
06-07 19:52:59.767: E/AndroidRuntime(19764): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
06-07 19:52:59.767: E/AndroidRuntime(19764): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
06-07 19:52:59.767: E/AndroidRuntime(19764): 	at dalvik.system.NativeStart.main(Native Method)
06-07 19:52:59.777: W/ActivityManager(4257): Error in app com.trunk.ticket running instrumentation ComponentInfo{com.etone.test.main/com.etone.test.runner.instrum.CarTestRunner}:
06-07 19:52:59.777: W/ActivityManager(4257):   java.lang.IllegalAccessError
06-07 19:52:59.777: W/ActivityManager(4257):   java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
06-07 19:52:59.777: I/ActivityManager(4257): Force stopping package com.trunk.ticket uid=10055

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 07, 2013 13:18:09_

This is not an issue in Robotium.

**Status:** Invalid  
  **Owner:** renasr...@gmail.com
