### ISSUE TITLE
takescreenshot()  is failed.

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#566]
_From [chenjunm...@gmail.com](https://code.google.com/u/100954131586309732466/) on July 17, 2013 02:17:41_

What steps will reproduce the problem? 1..I'm trying to use takescreenshot() method.
2.Have added writeExternalStorage permission in the manifest file of the Application under test.
3.Please find attached the Logcat log.
4.I'm using Galaxy i9100 device.
5.I'm using robotium 4.2 . What is the expected output? What do you see instead? What version of the product are you using? On what operating system? Please provide any additional information below.

**Attachment:** [Log.txt](http://code.google.com/p/robotium/issues/detail?id=487)

_Original issue: http://code.google.com/p/robotium/issues/detail?id=487_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on July 17, 2013 04:06:54_

Thanks for reporting this. It will be fixed in the next release.

**Status:** Accepted  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [berg...@uncle.se](https://code.google.com/u/107498801174108257890/) on August 25, 2013 03:03:14_

Just before you get this NullPointerException do you also get a warning similar to this one? And can I get the version of android you are using?

W/System.err(1727): java.lang.NoSuchFieldException: mEGLContextClientVersiond
W/System.err(1727): 	at java.lang.Class.getDeclaredField(Class.java:631)
W/System.err(1727): 	at com.jayway.reflectiontest.Reflect$FieldRf.getField(Reflect.java:110)
W/System.err(1727): 	at com.jayway.reflectiontest.Reflect$FieldRf.out(Reflect.java:68)
W/System.err(1727): 	at com.jayway.reflectiontest.MainActivity.onClick(MainActivity.java:31)
W/System.err(1727): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(1727): 	at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err(1727): 	at android.view.View$1.onClick(View.java:3592)
W/System.err(1727): 	at android.view.View.performClick(View.java:4202)
W/System.err(1727): 	at android.view.View$PerformClick.run(View.java:17340)
W/System.err(1727): 	at android.os.Handler.handleCallback(Handler.java:725)
W/System.err(1727): 	at android.os.Handler.dispatchMessage(Handler.java:92)
W/System.err(1727): 	at android.os.Looper.loop(Looper.java:137)
W/System.err(1727): 	at android.app.ActivityThread.main(ActivityThread.java:5039)
W/System.err(1727): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(1727): 	at java.lang.reflect.Method.invoke(Method.java:511)

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on September 08, 2013 22:13:27_

The nullpointerexception has been fixed in Robotium 4.3.

**Status:** Verified
