### ISSUE TITLE
java.lang.nullpointerexception error on trying to run the project using robotium 

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#570]
_From [sinha.ka...@gmail.com](https://code.google.com/u/103828779966021760852/) on July 23, 2013 02:58:45_

on trying to run the UIAutomator project with robotium .It showing error.

java.lang.NullPointerException
        at com.jayway.android.robotium.solo.ActivityUtils.setupActivityMonitor(A
ctivityUtils.java:102)
        at com.jayway.android.robotium.solo.ActivityUtils.<init>(ActivityUtils.j
ava:55)
        at com.jayway.android.robotium.solo.Solo.<init>(Solo.java:115)
        at com.jayway.android.robotium.solo.Solo.<init>(Solo.java:141)
        at com.android.test.ca.AhaTest.setUp(AhaTest.java:90)
        at junit.framework.TestCase.runBare(TestCase.java:132)
        at junit.framework.TestResult$1.protect(TestResult.java:115)
        at junit.framework.TestResult.runProtected(TestResult.java:133)
        at junit.framework.TestResult.run(TestResult.java:118)
        at junit.framework.TestCase.run(TestCase.java:124)
        at com.android.uiautomator.testrunner.UiAutomatorTestRunner.start(UiAuto
matorTestRunner.java:144)
        at com.android.uiautomator.testrunner.UiAutomatorTestRunner.run(UiAutoma
torTestRunner.java:87)
        at com.android.commands.uiautomator.RunTestCommand.run(RunTestCommand.ja
va:90)
        at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:235)
        at dalvik.system.NativeStart.main(Native Method)

What is the possible solution for the above.If i declare solo object 
solo = new Solo(getintrumentation()): then this error is showing.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=491_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on July 23, 2013 09:35:59_

Use Robotium with activityinstrumentationtestcase2 instead.

**Status:** Invalid
