### ISSUE TITLE
Unable to entertext in Webview page using robotium 4.2

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#572]
_From [sinha.ka...@gmail.com](https://code.google.com/u/103828779966021760852/) on July 26, 2013 11:17:22_

package com.calculator.test;

import org.junit.Test;

import android.test.ActivityInstrumentationTestCase2;

import com.jayway.android.robotium.solo.*;
import com.jayway.android.robotium.solo.By;
import com.jayway.android.robotium.solo.Solo;

@SuppressWarnings("rawtypes")
public class SMPage extends ActivityInstrumentationTestCase2{

	private static final String LAUNCHER_ACTIVITY_FULL_CLASSNAME = "com.aha.android.app.login.WelcomePageActivity";
	private Solo solo;

	private static Class launcherActivityClass;
    static{
            try {
                    launcherActivityClass = Class.forName(LAUNCHER_ACTIVITY_FULL_CLASSNAME);
            } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
            }
    }
	@SuppressWarnings("unchecked")
	public SMPage() {
		super(launcherActivityClass);
	}
	
	@Override
	public void setUp() throws Exception {
		//setUp() is run before a test case is started. 
		//This is where the solo object is created.
		solo = new Solo(getInstrumentation(), getActivity());
	}
	
	@Override
	public void tearDown() throws Exception {
		//tearDown() is run after a test case has finished. 
		//finishOpenedActivities() will finish all the activities that have been opened during the test execution.
		solo.finishOpenedActivities();
	}
	
	@Test
	public void testLaunch() throws Exception {
		solo.clickOnText("Login");
		solo.clickOnText("Forgot your password?");
		Thread.sleep(50000);
		solo.typeTextInWebElement(By.name("email"), "sinha.kanak@gmail.com");
		solo.clickOnText("Submit");
		Thread.sleep(5000	

	}
	
	
	
}

Not able to enter text in the webview page . Screen shot attached of the page. Using robotium 4.2.

**Attachment:** [password.pdf](http://code.google.com/p/robotium/issues/detail?id=493)

_Original issue: http://code.google.com/p/robotium/issues/detail?id=493_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on July 27, 2013 22:13:33_

What happens if you use solo.enterTextInWebElement(By.name("email"), "sinha.kanak@gmail.com");

**Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [sinha.ka...@gmail.com](https://code.google.com/u/103828779966021760852/) on July 28, 2013 22:06:50_

junit.framework.AssertionFailedError: WebElement with name: 'email' is not found!
at com.jayway.android.robotium.solo.Clicker.clickOnWebElement(Clicker.java:325)
at com.jayway.android.robotium.solo.Solo.clickOnWebElement(Solo.java:868)
at com.jayway.android.robotium.solo.Solo.typeTextInWebElement(Solo.java:1685)
at com.calculator.test.SMPage.testLaunch(SMPage.java:67)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661)

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on July 29, 2013 08:19:51_

What do you see in the log if you do this:

for(WebElement webElement : solo.getCurrentWebElements()){
    Log.d("Robotium", "id: '" + webElement.getId() + "' text: '" + webElement.getText() + "' name: '" + webElement.getName() + "' class name: '" + webElement.getClassName() + "' tag name: '" + webElement.getTagName() + "'");

**Comment by renas** [comment]
_From [sinha.ka...@gmail.com](https://code.google.com/u/103828779966021760852/) on July 30, 2013 00:55:57_

It working fine. the element name i was entering was wrong. so entered the correct one and it is working

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on July 30, 2013 01:12:27_

**Status:** Invalid

**Comment by renas** [comment]
_From [gpprakas...@gmail.com](https://code.google.com/u/101938211124354107992/) on July 31, 2014 23:47:53_

I am newbie to Robotium.Could anyone please tell me where i can see the properties logged via Log.d in the comment 4.
