### ISSUE TITLE
RobotiumRC: Install RobotiumRCOverlay fail on mac os x

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#581]
_From [enduranc...@gmail.com](https://code.google.com/u/114748201115657892143/) on August 22, 2013 03:25:36_

What steps will reproduce the problem? 1. Try to install RobotiumRCOverlay2013809 based on RobotiumRCOverlay2013712.
2. Throw exception, fail to install. What is the expected output? What do you see instead? Expected: Install successful.
Actual: fail What version of the product are you using? On what operating system? mac os x 10.8.3 Please provide any additional information below. Error log:
Installing on 'mac os x' System
RobotiumRC InstallDir: /Library/robotiumrc
Start RobotiumRC Installation......
Unzip RobotiumRCInstall.ZIP ......
 
File Extraction Error:
error in opening zip file
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:128)
	at java.util.zip.ZipFile.<init>(ZipFile.java:89)
	at org.safs.text.FileUtilities.unzipFile(FileUtilities.java:630)
	at com.jayway.android.robotium.remotecontrol.install.SilentInstaller.doSAFSInstall(SilentInstaller.java:254)
	at com.jayway.android.robotium.remotecontrol.install.SilentInstaller.main(SilentInstaller.java:686)
./Overlay-Mac.sh: line 93: ./modifyProjectFiles.sh: No such file or directory

_Original issue: http://code.google.com/p/robotium/issues/detail?id=502_

**Comment by renas** [comment]
_From [carl.na...@sas.com](https://code.google.com/u/109112886858732574266/) on August 22, 2013 06:00:42_

modifyProjectFiles.sh was part of the original release.  So you do have it.  If you unzipped the Overlay somewhere else, then I have confirmed that it is missing.  However, you can copy the modifyProjectFile.sh you have to that temporary unzip directory to complete the install.

Thanks for reporting this.

**Status:** Accepted

**Comment by renas** [comment]
_From [carl.na...@sas.com](https://code.google.com/u/109112886858732574266/) on August 22, 2013 08:14:17_

**Owner:** carl.na...@sas.com

**Comment by renas** [comment]
_From [enduranc...@gmail.com](https://code.google.com/u/114748201115657892143/) on August 22, 2013 08:39:52_

I tried your suggestion, still meet an exception, but looks like install successful anyway.....

Log:

Installing on 'mac os x' System
RobotiumRC InstallDir: /Library/robotiumrc
Start RobotiumRC Installation......
Unzip RobotiumRCInstall.ZIP ......
 
File Extraction Error:
error in opening zip file
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:128)
	at java.util.zip.ZipFile.<init>(ZipFile.java:89)
	at org.safs.text.FileUtilities.unzipFile(FileUtilities.java:630)
	at com.jayway.android.robotium.remotecontrol.install.SilentInstaller.doSAFSInstall(SilentInstaller.java:254)
	at com.jayway.android.robotium.remotecontrol.install.SilentInstaller.main(SilentInstaller.java:686)
ANDROID_HOME=/Users/TobyTang/android/android/sdk
Creating /Library/robotiumrc/SAFSTCPMessenger/local.properties
Creating /Library/robotiumrc/RobotiumTestRunner/local.properties
Modifying file and directory permissions for write access...

**Comment by renas** [comment]
_From [carl.na...@sas.com](https://code.google.com/u/109112886858732574266/) on August 29, 2013 11:15:39_

There were actually a couple of different things going on causing this.  The good news is I have fixed the install issues on Mac and even improved it to provide the same opportunity for automatic builds of the TCPMessenger and both TestRunners AND the sample SpinnerActivity--assuming the environment is properly prepared to perform them.

However, there is a remaining issue of Mac Android emulators crashing on attempts to unlock the screen.  So I am torn on whether to release now with broken Mac emulators, or try to fix the emulator issue and then release.

Comments are welcome.

**Comment by renas** [comment]
_From [enduranc...@gmail.com](https://code.google.com/u/114748201115657892143/) on August 29, 2013 19:17:30_

Fix the emulator issue and then release will be better since it's a big issue, sometime even block issue.

BTW, could you also add methods to support launch emulator with custom params, like this format below,

emulator -avd TestEmulator -prop prop=xxx - prop prop=xxx 

it will be a good help to control the initial emulator status..

**Comment by renas** [comment]
_From [carl.na...@sas.com](https://code.google.com/u/109112886858732574266/) on September 04, 2013 08:47:25_

I have fixed the install issues and all code has been pushed to CVS.

This will be available in the next RobotiumRC release.  This should be later this week, or next week alongside the anticipated next release of core Robotium.

Concerning the desire to support additional options on the launch of the emulator--that is not currently in the new code.  However, the start of the emulator can occur via a call to the android tool, or the StartEmulator tool provided with safsautoandroid.jar.

Sample Windows invocation:

SET EMU=SprintEvo
@REM SET EMU=TransformerPrime
@REM SET EMU=AtomX86_412

java "-Dandroid-home=C:\Program Files (x86)\Android\android-sdk" org.safs.android.auto.lib.StartEmulator -no-snapstorage -avd %EMU% http://safsdev.sourceforge.net/doc/org/safs/android/auto/lib/StartEmulator.html Carl Nagle
SAS Research and Development
Planning, Operations and Strategy
General Applications and Tools
carl.nagle@sas.com

**Status:** Fixed
