### ISSUE TITLE
Intent in process com.emicnet.emicall resolved to different process com.emicnet.emicall:sipStack: ...

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#609]
_From [xhou1102...@gmail.com](https://code.google.com/u/101557602884781666490/) on October 08, 2013 02:46:05_

The Failure Trace :

java.lang.RuntimeException: Intent in process com.emicnet.emicall resolved to different process com.emicnet.emicall:sipStack: Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=com.emicnet.emicall/.ui.SplashActivity }
at android.app.Instrumentation.startActivitySync(Instrumentation.java:385)
at android.test.InstrumentationTestCase.launchActivityWithIntent(InstrumentationTestCase.java:119)
at android.test.InstrumentationTestCase.launchActivity(InstrumentationTestCase.java:97)
at android.test.ActivityInstrumentationTestCase2.getActivity(ActivityInstrumentationTestCase2.java:104)
at com.emicnet.emicall.test.Test.setUp(Test.java:27)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)

1, My App process is ":sipStack"
 AndroidManifest.xml:
  ...
   \<activity
            android:name="com.emicnet.emicall.ui.EmiSipHome"
            android:exported="false"
            android:launchMode="singleTop"
            android:process=":sipStack"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustPan" >
  ...
2, My testcase  AndroidManifest.xml:
\<?xml version="1.0" encoding="utf-8"?>
\<manifest xmlns:android=" http://schemas.android.com/apk/res/android "
    package="com.emicnet.emicall.test"
    android:versionCode="1"
    android:versionName="1.0" >

    \<uses-sdk android:minSdkVersion="8" />

    \<instrumentation
        android:name="android.test.InstrumentationTestRunner"
        android:targetPackage="com.emicnet.emicall" />

    \<application
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name" >
        \<uses-library android:name="android.test.runner" />
    \</application>

\</manifest>

_Original issue: http://code.google.com/p/robotium/issues/detail?id=530_

**Comment by renas** [comment]
_From [xhou1102...@gmail.com](https://code.google.com/u/101557602884781666490/) on October 08, 2013 18:45:48_

Is there any problem that I can`t run my case

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on October 09, 2013 09:36:22_

Im not sure what your problem is. This is an issue tracker for Robotium problems. Your issue is with android.test.

**Status:** Invalid  
  **Owner:** renasr...@gmail.com
