### ISSUE TITLE
Problem in running test methods on queue (it works when run alone).

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#614]
_From [flavioca...@gmail.com](https://code.google.com/u/107380997665066938982/) on October 17, 2013 02:58:04_

What steps will reproduce the problem? 1. I can run a single test method selecting it and running as Android Junit test.
2. Test crashes on same test method when I try to run test methods in queue. What is the expected output? What do you see instead? I'd like the test goes on but it stops and it logs me the information listed before. What version of the product are you using? On what operating system? I'm having this problem on Robotium 4.2 / 4.3; Android version is 4.2.2 on Samsung S4 Please provide any additional information below. The console of eclipse print me this error: 
[2013-10-17 11:24:51 - MyAppTestSprint2_GPS_ON] Test run failed: Instrumentation run failed due to 'java.lang.IllegalArgumentException'
[2013-10-17 11:24:51 - MyAppTestSprint2_GPS_ON] Test run finished

Logcat print me this information:
10-17 11:21:08.483: E/WindowManager(11023): Activity com.xxx.MyAppnew.activities.HomeScreenActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{4209bde8 V.E..... R......D 0,0-1026,486} that was originally added here
10-17 11:21:08.483: E/WindowManager(11023): android.view.WindowLeaked: Activity com.xxx.MyAppnew.activities.HomeScreenActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{4209bde8 V.E..... R......D 0,0-1026,486} that was originally added here
10-17 11:21:08.483: E/WindowManager(11023): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:426)
10-17 11:21:08.483: E/WindowManager(11023): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:235)
10-17 11:21:08.483: E/WindowManager(11023): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
10-17 11:21:08.483: E/WindowManager(11023): 	at android.app.Dialog.show(Dialog.java:282)
10-17 11:21:08.483: E/WindowManager(11023): 	at com.xxx.MyAppnew.utils.ProgressBarDialog.showProgressDialog(ProgressBarDialog.java:27)
10-17 11:21:08.483: E/WindowManager(11023): 	at com.xxx.MyAppnew.utils.ProgressBarDialog.<init>(ProgressBarDialog.java:13)
10-17 11:21:08.483: E/WindowManager(11023): 	at com.xxx.MyAppnew.activities.HomeTabCouponsFragment.fetchStores(HomeTabCouponsFragment.java:628)
10-17 11:21:08.483: E/WindowManager(11023): 	at com.xxx.MyAppnew.activities.HomeTabCouponsFragment.startDowload(HomeTabCouponsFragment.java:619)
10-17 11:21:08.483: E/WindowManager(11023): 	at com.xxx.MyAppnew.activities.HomeTabCouponsFragment.fetchGpsLocation(HomeTabCouponsFragment.java:401)
10-17 11:21:08.483: E/WindowManager(11023): 	at com.xxx.MyAppnew.activities.HomeTabCouponsFragment.makeNearestView(HomeTabCouponsFragment.java:388)
10-17 11:21:08.483: E/WindowManager(11023): 	at com.xxx.MyAppnew.activities.HomeScreenActivity.onActivityResult(HomeScreenActivity.java:746)
10-17 11:21:08.483: E/WindowManager(11023): 	at android.app.Activity.dispatchActivityResult(Activity.java:5439)
10-17 11:21:08.483: E/WindowManager(11023): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3427)
10-17 11:21:08.483: E/WindowManager(11023): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3474)
10-17 11:21:08.483: E/WindowManager(11023): 	at android.app.ActivityThread.access$1200(ActivityThread.java:152)
10-17 11:21:08.483: E/WindowManager(11023): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1330)
10-17 11:21:08.483: E/WindowManager(11023): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-17 11:21:08.483: E/WindowManager(11023): 	at android.os.Looper.loop(Looper.java:137)
10-17 11:21:08.483: E/WindowManager(11023): 	at android.app.ActivityThread.main(ActivityThread.java:5328)
10-17 11:21:08.483: E/WindowManager(11023): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-17 11:21:08.483: E/WindowManager(11023): 	at java.lang.reflect.Method.invoke(Method.java:511)
10-17 11:21:08.483: E/WindowManager(11023): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
10-17 11:21:08.483: E/WindowManager(11023): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
10-17 11:21:08.483: E/WindowManager(11023): 	at dalvik.system.NativeStart.main(Native Method)
10-17 11:21:08.534: D/dalvikvm(11023): GC_EXPLICIT freed 115K, 17&#37; free 30860K/37132K, paused 4ms+13ms, total 54ms
10-17 11:21:08.534: D/AndroidRuntime(11023): Shutting down VM
10-17 11:21:08.534: W/dalvikvm(11023): threadid=1: thread exiting with uncaught exception (group=0x40f39ac8)
10-17 11:21:08.534: D/AbsListView(11023): [unregisterDoubleTapMotionListener]
10-17 11:21:08.534: I/MotionRecognitionManager(11023):   .unregisterListener : / listener count = 0->0,  
10-17 11:21:08.534: D/AbsListView(11023): unregisterIRListener() is called 
10-17 11:21:08.544: E/AndroidRuntime(11023): FATAL EXCEPTION: main
10-17 11:21:08.544: E/AndroidRuntime(11023): java.lang.IllegalArgumentException: View not attached to window manager
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:402)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:304)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:79)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at android.app.Dialog.dismissDialog(Dialog.java:325)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at android.app.Dialog.dismiss(Dialog.java:307)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at com.xxx.MyAppnew.utils.ProgressBarDialog.hideProgressDialog(ProgressBarDialog.java:31)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at com.xxx.MyAppnew.activities.HomeTabCouponsFragment$5.onComplete(HomeTabCouponsFragment.java:650)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at com.xxx.MyAppnew.activities.HomeTabCouponsFragment$5.onComplete(HomeTabCouponsFragment.java:1)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at com.xxx.MyAppnew.tasks.StoresTask.onPostExecute(StoresTask.java:127)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at com.xxx.MyAppnew.tasks.StoresTask.onPostExecute(StoresTask.java:1)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at android.os.AsyncTask.finish(AsyncTask.java:631)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at android.os.Looper.loop(Looper.java:137)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at android.app.ActivityThread.main(ActivityThread.java:5328)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-17 11:21:08.544: E/AndroidRuntime(11023): 	at java.lang.reflect.Method.invoke(Method.java:511)
10-17 11:21:08.544: E/Andro...

_Original issue: http://code.google.com/p/robotium/issues/detail?id=535_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on October 17, 2013 03:35:46_

This is not a Robotium issue. Maybe this can help: http://stackoverflow.com/questions/11957409/activity-has-leaked-window-com-android-internal-policy-impl-phonewindowdecorvie

**Status:** Invalid  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [hexns...@gmail.com](https://code.google.com/u/113685360572035713774/) on December 03, 2014 22:43:44_

i have met the same problem. Do you resolve it ?
