### ISSUE TITLE
EditText not Found !!!

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#616]
_From [Tlakh...@gmail.com](https://code.google.com/u/109575906032784442151/) on October 21, 2013 09:00:40_

public void testLogin() throws InterruptedException {
		solo.waitForActivity(LAUNCHER_ACTIVITY_FULL_CLASSNAME);		
		solo.clickOnScreen(100, 100);
		solo.clickOnButton("Log In");
		solo.clearEditText(0);
		solo.enterText(0, "stest123");
		solo.clearEditText(1);
		solo.enterText(1, "123456");
		final EditText etext = solo.getEditText(1);
		solo.waitForActivity(LAUNCHER_ACTIVITY_FULL_CLASSNAME);
		Runnable runnable = new Runnable() {
			public void run() {
				etext.onEditorAction(EditorInfo.IME_ACTION_DONE);
			}
		};

		solo.getCurrentActivity().runOnUiThread(runnable);
		assertTrue(solo.searchText("All"));
		       solo.waitForActivity(solo.getCurrentActivity().toString());
		solo.clickOnScreen(239, 761, 1);
		solo.sleep(5000);
	}
	

Why I am getting the below error ??

junit.framework.AssertionFailedError: EditText is not found!
at com.jayway.android.robotium.solo.Waiter.waitForAndGetView(Waiter.java:501)
at com.jayway.android.robotium.solo.Solo.clearEditText(Solo.java:1783)
at com.WhatsApp.test.StartWhatsApp.testLoginToWhatsApp(StartWhatsApp.java:53)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661)

Where is the error???

_Original issue: http://code.google.com/p/robotium/issues/detail?id=537_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on October 21, 2013 23:18:15_

Thanks for reporting this. Would it be possible for you to share an app that exhibits this issue?

**Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [Tlakh...@gmail.com](https://code.google.com/u/109575906032784442151/) on October 22, 2013 00:25:45_

I am sorry. I can't share apk file with you.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on October 22, 2013 00:27:20_

Can you send a screenshot of the screen? You can mail it to renasreda@gmail.com.

**Comment by renas** [comment]
_From [Tlakh...@gmail.com](https://code.google.com/u/109575906032784442151/) on October 22, 2013 01:38:52_

Okay I can do that.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on October 23, 2013 00:29:33_

If the application crashes also the test execution stops.

**Status:** Invalid

**Comment by renas** [comment]
_From [Tlakh...@gmail.com](https://code.google.com/u/109575906032784442151/) on October 23, 2013 00:47:09_

Please tell me what shall I do in such scenario ???

**Comment by renas** [comment]
_From [Tlakh...@gmail.com](https://code.google.com/u/109575906032784442151/) on October 23, 2013 01:53:20_

If it is not EditText, but TextView then could you please let me know how to enter text in textfieds using TextView ???

I am unable to see hierarchy Viewer of an app so I am just guessing EditText/TextView..........
