### ISSUE TITLE
NullPointerException in ScreenshotTaker.getBitmapOfView

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#617]
_From [miraculi...@gmail.com](https://code.google.com/u/100519236307936948879/) on October 22, 2013 23:31:41_

What steps will reproduce the problem? 1. Automate an App on a tablet device
2. Turn display (setActivityOrientation())
3. Take a screenshot with robotium What is the expected output? What do you see instead? Apparently view.getDrawingCache() returns null in some cases, especially when the device has a large screen and the app consumes lots of cpu and memory. There is probably not much we can do to prevent this, but it would be great if we had some kind of null check in ScreenshotTaker.getBitmapOfView(). What version of the product are you using? On what operating system? Robotium 4.3 on two tablets (Android 3.2 and Android 4.0). Please provide any additional information below. 10-23 01:04:17.973 W/dalvikvm(18781): threadid=1: thread exiting with uncaught exception (group=0x40a3b1f8)

10-23 01:04:17.983 E/AndroidRuntime(18781): FATAL EXCEPTION: main

10-23 01:04:17.983 E/AndroidRuntime(18781): java.lang.NullPointerException

10-23 01:04:17.983 E/AndroidRuntime(18781): 	at com.jayway.android.robotium.solo.ScreenshotTaker.getBitmapOfView(ScreenshotTaker.java:221)

10-23 01:04:17.983 E/AndroidRuntime(18781): 	at com.jayway.android.robotium.solo.ScreenshotTaker.access$400(ScreenshotTaker.java:32)

10-23 01:04:17.983 E/AndroidRuntime(18781): 	at com.jayway.android.robotium.solo.ScreenshotTaker$ScreenshotRunnable.run(ScreenshotTaker.java:332)

10-23 01:04:17.983 E/AndroidRuntime(18781): 	at android.os.Handler.handleCallback(Handler.java:605)

10-23 01:04:17.983 E/AndroidRuntime(18781): 	at android.os.Handler.dispatchMessage(Handler.java:92)

10-23 01:04:17.983 E/AndroidRuntime(18781): 	at android.os.Looper.loop(Looper.java:137)

10-23 01:04:17.983 E/AndroidRuntime(18781): 	at android.app.ActivityThread.main(ActivityThread.java:4424)

10-23 01:04:17.983 E/AndroidRuntime(18781): 	at java.lang.reflect.Method.invokeNative(Native Method)

10-23 01:04:17.983 E/AndroidRuntime(18781): 	at java.lang.reflect.Method.invoke(Method.java:511)

10-23 01:04:17.983 E/AndroidRuntime(18781): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)

10-23 01:04:17.983 E/AndroidRuntime(18781): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)

10-23 01:04:17.983 E/AndroidRuntime(18781): 	at dalvik.system.NativeStart.main(Native Method)

10-23 01:04:17.983 W/ActivityManager(  135): Error in app com.xxxxxxxxxxxxxxxxxx running instrumentation ComponentInfo{com.xxxxxxxxxxxxxxxxxx/pl.polidea.instrumentation.PolideaInstrumentationTestRunner}:

10-23 01:04:17.983 W/ActivityManager(  135):   java.lang.NullPointerException

10-23 01:04:17.983 W/ActivityManager(  135):   java.lang.NullPointerException

10-23 01:04:17.983 I/ActivityManager(  135): Force stopping package com.xxxxxxxxxxxxxxxxxx uid=10087

10-23 01:04:17.993 D/AndroidRuntime(18771): Shutting down VM

_Original issue: http://code.google.com/p/robotium/issues/detail?id=538_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on October 23, 2013 00:28:58_

Thanks for reporting this. It will be fixed in the next release.

**Status:** Accepted  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 04, 2013 08:33:06_

Thanks again for reporting this. It has been fixed in 4.3.1.

**Status:** Verified
