### ISSUE TITLE
Xpath testcase fails in android for version less than 4

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#621]
_From [chokkarb...@gmail.com](https://code.google.com/u/102390854943396041703/) on October 24, 2013 04:46:50_

What steps will reproduce the problem? 1. Playing back webapp by xpath in android version less than 4, it fails.(checking with android 2.3   Emulator and galaxy tab )

2.Nexus works fine What is the expected output? What do you see instead? Common webelement xpath, need to work an all the devices. What version of the product are you using? On what operating system? Robotium 4.3 Please provide any additional information below. Attached log details:

10-24 16:24:06.349: I/TestRunner(30946): failed: testmedmo(com.robo.common.test.SamAppTestApk)
10-24 16:24:06.349: I/TestRunner(30946): ----- begin exception -----
10-24 16:24:06.429: I/TestRunner(30946): junit.framework.AssertionFailedError: WebElement with xpath: '//div[@id='root']/div[2]/div/div/div/a/span/div' is not found!
10-24 16:24:06.429: I/TestRunner(30946): 	at junit.framework.Assert.fail(Assert.java:47)
10-24 16:24:06.429: I/TestRunner(30946): 	at junit.framework.Assert.assertTrue(Assert.java:20)
10-24 16:24:06.429: I/TestRunner(30946): 	at com.jayway.android.robotium.solo.Clicker.clickOnWebElement(Clicker.java:343)
10-24 16:24:06.429: I/TestRunner(30946): 	at com.jayway.android.robotium.solo.Solo.clickOnWebElement(Solo.java:890)
10-24 16:24:06.429: I/TestRunner(30946): 	at com.robo.common.test.SamAppTestApk.testmedmo(SamAppTestApk.java:43)
10-24 16:24:06.429: I/TestRunner(30946): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-24 16:24:06.429: I/TestRunner(30946): 	at java.lang.reflect.Method.invoke(Method.java:507)
10-24 16:24:06.429: I/TestRunner(30946): 	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:204)
10-24 16:24:06.429: I/TestRunner(30946): 	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:194)
10-24 16:24:06.429: I/TestRunner(30946): 	at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:186)
10-24 16:24:06.429: I/TestRunner(30946): 	at junit.framework.TestCase.runBare(TestCase.java:127)
10-24 16:24:06.429: I/TestRunner(30946): 	at junit.framework.TestResult$1.protect(TestResult.java:106)
10-24 16:24:06.429: I/TestRunner(30946): 	at junit.framework.TestResult.runProtected(TestResult.java:124)
10-24 16:24:06.429: I/TestRunner(30946): 	at junit.framework.TestResult.run(TestResult.java:109)
10-24 16:24:06.429: I/TestRunner(30946): 	at junit.framework.TestCase.run(TestCase.java:118)
10-24 16:24:06.429: I/TestRunner(30946): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
10-24 16:24:06.429: I/TestRunner(30946): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
10-24 16:24:06.429: I/TestRunner(30946): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:529)
10-24 16:24:06.429: I/TestRunner(30946): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1448)
10-24 16:24:06.429: I/TestRunner(30946): ----- end exception -----
10-24 16:24:06.498: I/TestRunner(30946): finished: testmedmo(com.robo.common.test.SamAppTestApk)

Note:
In google "Issue attachment storage quota exceeded".

So i attached files in host. http://www.mediafire.com/?nn6ohf26k4c0v11

_Original issue: http://code.google.com/p/robotium/issues/detail?id=542_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on October 24, 2013 23:14:40_

Thanks for reporting this.

**Status:** Accepted  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 04, 2013 08:35:46_

Will open up when there is time to do something about this.

**Status:** WontFix
