### ISSUE TITLE
Method solo.clickOnActionBarHomeButton(); doesn't work

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#632]
_From [dmitriy....@gmail.com](https://code.google.com/u/107161100776404870438/) on November 12, 2013 05:57:20_

What steps will reproduce the problem? I'm trying to use solo.clickOnActionBarHomeButton(); 
Nothing special case. Just trying to use it. What is the expected output? What do you see instead? Opens menu / crash of my test What version of the product are you using? On what operating system? robotium 4.3. Android 4.1.2

And in log there are following strings:
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:4867)
at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:979)
at android.view.ViewGroup.invalidateChild(ViewGroup.java:4306)
at android.view.View.invalidate(View.java:10519)
at android.view.View.invalidate(View.java:10474)
at android.support.v4.widget.DrawerLayout.openDrawer(DrawerLayout.java:985)
at android.support.v4.app.Watson.onMenuItemSelected(Watson.java:129)
at com.actionbarsherlock.ActionBarSherlock.callbackOptionsItemSelected(ActionBarSherlock.java:635)
at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchOptionsItemSelected(ActionBarSherlockNative.java:78)
at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:209)
at com.jayway.android.robotium.solo.Clicker.clickOnActionBarHomeButton(Clicker.java:323)
at com.jayway.android.robotium.solo.Solo.clickOnActionBarHomeButton(Solo.java:1243)
at 
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:177)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1608)

_Original issue: http://code.google.com/p/robotium/issues/detail?id=553_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 12, 2013 22:15:53_

Please update to 4.3.1.

**Status:** Invalid  
  **Owner:** renasr...@gmail.com
