### ISSUE TITLE
getView(String) crashes when View is not visible

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#638]
_From [calebfw...@gmail.com](https://code.google.com/u/113225363890702914841/) on December 03, 2013 08:00:12_

What steps will reproduce the problem? 1. View is not visible
2. Call solo.waitForView(solo.getView(String ID)) What is the expected output? What do you see instead? Script waits for view to become visible or after timeout returns false. What version of the product are you using? On what operating system? robotium-solo-4.3.2-SNAPSHOT Please provide any additional information below. This was built using the latest source code. In the previous version, this function worked properly.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=559_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 03, 2013 10:08:37_

Thanks for reporting this. Please send the log.

**Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [calebfw...@gmail.com](https://code.google.com/u/113225363890702914841/) on December 04, 2013 04:04:46_

Here is the log:
E/SurfaceFlinger(  794): ro.sf.lcd_density must be defined as a build property
E/ThrottleService( 1211): problem during onPollAlarm: java.lang.IllegalStateException: problem parsing stats: java.io.FileNotFoundException: /proc/net/xt_qtaguid/iface_stat_all: open failed: ENOENT (No such file or directory)
E/ThrottleService( 1211): Error reading data file
W/ActivityManager( 1211): Unable to start service Intent { act=com.android.email.ACCOUNT_INTENT } U=0: not found
W/ActivityManager( 1211): Unable to start service Intent { act=com.android.email.ACCOUNT_INTENT } U=0: not found
W/Trace   ( 1486): Unexpected value from nativeGetEnabledTags: 0
W/Trace   ( 1486): Unexpected value from nativeGetEnabledTags: 0
E/ActivityThread( 1486): Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@b3f25b90 that was originally bound here
E/ActivityThread( 1486): android.app.ServiceConnectionLeaked: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@b3f25b90 that was originally bound here
E/ActivityThread( 1486): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:969)
E/ActivityThread( 1486): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:863)
E/ActivityThread( 1486): 	at android.app.ContextImpl.bindService(ContextImpl.java:1418)
E/ActivityThread( 1486): 	at android.app.ContextImpl.bindService(ContextImpl.java:1407)
E/ActivityThread( 1486): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:473)
E/ActivityThread( 1486): 	at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:157)
E/ActivityThread( 1486): 	at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:145)
E/ActivityThread( 1486): 	at com.android.emailcommon.service.ServiceProxy.test(ServiceProxy.java:191)
E/ActivityThread( 1486): 	at com.android.exchange.ExchangeService$7.run(ExchangeService.java:1850)
E/ActivityThread( 1486): 	at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:551)
E/ActivityThread( 1486): 	at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:549)
E/ActivityThread( 1486): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
E/ActivityThread( 1486): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
E/ActivityThread( 1486): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
E/ActivityThread( 1486): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
E/ActivityThread( 1486): 	at java.lang.Thread.run(Thread.java:856)
E/StrictMode( 1486): null
E/StrictMode( 1486): android.app.ServiceConnectionLeaked: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@b3f25b90 that was originally bound here
E/StrictMode( 1486): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:969)
E/StrictMode( 1486): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:863)
E/StrictMode( 1486): 	at android.app.ContextImpl.bindService(ContextImpl.java:1418)
E/StrictMode( 1486): 	at android.app.ContextImpl.bindService(ContextImpl.java:1407)
E/StrictMode( 1486): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:473)
E/StrictMode( 1486): 	at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:157)
E/StrictMode( 1486): 	at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:145)
E/StrictMode( 1486): 	at com.android.emailcommon.service.ServiceProxy.test(ServiceProxy.java:191)
E/StrictMode( 1486): 	at com.android.exchange.ExchangeService$7.run(ExchangeService.java:1850)
E/StrictMode( 1486): 	at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:551)
E/StrictMode( 1486): 	at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:549)
E/StrictMode( 1486): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
E/StrictMode( 1486): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
E/StrictMode( 1486): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
E/StrictMode( 1486): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
E/StrictMode( 1486): 	at java.lang.Thread.run(Thread.java:856)
W/ActivityManager( 1211): Unbind failed: could not find connection for android.os.BinderProxy@b40e8928
E/ActivityThread( 1486): Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@b3f1f840 that was originally bound here
E/ActivityThread( 1486): android.app.ServiceConnectionLeaked: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@b3f1f840 that was originally bound here
E/ActivityThread( 1486): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:969)
E/ActivityThread( 1486): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:863)
E/ActivityThread( 1486): 	at android.app.ContextImpl.bindService(ContextImpl.java:1418)
E/ActivityThread( 1486): 	at android.app.ContextImpl.bindService(ContextImpl.java:1407)
E/ActivityThread( 1486): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:473)
E/ActivityThread( 1486): 	at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:157)
E/ActivityThread( 1486): 	at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:145)
E/ActivityThread( 1486): 	at com.android.emailcommon.service.AccountServiceProxy.getDeviceId(AccountServiceProxy.java:116)
E/ActivityThread( 1486): 	at com.android.exchange.ExchangeService.getDeviceId(ExchangeService.java:1249)
E/ActivityThread( 1486): 	at com.android.exchange.ExchangeService$7.run(ExchangeService.java:1856)
E/ActivityThread( 1486): 	at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:551)
E/ActivityThread( 1486): 	at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:549)
E/ActivityThread( 1486): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
E/ActivityThread( 1486): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
E/ActivityThread( 1486): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
E/ActivityThread( 1486): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
E/ActivityThread( 1486): 	at java.lang.Thread.run(Thread.java:856)
E/StrictMode( 1486): null
E/StrictMode( 1486): android.app.ServiceConnectionLeaked: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@b3f1f840 that was originally bound here
E/StrictMode( 1486): 	at android.app.LoadedApk$ServiceDispatcher....

**Comment by renas** [comment]
_From [calebfw...@gmail.com](https://code.google.com/u/113225363890702914841/) on December 04, 2013 04:04:46_

...<init>(LoadedApk.java:969)
E/StrictMode( 1486): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:863)
E/StrictMode( 1486): 	at android.app.ContextImpl.bindService(ContextImpl.java:1418)
E/StrictMode( 1486): 	at android.app.ContextImpl.bindService(ContextImpl.java:1407)
E/StrictMode( 1486): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:473)
E/StrictMode( 1486): 	at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:157)
E/StrictMode( 1486): 	at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:145)
E/StrictMode( 1486): 	at com.android.emailcommon.service.AccountServiceProxy.getDeviceId(AccountServiceProxy.java:116)
E/StrictMode( 1486): 	at com.android.exchange.ExchangeService.getDeviceId(ExchangeService.java:1249)
E/StrictMode( 1486): 	at com.android.exchange.ExchangeService$7.run(ExchangeService.java:1856)
E/StrictMode( 1486): 	at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:551)
E/StrictMode( 1486): 	at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:549)
E/StrictMode( 1486): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
E/StrictMode( 1486): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
E/StrictMode( 1486): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
E/StrictMode( 1486): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
E/StrictMode( 1486): 	at java.lang.Thread.run(Thread.java:856)
W/ActivityManager( 1211): Unbind failed: could not find connection for android.os.BinderProxy@b40e9010

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 04, 2013 22:31:06_

Nothing in this stacktrace points to Robotium crashing the app. Probably the app crash gets triggered when the Robotium call is made.

**Status:** Invalid
