### ISSUE TITLE
clickOnButton not working on some screens

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#639]
_From [flavioca...@gmail.com](https://code.google.com/u/107380997665066938982/) on December 04, 2013 02:51:17_

What steps will reproduce the problem? 1. I run a script on an application and it runs well. I use solo.clickOnButton(3); to click a button
2. I try to run the same script on a new version of the application but the action solo.clickOnButton(3); has no effects. What is the expected output? What do you see instead? I expect to see a popup after clicking on a button identified by its id- What version of the product are you using? On what operating system? I've this problems on Samsung S4 and other devices too. Android version is 4.2.2 Please provide any additional information below. I think this problem could be related to the fact that these buttons are marked as NAF Button in UI Automator screen.
You can see a screenshot on this page: http://stackoverflow.com/questions/20358149/naf-nodes-automation-with-robotium

_Original issue: http://code.google.com/p/robotium/issues/detail?id=560_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 04, 2013 04:03:53_

Is the layout the same as before? Can you click on the button by changing the index?

**Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [flavioca...@gmail.com](https://code.google.com/u/107380997665066938982/) on December 04, 2013 04:09:48_

Layout has changed but I can't click anymore on buttons using robotium.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 04, 2013 04:16:44_

You cant click on any of the buttons?

**Comment by renas** [comment]
_From [flavioca...@gmail.com](https://code.google.com/u/107380997665066938982/) on December 04, 2013 04:22:29_

If I use solo.clickOnButton(0), solo.clickOnButton(1), ... and so on, It doesn't click. The same button are marked as NAF Node on previous screens; i resolved adding in the code the attribute android:contentdescription but I can't solve the problem i wrote above with robotium.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 04, 2013 06:59:34_

Would it be possible for you to share an app that exhibits this issue?

**Comment by renas** [comment]
_From [flavioca...@gmail.com](https://code.google.com/u/107380997665066938982/) on December 04, 2013 07:02:59_

I can't because I'm not the owner but I'm just working on it to evaluate benefit of automation :(

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 04, 2013 23:54:44_

What if you use the one of the ID:s? solo.clickOnView(solo.getString(String id));

**Comment by renas** [comment]
_From [flavioca...@gmail.com](https://code.google.com/u/107380997665066938982/) on December 05, 2013 03:13:53_

I can use this command on button with label but I can't on button with just an image. Right? I need to click on accept button whose id is "accept_button" but it has no label.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 05, 2013 03:15:32_

You can use it on all views. The recommendation is to always use ID:s if
possible.

/Renas

**Comment by renas** [comment]
_From [flavioca...@gmail.com](https://code.google.com/u/107380997665066938982/) on December 05, 2013 03:25:11_

I'm trying with this: solo.clickOnButton(solo.getString("acceptbutton"));	 
but it doesn't work.

This is the failure trace:
android.content.res.Resources$NotFoundException: String resource ID #0x0
at android.content.res.Resources.getText(Resources.java:1057)
at android.content.res.Resources.getString(Resources.java:1149)
at android.content.Context.getString(Context.java:332)
at com.jayway.android.robotium.solo.Getter.getString(Getter.java:81)
at com.jayway.android.robotium.solo.Getter.getString(Getter.java:99)
at com.jayway.android.robotium.solo.Solo.getString(Solo.java:2460)
at com.MWalletTest.TestApk.test_coupons_002(TestApk.java:208)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1698)

In the same screen there are more items with same id ("acceptbutton");

**Comment by renas** [comment]
_From [flavioca...@gmail.com](https://code.google.com/u/107380997665066938982/) on December 05, 2013 07:06:41_

If you want I can share my desktop with TeamViewer so you can inspect both code, layouts and whatelse you think could be useful.

**Comment by renas** [comment]
_From [flavioca...@gmail.com](https://code.google.com/u/107380997665066938982/) on December 09, 2013 06:02:16_

I found a tip; button index has been scaled; even if I don't add other button to layout, now buttons have an higher index; so I can still see them.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 22, 2013 00:18:25_

The index is based on how many views of a kind that are available.

**Status:** Invalid
