### ISSUE TITLE
Edit Text not taking values!

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#641]
_From [kumar.mo...@gmail.com](https://code.google.com/u/107787737324752900518/) on December 06, 2013 00:48:49_

I am running my below solo script:

public void testCanOpenSettings() throws InterruptedException{	
		try{
			solo.enterText(1, "test");
			solo.enterText(3, "test");
			solo.clickOnButton("Login");
			solo.sleep(3000);
			solo.clickOnButton("Logout");
		}
		catch(Exception e){
			e.printStackTrace();
		}
} What is the expected output? What do you see instead? junit.framework.AssertionFailedError: 4 EditTexts are not found!
at com.jayway.android.robotium.solo.Waiter.waitForAndGetView(Waiter.java:507)
at com.jayway.android.robotium.solo.Solo.enterText(Solo.java:1681)
at com.androidhive.sessions.TestSessionManagement.testCanOpenSettings(TestSessionManagement.java:42)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661) What version of the product are you using? On what operating system? 1.Windows 7 Please provide any additional information below. 1.First Edit text is not taking values.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=562_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 06, 2013 06:37:00_

The index of the first EditText is 0. Index of second 1 etc.

**Status:** Invalid  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 06, 2013 06:37:00_

The index of the first EditText is 0. Index of second 1 etc.

**Comment by renas** [comment]
_From [kumar.mo...@gmail.com](https://code.google.com/u/107787737324752900518/) on December 06, 2013 08:56:10_

Yes its working fine! Thanks buddy!
