### ISSUE TITLE
java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.EditText

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#644]
_From [mgmanika...@gmail.com](https://code.google.com/u/116192218524012817642/) on December 14, 2013 04:41:22_

What steps will reproduce the problem? 1.	EditText editText = (EditText) solo.getCurrentActivity().findViewById(SRC_R.id.username);
	solo.enterText(editText, "Username");
2.	EditText editText = (EditText) solo.getView(SRC_R.id.pinValue);
	solo.enterText(editText, "Username"); What is the expected output? What do you see instead? java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.EditText
at com.mob.page.SignInPage.enterUsername(SignInPage.java:75)
at com.mob.test.SignInTest.test1_SignInWithmobAccount(SignInTest.java:35)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701) What version of the product are you using? On what operating system? robotium-solo-4.3.jar, Android 4.3.1 Please provide any additional information below. I don't know why this misbehaviour , apart from this project above command working fine.

Please let know what could be the problem and how to resolve.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=565_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 15, 2013 00:35:13_

You trying to cast a LinerLayout to an EditText. You need to use the correct resource ID. If you dont know the resource ID you can use enterText with index instead. Please see the javadoc.

**Status:** Invalid

**Comment by renas** [comment]
_From [mgmanika...@gmail.com](https://code.google.com/u/116192218524012817642/) on December 15, 2013 05:10:27_

Thank you for reply.

Above mention  resource ID's are corresponding EditText ID only, I got these ID's via  hieararchyviewer.

So what could be the issue. Please help me.
