### ISSUE TITLE
ArrayList cannot be cast to android.view.View[]

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#647]
_From [simonro...@gmail.com](https://code.google.com/u/112884998850952343960/) on January 02, 2014 04:48:07_

What steps will reproduce the problem? 1. Buy a Nexus 5
2. Start using a really simple instructions like solo.waitForText("Demo data launched"); What is the expected output? What do you see instead? Test should start as usual. What version of the product are you using? On what operating system? Robotium 4.3.1, Android 4.4.2 Please provide any additional information below. java.lang.RuntimeException: java.lang.ClassCastException: java.util.ArrayList cannot be cast to android.view.View[]
at com.jayway.android.robotium.solo.Searcher.searchFor(Searcher.java:128)
at com.jayway.android.robotium.solo.Waiter.waitForText(Waiter.java:464)
at com.jayway.android.robotium.solo.Waiter.waitForText(Waiter.java:403)
at com.jayway.android.robotium.solo.Waiter.waitForText(Waiter.java:375)
at com.jayway.android.robotium.solo.Solo.waitForText(Solo.java:200)

_Original issue: http://code.google.com/p/robotium/issues/detail?id=568_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on January 02, 2014 08:49:45_

This issue has been fixed with Robotium 4.3.1. I just dubbel checked on 4.2.2. Download 4.3.1 from here: https://code.google.com/p/robotium/downloads/list And make sure you clean your test project by going to Project --> Clean

**Status:** Invalid  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [Psion...@gmail.com](https://code.google.com/u/117425434047763311599/) on February 03, 2014 14:49:26_

I am currently able to reproduce this issue with Robotium 4.3.1 on an Android Virtual Device running 4.2.2. This issue does NOT reproduce on devices with a lower version of the operating system. I'm currently using Android Studio 0.4.0 with gradle version 1.9. I'd greatly appreciate any help or guidance in this issue.

**Comment by renas** [comment]
_From [Psion...@gmail.com](https://code.google.com/u/117425434047763311599/) on February 03, 2014 17:15:56_

I've updated to 5.0.1 and I no longer have this issue.
