### ISSUE TITLE
Clicker doesn't work (solo.clickOnScreen)

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#655]
_From [andrei.c...@gmail.com](https://code.google.com/u/101116857530603236234/) on February 11, 2014 02:55:59_

What version of the product are you using? On what operating system? 5.0.1/windows7 x64 Please provide any additional information below. junit.framework.AssertionFailedError: View is null and can therefore not be clicked!
    at com.robotium.solo.Clicker.clickOnScreen(Clicker.java:171)
    at com.robotium.solo.Clicker.clickOnScreen(Clicker.java:158)
    at com.robotium.solo.Solo.clickOnView(Solo.java:1006)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
    at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
    at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
    at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)

_Original issue: http://code.google.com/p/robotium/issues/detail?id=576_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on February 11, 2014 08:42:11_

The reason you are getting this issue is due to the View being null when you try to click it. I can recommend you to use solo.getView() to get the view.

**Status:** Invalid  
  **Owner:** renasr...@gmail.com
