### ISSUE TITLE
Cannot click on listview in 4.4.2 devices.

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#685]
_From [Tsvpp.vi...@gmail.com](https://code.google.com/u/117668493188378019990/) on May 15, 2014 00:27:52_

Hi Team,

I'm facing a serious problem in 4.4.2 devices. What steps will reproduce the problem? I am having a Listview and i am trying to perform click operation. i cannot perform click operation it's throwing a exception 

java.lang.ClassCastException: java.util.ArrayList cannot be cast to android.view.View[]
at com.jayway.android.robotium.solo.ViewFetcher.getWindowDecorViews(ViewFetcher.java:399)
at com.jayway.android.robotium.solo.ViewFetcher.getAllViews(ViewFetcher.java:81)
at com.jayway.android.robotium.solo.ViewFetcher.getViews(ViewFetcher.java:199)
at com.jayway.android.robotium.solo.ViewFetcher.getCurrentViews(ViewFetcher.java:318)
at com.jayway.android.robotium.solo.ViewFetcher.getCurrentViews(ViewFetcher.java:305)
at com.jayway.android.robotium.solo.Searcher.searchFor(Searcher.java:142)
at com.jayway.android.robotium.solo.Waiter.waitForView(Waiter.java:145)
at com.jayway.android.robotium.solo.Waiter.waitForViews(Waiter.java:203)
at com.jayway.android.robotium.solo.Solo.scrollDown(Solo.java:1251)

3.I have checked with 4.3 device this working fine and click operation is being performed.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=606_

**Comment by renas** [comment]
_From [Tsvpp.vi...@gmail.com](https://code.google.com/u/117668493188378019990/) on May 15, 2014 00:29:58_

i am using the latest jar "robotium-solo-5.1"

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on May 15, 2014 22:39:50_

Please clean your project and update to 5.0

**Status:** Invalid  
  **Owner:** renasr...@gmail.com
