### ISSUE TITLE
All apis with resource id are not work

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#686]
_From [suo...@gmail.com](https://code.google.com/u/102086854047711326726/) on May 15, 2014 02:43:33_

The following codes works well.

EditText t1 = solo.getEditText("Event name");
solo.enterText(t1, "abcdefg");

===============================================================
But if I change it to 
solo.enterText(com.android.calendar.R.id.title, "abcdefg");
The results will be 
junit.framework.AssertionFailedError: 2131755035 EditTexts are not found!
	at com.robotium.solo.Waiter.waitForAndGetView(Waiter.java:537)
	at com.robotium.solo.Solo.enterText(Solo.java:1719)

The log output 

Log.v("uta", "textedit id=" +String.valueOf(t1.getId()) + " name=" + t1.getResources().getResourceEntryName(t1.getId()));
Log.v("uta", "textedit id from res id=" + String.valueOf(com.android.calendar.R.id.title));

05-15 05:19:49.110: V/uta(6200): textedit id=2131755034 name=title
05-15 05:19:49.180: V/uta(6200): textedit id from res id=2131755034

The issue exists on other widgets and APIs.

The junit.framework.AssertionFailedError: xxxxx is always larger than the real id 1, but it is also not work if I make a workaround. What version of the product are you using? On what operating system? I am working on emulator and modifying aosp calendar. the robotium version is 5.1 Please provide any additional information below.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=607_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on May 15, 2014 22:38:59_

Use solo.getView() if you want to work with resource ID:s

**Status:** Invalid  
  **Owner:** renasr...@gmail.com
