### ISSUE TITLE
process crash when run ui automation test case via robotium to navigate to one activity of product

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#688]
_From [shuhua.w...@gmail.com](https://code.google.com/u/108454633954371280066/) on May 21, 2014 04:41:02_

Product apk uses two jars: android-support-v7-appcompat.jar and android-support-v4.jar. And I added the two jars into the libs of test apk.
When test code navigates to one activity, process crashed. The info is as following:
05-21 15:38:28.626 W/dalvikvm(21697): Class resolved by unexpected DEX: Landroid/support/v7/app/ActionBarActivity;(0x412d7c40):0xda4a0 ref [Landroid/support/v4/app/FragmentActivity;] Landroid/support/v4/app/FragmentActivity;(0x412d7c40):0xda140
05-21 15:38:28.626 W/dalvikvm(21697): (Landroid/support/v7/app/ActionBarActivity; had used a different Landroid/support/v4/app/FragmentActivity; during pre-verification)
05-21 15:38:28.626 W/dalvikvm(21697): Unable to resolve superclass of Landroid/support/v7/app/ActionBarActivity; (236)
05-21 15:38:28.626 W/dalvikvm(21697): Link of class 'Landroid/support/v7/app/ActionBarActivity;' failed
05-21 15:38:28.626 W/dalvikvm(21697): Unable to resolve superclass of Lcom/abc/bbb/client/android/ActivityPrompt; (708)
05-21 15:38:28.626 W/dalvikvm(21697): Link of class 'Lcom/abc/bbb/client/android/ActivityPrompt;' failed
05-21 15:38:28.626 W/dalvikvm(21697): Unable to resolve superclass of Lcom/abc/bbb/client/android/AddressPrompt; (1256)
05-21 15:38:28.626 W/dalvikvm(21697): Link of class 'Lcom/abc/bbb/client/android/AddressPrompt;' failed
05-21 15:38:28.626 D/AndroidRuntime(21697): Shutting down VM
05-21 15:38:28.626 W/dalvikvm(21697): threadid=1: thread exiting with uncaught exception (group=0x40c271f8)
05-21 15:38:28.626 W/System.err(21697): java.lang.NoClassDefFoundError: com/abc/bbb/client/android/AddressPrompt
05-21 15:38:28.631 W/System.err(21697):     at com.abc.bbb.client.android.abc.ViewActivity.onClick(ABCViewActivity.java:1366)
05-21 15:38:28.631 W/System.err(21697):     at android.bbb.bbb.performClick(bbb.java:3620)
05-21 15:38:28.631 W/System.err(21697):     at android.bbb.View$PerformClick.run(bbb.java:14292)
05-21 15:38:28.631 W/System.err(21697):     at android.os.Handler.handleCallback(Handler.java:605)
05-21 15:38:28.631 W/System.err(21697):     at android.os.Handler.dispatchMessage(Handler.java:92)
05-21 15:38:28.631 W/System.err(21697):     at android.os.Looper.loop(Looper.java:137)
05-21 15:38:28.631 W/System.err(21697):     at android.app.ActivityThread.main(ActivityThread.java:4507)
05-21 15:38:28.631 W/System.err(21697):     at java.lang.reflect.Method.invokeNative(Native Method)
05-21 15:38:28.631 W/System.err(21697):     at java.lang.reflect.Method.invoke(Method.java:511)
05-21 15:38:28.631 W/System.err(21697):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:974)
05-21 15:38:28.631 W/System.err(21697):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:741)
05-21 15:38:28.631 W/System.err(21697):     at dalvik.system.NativeStart.main(Native Method)
05-21 15:38:28.631 W/System.err(21697): Caused by: java.lang.ClassNotFoundException: com.abc.bbb.client.android.AddressPrompt
05-21 15:38:28.631 W/System.err(21697):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
05-21 15:38:28.636 W/System.err(21697):     at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
05-21 15:38:28.636 W/System.err(21697):     at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
05-21 15:38:28.636 W/System.err(21697):     ... 12 more

My test env: 
Samsung tab7(android 4.0.3)
\# Project target.
target=android-16

robotium: 3.5.1
Does anyone have any idea about it?

Thanks very much in advance!

_Original issue: http://code.google.com/p/robotium/issues/detail?id=609_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on May 21, 2014 04:48:43_

This issue is not caused by Robotium. Please update Robotium to version 5.1.

**Status:** Invalid  
  **Owner:** renasr...@gmail.com
