### ISSUE TITLE
waitForText() causes NullPointerException

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#691]
_From [Psion...@gmail.com](https://code.google.com/u/117425434047763311599/) on June 05, 2014 11:44:58_

I can't figure out how to reopen an older issue, but I am hitting this issue in the current version (5.1) of Robotium. 

I get the NPE from clickOnText and waitForText, and both NPEs seem to come from the Searcher class. https://code.google.com/p/robotium/issues/detail?id=403

_Original issue: http://code.google.com/p/robotium/issues/detail?id=612_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 06, 2014 03:11:33_

Thanks for reporting this. Can you please paste the log?

**Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [Psion...@gmail.com](https://code.google.com/u/117425434047763311599/) on June 13, 2014 09:34:05_

at com.robotium.solo.Searcher.searchFor(Searcher.java:128)
    at com.robotium.solo.Waiter.waitForText(Waiter.java:479)
    at com.robotium.solo.Waiter.waitForText(Waiter.java:418)
    at com.robotium.solo.Waiter.waitForText(Waiter.java:390)
    at com.robotium.solo.Solo.waitForText(Solo.java:277)
    at BVT.test_BVT_Settings(BVT.java:145)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
    at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
    at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
    at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1738)
Caused by: java.lang.NullPointerException

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 15, 2014 07:07:53_

This seems to be the stacktrace of an older version of Robotium. Please download 5.1 and check if you can reproduce the issue there.

**Comment by renas** [comment]
_From [Psion...@gmail.com](https://code.google.com/u/117425434047763311599/) on June 15, 2014 08:42:48_

Wow... I'm sorry for bugging you with this. You're right. I didn't update my build.gradle files. I was using 5.0.1

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 15, 2014 23:20:19_

No problem. Let us know if encounter any issues with 5.1.

**Status:** Invalid
