### ISSUE TITLE
getWindowDecorViews null pointer exception

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#704]
_From [edwardg...@gmail.com](https://code.google.com/u/102892681195223343692/) on July 22, 2014 11:10:29_

What steps will reproduce the problem? ArrayList views=solo.getCurrentViews(Button.class); What is the expected output? What do you see instead? What version of the product are you using? On what operating system? 5.2.1 Please provide any additional information below. W/System.err( 1934): java.lang.NullPointerException: expected receiver of type android.view.WindowManagerGlobal, but got null
W/System.err( 1934): 	at java.lang.reflect.Field.getField(Native Method)
W/System.err( 1934): 	at java.lang.reflect.Field.get(Field.java:266)
W/System.err( 1934): 	at com.robotium.solo.ViewFetcher.getWindowDecorViews(ViewFetcher.java:506)
W/System.err( 1934): 	at com.robotium.solo.ViewFetcher.getAllViews(ViewFetcher.java:83)
W/System.err( 1934): 	at com.robotium.solo.ViewFetcher.getViews(ViewFetcher.java:204)
W/System.err( 1934): 	at com.robotium.solo.ViewFetcher.getCurrentViews(ViewFetcher.java:325)
W/System.err( 1934): 	at com.robotium.solo.ViewFetcher.getCurrentViews(ViewFetcher.java:311)
W/System.err( 1934): 	at com.robotium.solo.Solo.getCurrentViews(Solo.java:2140)
W/System.err( 1934): 	at com.intel.ami.guiinjector.Injector.testDisplayBlackBox(Injector.java:51)
W/System.err( 1934): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 1934): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 1934): 	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
W/System.err( 1934): 	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
W/System.err( 1934): 	at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
W/System.err( 1934): 	at junit.framework.TestCase.runBare(TestCase.java:134)
W/System.err( 1934): 	at junit.framework.TestResult$1.protect(TestResult.java:115)
W/System.err( 1934): 	at junit.framework.TestResult.runProtected(TestResult.java:133)
W/System.err( 1934): 	at junit.framework.TestResult.run(TestResult.java:118)
W/System.err( 1934): 	at junit.framework.TestCase.run(TestCase.java:124)
W/System.err( 1934): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
W/System.err( 1934): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
W/System.err( 1934): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
W/System.err( 1934): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)

_Original issue: http://code.google.com/p/robotium/issues/detail?id=625_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on July 24, 2014 03:51:20_

Thanks for reporting this. What version of Android are you using?

**Status:** Accepted  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on August 14, 2014 04:55:23_

This is not reproducible by us.

**Status:** Invalid
