### ISSUE TITLE
Activity XXXX.login.LoginActivity has leaked 

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#722]
_From [hexns...@gmail.com](https://code.google.com/u/113685360572035713774/) on December 03, 2014 22:53:07_

What steps will reproduce the problem? 1. I can run a single test method selecting it and running as Android Junit test.
2. Test crashes on same test method when I try to run test methods in queue. What is the expected output? What do you see instead? What version of the product are you using? On what operating system? I'm having this problem on Robotium 5.0; Android version is 2.3.6 on Hawei Please provide any additional information below. public void tearDown() throws Exception {
		
		//activity.finish();
		try {
			solo.finishOpenedActivities();
			logger.info("<B><font color=\"blue\">===============TestCase End=======================</font></B>");
			Logger.shutdown();
		} catch (Throwable e) {
			e.printStackTrace();
		}
		super.tearDown();
	}

12-04 14:45:08.670: E/JavaBinder(5361): !!! FAILED BINDER TRANSACTION !!!
12-04 14:45:08.690: I/ActivityManager(146): Process com.qiandai.feipos_shanghuban.main:remote (pid 6208) has died.
12-04 14:45:08.710: E/ActivityThread(5361): Activity com.qiandai.feipos_shanghuban.login.LoginActivity has leaked 

ServiceConnection com.baidu.location.a@406eaf50 that was originally bound here
12-04 14:45:08.710: E/ActivityThread(5361): android.app.ServiceConnectionLeaked: Activity 

com.qiandai.feipos_shanghuban.login.LoginActivity has leaked ServiceConnection com.baidu.location.a@406eaf50 that was originally 

bound here
12-04 14:45:08.710: E/ActivityThread(5361): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:938)
12-04 14:45:08.710: E/ActivityThread(5361): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:833)
12-04 14:45:08.710: E/ActivityThread(5361): 	at android.app.ContextImpl.bindService(ContextImpl.java:872)
12-04 14:45:08.710: E/ActivityThread(5361): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:347)
12-04 14:45:08.710: E/ActivityThread(5361): 	at com.baidu.location.LocationClient.for(Unknown Source)
12-04 14:45:08.710: E/ActivityThread(5361): 	at com.baidu.location.LocationClient.if(Unknown Source)
12-04 14:45:08.710: E/ActivityThread(5361): 	at com.baidu.location.d.handleMessage(Unknown Source)
12-04 14:45:08.710: E/ActivityThread(5361): 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-04 14:45:08.710: E/ActivityThread(5361): 	at android.os.Looper.loop(Looper.java:130)
12-04 14:45:08.710: E/ActivityThread(5361): 	at android.app.ActivityThread.main(ActivityThread.java:3695)
12-04 14:45:08.710: E/ActivityThread(5361): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-04 14:45:08.710: E/ActivityThread(5361): 	at java.lang.reflect.Method.invoke(Method.java:507)
12-04 14:45:08.710: E/ActivityThread(5361): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run

(ZygoteInit.java:842)
12-04 14:45:08.710: E/ActivityThread(5361): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
12-04 14:45:08.710: E/ActivityThread(5361): 	at dalvik.system.NativeStart.main(Native Method)

_Original issue: http://code.google.com/p/robotium/issues/detail?id=643_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on December 04, 2014 14:28:39_

You have found a bug in the app your testing:

com.qiandai.feipos_shanghuban.login.LoginActivity has leaked ServiceConnection com.baidu.location.a@406eaf50 that was originally 

bound here

**Status:** Invalid  
  **Owner:** renasr...@gmail.com
