### ISSUE TITLE
solo.clickOnText finds the required text but treats it as a different text

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#729]
_From [gil.ujfa...@gmail.com](https://code.google.com/u/107824763016596675587/) on January 19, 2015 06:34:26_

What steps will reproduce the problem? 1.Have a TextView with text= "Weekly (default)"
2.Try to click on it using solo.clickOnText(text, 0, true); What is the expected output? What do you see instead? Expected: the TextView is clicked.
Actual:
junit.framework.AssertionFailedError: Text string: 'Weekly (default)' is not found! What version of the product are you using? On what operating system? robotium 5.2.1, windows 7, java 7 Please provide any additional information below. as appears below the text is actually found by solo but is classified as a different text. i guess that it is a bug that has sometinhg to do with the bracket signs which probably affect the regex trying to match the text.
cheers,
Gil.

Stack trace (and few of the logcat lines):

01-19 13:22:13.045 D/Robotium( 6857): 'Weekly (default)' not found. Have found: 'Notification Frequency'

01-19 13:22:13.045 D/Robotium( 6857): 'Weekly (default)' not found. Have found: 'Daily'

01-19 13:22:13.045 D/Robotium( 6857): 'Weekly (default)' not found. Have found: 'Weekly (default)'

01-19 13:22:13.045 D/Robotium( 6857): 'Weekly (default)' not found. Have found: 'Every 2 weeks'

01-19 13:22:13.045 D/Robotium( 6857): 'Weekly (default)' not found. Have found: 'Monthly'

01-19 13:22:13.045 D/Robotium( 6857): 'Weekly (default)' not found. Have found: 'Never'

01-19 13:22:13.045 E/RobotiumExecutorCleaner( 6857): Exception caught

01-19 13:22:13.045 E/RobotiumExecutorCleaner( 6857): Stack trace:

01-19 13:22:13.045 E/RobotiumExecutorCleaner( 6857): junit.framework.AssertionFailedError: Text string: 'Weekly (default)' is not found!

01-19 13:22:13.045 E/RobotiumExecutorCleaner( 6857): 	at junit.framework.Assert.fail(Assert.java:50)

01-19 13:22:13.045 E/RobotiumExecutorCleaner( 6857): 	at com.robotium.solo.Clicker.clickOnText(Clicker.java:447)

01-19 13:22:13.045 E/RobotiumExecutorCleaner( 6857): 	at com.robotium.solo.Solo.clickOnText(Solo.java:1118)

01-19 13:22:13.045 E/RobotiumExecutorCleaner( 6857): 	at org.topq.mobile.server.impl.soloexecutor.SoloExecutor.clickOnText(SoloExecutor.java:2293)

_Original issue: http://code.google.com/p/robotium/issues/detail?id=650_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on January 21, 2015 00:21:03_

This is due to the regex support in Robotium. Please use Pattern.qoute("text") to bypass it.

**Status:** Invalid  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [gil.ujfa...@gmail.com](https://code.google.com/u/107824763016596675587/) on January 21, 2015 00:43:20_

thanks
