### ISSUE TITLE
When using Solo.clickOnActionBarHomeButton, can't click on text on the NavigationDrawer

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#745]
_From [ban...@gmail.com](https://code.google.com/u/107324241286441219984/) on March 03, 2015 09:19:16_

What steps will reproduce the problem? 1. Use Solo.clickOnActionBarHomeButton to open the navigation drawer
2. Added a sleep for wait until is opened
3. Use Solo.clickOnText to click on one of the navigation items What is the expected output? What do you see instead? Don't find the text of the items that I'm trying to click. I tried searchText and waitForText, and also don't work to find a text on the NavigationDrawer. What version of the product are you using? On what operating system? Robotium 5.0.1. Android 4.X Please provide any additional information below. If I try to get the ImageView from the ActionBar directly using this code:
View view = Solo.getView(android.R.id.home);
Solo.clickOnView(view);

I can click on items in the navigation drawer. However, this solutions leads me to sometimes have SecurityException regarding not having the inject events permission.

What can I do to solve this problem?

_Original issue: http://code.google.com/p/robotium/issues/detail?id=666_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 03, 2015 09:25:37_

The actionbar views are not text views and therefore you need to use getView() and then clickOnView() just as you do. Please update to Robotium 5.3.1 and the security exceptions will be gone. Let me know if it fixes the problem for you.

**Status:** Invalid  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [ban...@gmail.com](https://code.google.com/u/107324241286441219984/) on March 03, 2015 09:35:25_

Thanks for your fast answer.

I was using the clickOnText on the navigation drawer items, not the action bar.

Yes, I will update then to the last version and check if the security exception is gone.

To tap on the 'hamburger' icon, should I use:
Solo.clickOnActionBarHomeButton
OR
View view = Solo.getView(android.R.id.home);
Solo.clickOnView(view);

seems the last one for your answer, however, the method clickOnActionBarHomeButton seems made for that?

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 03, 2015 09:37:31_

Always use the ID. ClickOnActionBarHomeButton does not work on the support
library.

**Comment by renas** [comment]
_From [ban...@gmail.com](https://code.google.com/u/107324241286441219984/) on March 03, 2015 13:35:22_

Still have the same SecurityException (sometimes):
Failure in testDifferentFragmentsCanBeSelected:
junit.framework.AssertionFailedError: Click at (85.0, 147.0) can not be completed! (java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission)
	at com.robotium.solo.Clicker.clickOnScreen(Clicker.java:106)
	at com.robotium.solo.Clicker.clickOnScreen(Clicker.java:205)
	at com.robotium.solo.Clicker.clickOnScreen(Clicker.java:170)
	at com.robotium.solo.Solo.clickOnView(Solo.java:1096)

This is the code:
final View homeView = solo.getView(android.R.id.home);
solo.clickOnView(homeView);
solo.sleep();

Do you have any idea what could be?

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 03, 2015 13:37:11_

Security exceptions are thrown by the Android platform when trying to click on a View that belongs to another app. Is something blocking the view you are trying to click?

**Comment by renas** [comment]
_From [ban...@gmail.com](https://code.google.com/u/107324241286441219984/) on March 03, 2015 13:42:05_

No. I have the last screenshot and our app is the most front (no dialog). Already using Robotium 5.3.1

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 03, 2015 13:43:05_

This is strange. Would it be possible for you to email me your apk?

**Comment by renas** [comment]
_From [ban...@gmail.com](https://code.google.com/u/107324241286441219984/) on March 09, 2015 09:42:58_

Hey,

Sorry for the late response.
Regarding the APK, can't provide the debug version. Or do you want a production version?

The problem still happens on 5.3.1 :(
The device is a Nexus 5 ART with 4.4.2.
Other devices seems more stable (Huawei Valiant Y301 A1 4.1.1 and Sony Experia P 4.0.4)

Thanks
