### ISSUE TITLE
Robotium not working with cordova 3.6.3

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#757]
_From [sktniran...@gmail.com](https://code.google.com/u/104314344570860407724/) on May 19, 2015 00:15:51_

I got this error "Test failed to run to completion. Reason: 'Instrumentation run failed due to 'java.lang.ClassCastException''. Check device logcat for details" when i try to record my cordova app using Robotium. 

here is my detailed log:
05-19 12:31:17.373: E/AndroidRuntime(1709): java.lang.ClassCastException: com.robotium.recorder.executor.e.a cannot be cast to org.apache.cordova.CordovaChromeClient
05-19 12:31:17.373: E/AndroidRuntime(1709): 	at org.apache.cordova.CordovaWebView.setWebChromeClient(CordovaWebView.java:316)
05-19 12:31:17.373: E/AndroidRuntime(1709): 	at com.robotium.recorder.executor.e.l.run(l.java)
05-19 12:31:17.373: E/AndroidRuntime(1709): 	at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:1569)
05-19 12:31:17.373: E/AndroidRuntime(1709): 	at android.os.Handler.handleCallback(Handler.java:605)
05-19 12:31:17.373: E/AndroidRuntime(1709): 	at android.os.Handler.dispatchMessage(Handler.java:92)
05-19 12:31:17.373: E/AndroidRuntime(1709): 	at android.os.Looper.loop(Looper.java:137)
05-19 12:31:17.373: E/AndroidRuntime(1709): 	at android.app.ActivityThread.main(ActivityThread.java:4424)
05-19 12:31:17.373: E/AndroidRuntime(1709): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-19 12:31:17.373: E/AndroidRuntime(1709): 	at java.lang.reflect.Method.invoke(Method.java:511)
05-19 12:31:17.373: E/AndroidRuntime(1709): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
05-19 12:31:17.373: E/AndroidRuntime(1709): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
05-19 12:31:17.373: E/AndroidRuntime(1709): 	at dalvik.system.NativeStart.main(Native Method)

How to solve this issue?

_Original issue: http://code.google.com/p/robotium/issues/detail?id=678_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on May 19, 2015 07:25:14_

Cordova uses their own custom web client and therefore it is not compatible with Robotium Recorder.

**Status:** WontFix  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [nayanshr...@gmail.com](https://code.google.com/u/101169501305555766839/) on June 04, 2015 01:27:21_

So there is no work around by which we can automate Cordova app using Robotium ?
