### ISSUE TITLE
java.lang.OutOfMemoryError occuring on hi-res screenshots

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#759]
_From [cam9...@gmail.com](https://code.google.com/u/101498271695414958343/) on June 03, 2015 18:18:14_

What steps will reproduce the problem? 1.Use emulator with high resolution like Nexus 10 2560x1600
2.Take 16+ screenshots in a session. Error happens sporadically What is the expected output? What do you see instead? Should save the screenshot to storage instead fatally throws an OutOfMemoryError with message like "Failed to allocated XX bytes with XX bytes remaining and XMB until 0". My JVM most certainly does have a high enough maximum and oddly enough I've gotten the error for smaller file sizes when using 1920x1080 resolution emulators. What version of the product are you using? On what operating system? 5.4.1 Please provide any additional information below.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=680_

**Comment by renas** [comment]
_From [cam9...@gmail.com](https://code.google.com/u/101498271695414958343/) on June 04, 2015 05:22:20_

java.lang.OutOfMemoryError: Failed to allocate a 16384012 byte allocation with 15854054 free bytes and 15MB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.Bitmap.nativeCopy(Native Method)
at android.graphics.Bitmap.copy(Bitmap.java:557)
at com.robotium.solo.ScreenshotTaker.getBitmapOfView(ScreenshotTaker.java:246)
at com.robotium.solo.ScreenshotTaker.access$500(ScreenshotTaker.java:36)
at com.robotium.solo.ScreenshotTaker$ScreenshotRunnable.run(ScreenshotTaker.java:374)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by renas** [comment]
_From [cam9...@gmail.com](https://code.google.com/u/101498271695414958343/) on June 05, 2015 06:08:55_

Discussions on similar topics that may be relevant http://stackoverflow.com/questions/3117429/garbage-collector-in-android http://developer.android.com/training/displaying-bitmaps/index.html

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 05, 2015 08:25:46_

Thanks for reporting this.

**Status:** Accepted  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [cam9...@gmail.com](https://code.google.com/u/101498271695414958343/) on June 05, 2015 08:45:01_

So it's possible that I may have been naturally hitting my JVM ceiling since adding "android largeHeap="true"" to my manifest prevented the error. However after looking at the source there may be some optimizations possible in the screenshot process. 

Also have you considered allowing the bitmap configuration to be set in the takeScreenshot() method? RGB_565, for example, could reduce memory usage

**Comment by PrabhatPandey** [comment]
Hi renas, 

Even I am getting the same kind of error. I have 100+ test cases to test the application and in each case when the test is failing, I am taking a screenshot. 

16/23 failed and then the application crashes with the following error 

E/AndroidRuntime(11941): java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 8152436 free bytes and 7MB until OOM
E/AndroidRuntime(11941):     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
E/AndroidRuntime(11941):     at android.graphics.Bitmap.nativeCopy(Native Method)
E/AndroidRuntime(11941):     at android.graphics.Bitmap.copy(Bitmap.java:562)
E/AndroidRuntime(11941):     at com.robotium.solo.ScreenshotTaker.getBitmapOfView(ScreenshotTaker.java:246)
E/AndroidRuntime(11941):     at com.robotium.solo.ScreenshotTaker.access$500(ScreenshotTaker.java:36)
E/AndroidRuntime(11941):     at com.robotium.solo.ScreenshotTaker$ScreenshotRunnable.run(ScreenshotTaker.java:374)
E/AndroidRuntime(11941):     at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(11941):     at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(11941):     at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(11941):     at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime(11941):     at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11941):     at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(11941):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime(11941):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
W/ActivityManager(  753): Error in app com.simpl.android running instrumentation ComponentInfo{com.simpl.android.test/android.test.InstrumentationTestRunner}:
W/ActivityManager(  753):   java.lang.OutOfMemoryError.


As of now I have removed the screenshot method to run the test cases.

I see that the error was reported a long back. Can you tell me is it fixed or not ? 

Thanks

**Comment by renas** [comment]
Can you please try with Robotium 5.5.3?
