### ISSUE TITLE
HorizontalScrollView scroll to right

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#94]
_From [malliknm...@gmail.com](https://code.google.com/u/106657980405433549546/) on August 30, 2010 11:27:54_

What steps will reproduce the problem? 1.Create a HorizontalScrollView and views like buttons which spance more than screen size
2.From solo getViews and select the invisible button of the HorizontalScrollView
3.And do clickOnView(hiddenButton) expected is action from button
but there was no action performed What is the expected output? What do you see instead? Hidden buttons click action has to be performed. I can see the button from getViews but click dont give any output. What version of the product are you using? On what operating system? 1.7 API, Android 2.2, windows XP, on Droid device Please provide any additional information below.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=15_

**Comment by renas** [comment]
_From [malliknm...@gmail.com](https://code.google.com/u/106657980405433549546/) on August 30, 2010 11:29:11_

Addding views to HorizontalScrollView

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on August 30, 2010 23:10:25_

So basically the button is not shown when you want it to be clicked? Robotium tries to emulate a real user so therefore if it can not reach the button (hidden) it will not be able to click it. You should use scrollToSide() before you use clickOnView()/clickOnButton().

**Comment by renas** [comment]
_From [malliknm...@gmail.com](https://code.google.com/u/106657980405433549546/) on August 31, 2010 10:33:31_

I tried it but i have one more scroll view before my HorizontalScrollView on the screen.When i try to do scrollToSide() it happens to first scroll view not to the
second one where my hidden button is.

Or How to scroll specifice ScrollView if there are more than one on screen.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on August 31, 2010 11:05:40_

Use drag() instead, then you can define yourself how it should drag the screen. You might need to use 2 drags after eachother. There is functionality to choose which list to scroll but not which scroll view to scroll.

**Comment by renas** [comment]
_From [malliknm...@gmail.com](https://code.google.com/u/106657980405433549546/) on August 31, 2010 11:33:33_

My  HorizontalScrollView  is very bottom of the screen and my hidden button is far right in the scroll view , when i use drag(0,-50,0,0,10) nothing happens.
I am thinking this will move scrollview 50 units left from 0 in x direction and keep y the same.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on August 31, 2010 11:53:25_

You should write:

int screenWidth = 		 solo.getCurrentActivity().getWindowManager().getDefaultDisplay().getWidth();

drag(0,width -10,0,0,10) //-10  or more depending how far in the right it should start to drag.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on August 31, 2010 11:57:42_

it should be:
drag(width -10,10,20,20,10) //You want to start the drag from the right. The 20 is where the dragging in y should start which should be depending on your screen height.

**Comment by renas** [comment]
_From [malliknm...@gmail.com](https://code.google.com/u/106657980405433549546/) on August 31, 2010 12:35:11_

i get below error when i tried your idea.

check this link how my HorizontalScrollView  look like https://code.google.com/p/mobyfactory-uiwidgets-android/ 08-31 15:31:21.435: INFO/TestRunner(2367): junit.framework.AssertionFailedError: Application can not be dragged!
08-31 15:31:21.435: INFO/TestRunner(2367):     at junit.framework.Assert.fail(Assert.java:47)
08-31 15:31:21.435: INFO/TestRunner(2367):     at junit.framework.Assert.assertTrue(Assert.java:20)
08-31 15:31:21.435: INFO/TestRunner(2367):     at com.jayway.android.robotium.solo.Scroller.drag(Scroller.java:70)
08-31 15:31:21.435: INFO/TestRunner(2367):     at com.jayway.android.robotium.solo.Solo.drag(Solo.java:756)

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on August 31, 2010 13:04:56_

try this:

int height =  solo.getCurrentActivity().getWindowManager().getDefaultDisplay().getHeight();

drag(width -30,20,height-30,height-30,40);

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on August 31, 2010 21:30:52_

According to functionality..

**Status:** Invalid

**Comment by renas** [comment]
_From [malliknm...@gmail.com](https://code.google.com/u/106657980405433549546/) on September 02, 2010 06:11:43_

It worked like charm. Awesome.
Thank you
